import { Question, ConsistencyPair } from "../types";

// ============================================================
// 默契研究所 V2.0 — 一致性校验题 + 回答质量控制系统
// 20 道校验题 (7 组) + 5 道社会期望两难题
// 版本: V2.0-QC-001
// ============================================================

export const CONSISTENCY_QUESTIONS: Question[] = [
  // ========== A | 回应需求校验 ==========
  {
    id: "QC-RN-01",
    phase: "consistency",
    dimension: "response_need",
    kind: "likert",
    text: "如果我非常确定一段关系是稳定的，短时间联系减少通常不会让我怀疑关系本身。",
    scoreDirection: "reverse", // 高分 = 低 response_need
    version: "1.0",
    active: true,
    metadata: { notes: "交叉 RN-02、RN-08、RN-09。区分频率需求 vs 确定感需求" },
  },
  {
    id: "QC-RN-02",
    phase: "consistency",
    dimension: "response_need",
    kind: "likert",
    text: "真正让我难受的很多时候不是消息少，而是不知道「为什么突然变少」。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["clarity_over_frequency"],
  },
  {
    id: "QC-RN-03",
    phase: "consistency",
    dimension: "response_need",
    kind: "likert",
    text: "即使 TA 一天联系我很多次，如果我始终不知道自己在 TA 心里是什么位置，我还是可能不安心。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  // ========== B | 表达校验 ==========
  {
    id: "QC-EX-01",
    phase: "consistency",
    dimension: "expression",
    kind: "likert",
    text: "即使我很不舒服，如果我还没想清楚原因，我通常不会马上表达。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
    metadata: { notes: "交叉 EX-01、EX-10" },
  },
  {
    id: "QC-EX-02",
    phase: "consistency",
    dimension: "expression",
    kind: "likert",
    text: "对真正重要的事情，我宁愿表达得不够完美，也不希望对方完全靠猜。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "QC-EX-03",
    phase: "consistency",
    dimension: "expression",
    kind: "likert",
    text: "我有时嘴上说「没事」，其实心里还是希望对方继续问。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
    signalTags: ["indirect_reassurance_bidding"],
    metadata: { notes: "这不是简单低表达" },
  },
  // ========== C | 空间需求校验 ==========
  {
    id: "QC-SP-01",
    phase: "consistency",
    dimension: "space_need",
    kind: "likert",
    text: "有时候我想独处，并不是因为关系出了问题，只是单纯想恢复自己的状态。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["restorative_space"],
  },
  {
    id: "QC-SP-02",
    phase: "consistency",
    dimension: "space_need",
    kind: "likert",
    text: "如果 TA 明确告诉我「你安心做自己的事情就好」，我通常能更舒服地享受个人空间。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["autonomy_with_reassurance"],
  },
  {
    id: "QC-SP-03",
    phase: "consistency",
    dimension: "space_need",
    kind: "likert",
    text: "即使一整天和喜欢的人相处得很开心，我仍然可能在晚上想自己待一会儿。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  // ========== D | 情绪敏感校验 ==========
  {
    id: "QC-ES-01",
    phase: "consistency",
    dimension: "emotional_sensitivity",
    kind: "likert",
    text: "我经常能发现别人状态发生变化，但并不会马上认为那一定和我有关。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { notes: "区分敏感 vs 自我归因" },
  },
  {
    id: "QC-ES-02",
    phase: "consistency",
    dimension: "emotional_sensitivity",
    kind: "likert",
    text: "如果没有明显线索，我通常不会因为一条简单的消息就判断关系出了问题。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
  },
  {
    id: "QC-ES-03",
    phase: "consistency",
    dimension: "emotional_sensitivity",
    kind: "likert",
    text: "我对语气和态度变化很敏感，但很多时候我也知道自己的第一解释未必正确。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["high_awareness_with_interpretive_restraint"],
  },
  // ========== E | 冲突节奏校验 ==========
  {
    id: "QC-CU-01",
    phase: "consistency",
    dimension: "conflict_urgency",
    kind: "likert",
    text: "我希望问题尽快解决，但如果双方情绪已经很糟，我仍然可以接受有明确时间的暂停。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { notes: "校验 true_conflict_urgency vs needs_reconnection_time" },
  },
  {
    id: "QC-CU-02",
    phase: "consistency",
    dimension: "conflict_urgency",
    kind: "likert",
    text: "对我来说，「暂停一下」本身不可怕，真正难受的是不知道对方还会不会回来继续谈。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["needs_reconnection_time"],
  },
  {
    id: "QC-CU-03",
    phase: "consistency",
    dimension: "conflict_urgency",
    kind: "likert",
    text: "即使问题很重要，只要我确定第二天一定会继续讨论，我通常不会坚持必须当晚解决。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
  },
  // ========== F | 修复校验 ==========
  {
    id: "QC-RP-01",
    phase: "consistency",
    dimension: "repair_orientation",
    kind: "likert",
    text: "我愿意给关系修复机会，但这不代表同一个问题可以无限次重复。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["repair_with_boundaries"],
  },
  {
    id: "QC-RP-02",
    phase: "consistency",
    dimension: "repair_orientation",
    kind: "likert",
    text: "如果 TA 真的持续改变了行为，我愿意根据新的表现重新评价 TA，而不是永远只看过去。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "QC-RP-03",
    phase: "consistency",
    dimension: "repair_orientation",
    kind: "likert",
    text: "对我来说，道歉和真正改变不是一回事。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["behavior_change_required"],
  },
  // ========== G | 互惠/边界校验 ==========
  {
    id: "QC-BD-01",
    phase: "consistency",
    dimension: "expression",
    kind: "likert",
    text: "我可以接受关系里不是每件事情都五五分，只要长期来看双方都觉得自己的付出被看见。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["fairness_model"],
  },
  {
    id: "QC-BD-02",
    phase: "consistency",
    dimension: "space_need",
    kind: "likert",
    text: "和重要的人保持边界，并不代表我不信任或不重视对方。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
];

// ========== 社会期望两难题 (SD-01 ~ 05) ==========
export const SOCIAL_DESIRABILITY_QUESTIONS: Question[] = [
  {
    id: "SD-01",
    phase: "consistency",
    dimension: "conflict_urgency",
    kind: "forced_choice",
    text: "发生冲突时，下面哪一种对你更容易？",
    options: [
      { id: "1", label: "继续把问题说清楚，即使情绪还没有完全稳定。", value: 1 },
      { id: "2", label: "偏左", value: 2 },
      { id: "3", label: "两边都合理。", value: 3 },
      { id: "4", label: "偏右", value: 4 },
      { id: "5", label: "先停下来，即使问题暂时没有结论。", value: 5 },
    ],
    version: "1.0",
    active: true,
    metadata: { notes: "无标准答案 forced_choice" },
  },
  {
    id: "SD-02",
    phase: "consistency",
    dimension: "response_need",
    kind: "forced_choice",
    text: "关系里你更难接受：",
    options: [
      { id: "1", label: "对方不够主动。", value: 1 },
      { id: "2", label: "偏左", value: 2 },
      { id: "3", label: "都差不多", value: 3 },
      { id: "4", label: "偏右", value: 4 },
      { id: "5", label: "对方太频繁要求回应。", value: 5 },
    ],
    version: "1.0",
    active: true,
  },
  {
    id: "SD-03",
    phase: "consistency",
    dimension: "expression",
    kind: "forced_choice",
    text: "如果对方很爱你，但不太擅长表达；和很会表达但行动不够稳定相比，你更难接受哪一种？",
    options: [
      { id: "1", label: "很爱你但不擅长表达", value: 1 },
      { id: "2", label: "偏左", value: 2 },
      { id: "3", label: "都差不多难接受", value: 3 },
      { id: "4", label: "偏右", value: 4 },
      { id: "5", label: "很会表达但行动不稳定", value: 5 },
    ],
    version: "1.0",
    active: true,
    metadata: { notes: "无标准答案" },
  },
  {
    id: "SD-04",
    phase: "consistency",
    dimension: "space_need",
    kind: "forced_choice",
    text: "对你来说，亲密关系里更重要的是：",
    options: [
      { id: "1", label: "知道彼此大部分事情。", value: 1 },
      { id: "2", label: "偏左", value: 2 },
      { id: "3", label: "都重要", value: 3 },
      { id: "4", label: "偏右", value: 4 },
      { id: "5", label: "即使不知道所有事情，也相信彼此。", value: 5 },
    ],
    version: "1.0",
    active: true,
  },
  {
    id: "SD-05",
    phase: "consistency",
    dimension: "emotional_sensitivity",
    kind: "forced_choice",
    text: "哪一种更容易让你累？",
    options: [
      { id: "1", label: "一直照顾对方的感受。", value: 1 },
      { id: "2", label: "偏左", value: 2 },
      { id: "3", label: "都差不多", value: 3 },
      { id: "4", label: "偏右", value: 4 },
      { id: "5", label: "一直猜对方到底在想什么。", value: 5 },
    ],
    version: "1.0",
    active: true,
  },
];

// ========== 一致性配对定义 ==========
export const CONSISTENCY_PAIRS: ConsistencyPair[] = [
  // 回应需求
  { id: "CP-01", questionA: "RN-03", questionB: "RN-04", relationship: "opposite_direction", expectedTolerance: 2, severityWeight: 0.9 },
  { id: "CP-02", questionA: "RN-02", questionB: "QC-RN-01", relationship: "opposite_direction", expectedTolerance: 2, severityWeight: 0.85 },
  { id: "CP-03", questionA: "RN-08", questionB: "QC-RN-02", relationship: "same_direction", expectedTolerance: 2, severityWeight: 0.7 },
  // 表达
  { id: "CP-04", questionA: "EX-01", questionB: "EX-03", relationship: "opposite_direction", expectedTolerance: 2, severityWeight: 0.85 },
  { id: "CP-05", questionA: "EX-01", questionB: "QC-EX-01", relationship: "opposite_direction", expectedTolerance: 2, severityWeight: 0.8 },
  // 空间需求
  { id: "CP-06", questionA: "SP-01", questionB: "SP-03", relationship: "opposite_direction", expectedTolerance: 2, severityWeight: 0.85 },
  { id: "CP-07", questionA: "SP-06", questionB: "QC-SP-02", relationship: "same_direction", expectedTolerance: 2, severityWeight: 0.65 },
  // 情绪敏感
  { id: "CP-08", questionA: "ES-01", questionB: "ES-03", relationship: "opposite_direction", expectedTolerance: 2, severityWeight: 0.85 },
  { id: "CP-09", questionA: "ES-10", questionB: "QC-ES-01", relationship: "same_direction", expectedTolerance: 2, severityWeight: 0.6 },
  // 冲突节奏
  { id: "CP-10", questionA: "CU-01", questionB: "CU-03", relationship: "opposite_direction", expectedTolerance: 2, severityWeight: 0.85 },
  { id: "CP-11", questionA: "CU-10", questionB: "QC-CU-03", relationship: "same_direction", expectedTolerance: 2, severityWeight: 0.7 },
  // 修复
  { id: "CP-12", questionA: "RP-01", questionB: "RP-03", relationship: "opposite_direction", expectedTolerance: 2, severityWeight: 0.8 },
  { id: "CP-13", questionA: "RP-06", questionB: "QC-RP-03", relationship: "same_direction", expectedTolerance: 2, severityWeight: 0.65 },
];
