import { Question } from "../types";

// ============================================================
// 默契研究所 V2.0 — 60 道核心母题
// 6 维度 × 10 道
// 版本: V2.0-QB-001
// ============================================================

export const CORE_QUESTIONS: Question[] = [
  // ========== A | 回应与确定感需求 (response_need) ==========
  {
    id: "RN-01",
    phase: "core",
    dimension: "response_need",
    kind: "likert",
    text: "当一个我很在意的人突然比平时安静很多，我通常会比较快注意到这件事。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    exclusionGroup: "change_detection_01",
    metadata: {
      coreDistinction: "对关系信号变化是否敏感到足以触发确认需求",
      notes: "不要单独用这道题判断需要回应，它也会受到情绪敏感维度影响",
    },
  },
  {
    id: "RN-02",
    phase: "core",
    dimension: "response_need",
    kind: "likert",
    text: "如果一个重要的人很久没有回应，而我不知道原因，我会开始想我们之间是不是发生了什么变化。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: {
      coreDistinction: "不知道为什么是否会迅速转化成关系层面的担忧",
      reportValue: "高分用户以后可以进一步追问：如果 TA 明确告诉你只是忙，你是否会明显安心？这样可以区分需要陪伴和讨厌不确定。",
    },
  },
  {
    id: "RN-03",
    phase: "core",
    dimension: "response_need",
    kind: "likert",
    text: "在重要关系里，我比较希望对方明确告诉我「我们没事」，而不是让我自己判断。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { coreDistinction: "明确确认需求" },
  },
  {
    id: "RN-04",
    phase: "core",
    dimension: "response_need",
    kind: "likert",
    text: "即使一个重要的人暂时减少联系，我通常也不会因此怀疑彼此之间的关系。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
    metadata: { coreDistinction: "内部关系稳定感", notes: "高原始分代表不太依赖即时确认。正式计分：6 - 原始分数" },
  },
  {
    id: "RN-05",
    phase: "core",
    dimension: "response_need",
    kind: "scenario",
    text: "你们原本约好了见面，但 TA 临时取消，而且只简单说了一句「今天不太方便」。你的第一反应更接近：",
    options: [
      { id: "1", label: "没关系，应该有自己的原因。", value: 1 },
      { id: "2", label: "会有一点失望，但不会往关系上想。", value: 2 },
      { id: "3", label: "会想知道发生了什么。", value: 3 },
      { id: "4", label: "会开始担心 TA 是不是不太想见我。", value: 4 },
      { id: "5", label: "我很希望尽快确认 TA 对我的态度有没有变化。", value: 5 },
    ],
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { coreDistinction: "普通事件是否容易被解释成关系信号" },
  },
  {
    id: "RN-06",
    phase: "core",
    dimension: "response_need",
    kind: "scenario",
    text: "你明显感觉 TA 今天状态不太一样，于是问：「你怎么了？」TA 回答：「没什么。」你更可能：",
    options: [
      { id: "1", label: "相信 TA，暂时不再想。", value: 1 },
      { id: "2", label: "注意到了，但给 TA 一点时间。", value: 2 },
      { id: "3", label: "一边观察，一边等等看。", value: 3 },
      { id: "4", label: "还是会觉得事情没有说清楚。", value: 4 },
      { id: "5", label: "很难真正放下，会希望 TA 给一个更明确的解释。", value: 5 },
    ],
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { coreDistinction: "模糊回答是否足以恢复安全感" },
  },
  {
    id: "RN-07",
    phase: "core",
    dimension: "response_need",
    kind: "likert",
    text: "如果我已经连续几次感觉自己被放在比较靠后的位置，我会开始重新判断这段关系对对方到底有多重要。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { coreDistinction: "重复低回应是否会改变关系判断" },
  },
  {
    id: "RN-08",
    phase: "core",
    dimension: "response_need",
    kind: "likert",
    text: "当我因为一段关系感到不确定时，如果对方能够明确解释发生了什么，我通常会很快平静很多。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["reassurance_then_calm"],
    metadata: {
      coreDistinction: "用户真正需要的是更多联系，还是更少不确定",
      notes: "这是一道非常有价值的母题，同时产生 reassurance_then_calm 信号",
    },
  },
  {
    id: "RN-09",
    phase: "core",
    dimension: "response_need",
    kind: "likert",
    text: "只要我相信彼此关系是稳定的，即使一段时间联系比较少，我通常也可以接受。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
    metadata: { coreDistinction: "稳定感能否替代频繁联系" },
  },
  {
    id: "RN-10",
    phase: "core",
    dimension: "response_need",
    kind: "forced_choice",
    text: "如果只能选择一种关系状态，你更容易接受哪一种？",
    options: [
      { id: "1", label: "联系很多，但对方很少明确表达这段关系对 TA 意味着什么。", value: 1 },
      { id: "2", label: "比较接近左边", value: 2 },
      { id: "3", label: "两边差不多", value: 3 },
      { id: "4", label: "比较接近右边", value: 4 },
      { id: "5", label: "联系没有那么频繁，但对方会明确告诉你这段关系很重要。", value: 5 },
    ],
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["clarity_over_frequency"],
    metadata: {
      coreDistinction: "用户更重视联系频率，还是关系确定性",
      notes: "这道题不要直接并入普通总分，可以同时产生 clarity_over_frequency 信号",
    },
  },

  // ========== B | 主动表达与沟通 (expression) ==========
  {
    id: "EX-01",
    phase: "core",
    dimension: "expression",
    kind: "likert",
    text: "如果一件事情真的让我不舒服，我通常希望找机会把原因说出来。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { coreDistinction: "主动沟通倾向" },
  },
  {
    id: "EX-02",
    phase: "core",
    dimension: "expression",
    kind: "likert",
    text: "在重要关系里，我不喜欢让对方一直靠猜来理解我的感受。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "EX-03",
    phase: "core",
    dimension: "expression",
    kind: "likert",
    text: "即使我心里已经非常在意一件事情，我也可能表现得像什么都没有发生。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
    exclusionGroup: "alone_when_stressed_01",
    metadata: { coreDistinction: "内心感受和外在表达之间的距离" },
  },
  {
    id: "EX-04",
    phase: "core",
    dimension: "expression",
    kind: "likert",
    text: "我能够比较直接地告诉重要的人：「我现在需要你的回应。」",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    exclusionGroup: "direct_expression_01",
    metadata: { notes: "这不是测回应需求高低。它测：能不能表达自己的需求。" },
  },
  {
    id: "EX-05",
    phase: "core",
    dimension: "expression",
    kind: "likert",
    text: "当我真的喜欢一个人时，我通常能够通过语言或行动让 TA 感受到。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { coreDistinction: "感情表达能力" },
  },
  {
    id: "EX-06",
    phase: "core",
    dimension: "expression",
    kind: "scenario",
    text: "TA 做了一件让你不舒服的事，但你知道 TA 可能不是故意的。你更可能：",
    options: [
      { id: "1", label: "什么都不说。", value: 1 },
      { id: "2", label: "暂时忍住，看看以后还会不会发生。", value: 2 },
      { id: "3", label: "不确定要不要提。", value: 3 },
      { id: "4", label: "找一个合适的时候告诉 TA。", value: 4 },
      { id: "5", label: "比较快说明发生了什么以及自己的感受。", value: 5 },
    ],
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "EX-07",
    phase: "core",
    dimension: "expression",
    kind: "forced_choice",
    text: "当你希望一个重要的人理解你的感受时，你更接近：",
    options: [
      { id: "1", label: "希望 TA 自己看出来。", value: 1 },
      { id: "2", label: "比较偏左", value: 2 },
      { id: "3", label: "两边差不多", value: 3 },
      { id: "4", label: "比较偏右", value: 4 },
      { id: "5", label: "我会想办法把自己的感受说清楚。", value: 5 },
    ],
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { coreDistinction: "暗示型沟通 vs 明确型沟通" },
  },
  {
    id: "EX-08",
    phase: "core",
    dimension: "expression",
    kind: "likert",
    text: "如果我现在不想继续谈一个问题，我通常能够直接告诉对方：「我需要一点时间，之后我们再说。」",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { notes: "需要空间和突然消失不是同一个东西。" },
  },
  {
    id: "EX-09",
    phase: "core",
    dimension: "expression",
    kind: "likert",
    text: "有时候我担心说出自己的需求会给别人增加压力，所以宁愿不说。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
    signalTags: ["fear_of_burdening"],
    metadata: { reportValue: "你并非没有需求，而是可能会先判断说出来会不会给别人造成负担。" },
  },
  {
    id: "EX-10",
    phase: "core",
    dimension: "expression",
    kind: "likert",
    text: "当我自己也没有完全想明白的时候，我仍然可以告诉重要的人：「我现在有点乱，但这不是你的错。」",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { coreDistinction: "能否在不确定状态下仍保持基本沟通" },
  },

  // ========== C | 自主与空间需求 (space_need) ==========
  {
    id: "SP-01",
    phase: "core",
    dimension: "space_need",
    kind: "likert",
    text: "即使关系非常亲密，我仍然需要一些完全属于自己的时间。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "SP-02",
    phase: "core",
    dimension: "space_need",
    kind: "likert",
    text: "当我的情绪比较乱时，我通常更喜欢先自己整理一下，再和别人讨论。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    exclusionGroup: "alone_when_stressed_01",
  },
  {
    id: "SP-03",
    phase: "core",
    dimension: "space_need",
    kind: "likert",
    text: "只要我真的很喜欢一个人，我会希望我们尽可能一直保持联系。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
  },
  {
    id: "SP-04",
    phase: "core",
    dimension: "space_need",
    kind: "likert",
    text: "我觉得关系很好，并不代表所有休息时间都需要一起度过。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "SP-05",
    phase: "core",
    dimension: "space_need",
    kind: "scenario",
    text: "你正在忙自己的事情，TA 连续发来很多消息，希望你马上回应。你的感觉更接近：",
    options: [
      { id: "1", label: "我会觉得很开心。", value: 1 },
      { id: "2", label: "基本不会影响我。", value: 2 },
      { id: "3", label: "看当时情况。", value: 3 },
      { id: "4", label: "会有一点被打断的感觉。", value: 4 },
      { id: "5", label: "即使很喜欢 TA，我也会明显需要一点自己的空间。", value: 5 },
    ],
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "SP-06",
    phase: "core",
    dimension: "space_need",
    kind: "likert",
    text: "如果对方明确告诉我：「你可以自己待着，等你想聊的时候再找我，我们之间没有问题。」我通常会觉得很舒服。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["autonomy_with_reassurance"],
    metadata: { notes: "这是未来非常关键的一类用户：我需要空间，但我不希望空间意味着关系不安全。" },
  },
  {
    id: "SP-07",
    phase: "core",
    dimension: "space_need",
    kind: "likert",
    text: "如果连续很多天都和另一个人保持非常高频的联系，即使我很喜欢 TA，我也可能开始觉得有一点累。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "SP-08",
    phase: "core",
    dimension: "space_need",
    kind: "likert",
    text: "当一段关系越来越重要时，我通常会自然地希望双方花更多时间待在一起，而不是各做各的。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
  },
  {
    id: "SP-09",
    phase: "core",
    dimension: "space_need",
    kind: "likert",
    text: "对我来说，「我们联系得少一点」和「我们的关系变差了」是两件不同的事情。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { coreDistinction: "能否把联系频率和关系质量分开" },
  },
  {
    id: "SP-10",
    phase: "core",
    dimension: "space_need",
    kind: "forced_choice",
    text: "在一段稳定关系里，如果只能选择更接近的一种状态：",
    options: [
      { id: "1", label: "大部分事情最好一起做，联系越多越安心。", value: 1 },
      { id: "2", label: "比较偏左", value: 2 },
      { id: "3", label: "两边差不多", value: 3 },
      { id: "4", label: "比较偏右", value: 4 },
      { id: "5", label: "即使关系很好，也应该保留不少自己的生活。", value: 5 },
    ],
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },

  // ========== D | 情绪感知与关系敏感度 (emotional_sensitivity) ==========
  {
    id: "ES-01",
    phase: "core",
    dimension: "emotional_sensitivity",
    kind: "likert",
    text: "我通常很容易注意到别人语气、回复方式或者态度上的细微变化。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    exclusionGroup: "change_detection_01",
  },
  {
    id: "ES-02",
    phase: "core",
    dimension: "emotional_sensitivity",
    kind: "likert",
    text: "有时候别人一句看起来很普通的话，我也会注意到里面可能存在的情绪变化。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { notes: "这里不是「我会认定对方讨厌我」。只是「注意到」。" },
  },
  {
    id: "ES-03",
    phase: "core",
    dimension: "emotional_sensitivity",
    kind: "likert",
    text: "除非对方表现得非常明显，否则我通常不太会注意到一个人的情绪发生了变化。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
  },
  {
    id: "ES-04",
    phase: "core",
    dimension: "emotional_sensitivity",
    kind: "likert",
    text: "当一个熟悉的人说「我没事」时，我有时能够感觉出来 TA 其实并不是真的没事。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "ES-05",
    phase: "core",
    dimension: "emotional_sensitivity",
    kind: "likert",
    text: "身边重要的人情绪明显不好时，即使那件事与我无关，我自己的状态也可能受到一些影响。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["emotional_contagion"],
  },
  {
    id: "ES-06",
    phase: "core",
    dimension: "emotional_sensitivity",
    kind: "scenario",
    text: "TA 平时聊天会用很多表情和语气词，但今天明显变得简短。你最接近：",
    options: [
      { id: "1", label: "几乎不会注意到。", value: 1 },
      { id: "2", label: "注意到也不会特别想。", value: 2 },
      { id: "3", label: "会觉得有一点不同。", value: 3 },
      { id: "4", label: "会明显意识到 TA 的状态可能发生变化。", value: 4 },
      { id: "5", label: "我会很快捕捉到这种差异，并想知道原因。", value: 5 },
    ],
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "ES-07",
    phase: "core",
    dimension: "emotional_sensitivity",
    kind: "likert",
    text: "一次不愉快的交流结束以后，我有时会重新回想对方当时说话的细节。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { notes: "高分以后需要和 RN 维度结合。因为回想细节不等于害怕失去关系。" },
  },
  {
    id: "ES-08",
    phase: "core",
    dimension: "emotional_sensitivity",
    kind: "likert",
    text: "即使别人没有直接说出来，我也常常能够感觉到 TA 是希望靠近，还是想暂时保持一点距离。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "ES-09",
    phase: "core",
    dimension: "emotional_sensitivity",
    kind: "likert",
    text: "别人态度上的小变化一般很难进入我的注意范围。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
  },
  {
    id: "ES-10",
    phase: "core",
    dimension: "emotional_sensitivity",
    kind: "likert",
    text: "我可以注意到一个人的状态变化，但并不会自动认为那一定和我有关。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["perceptive_without_personalizing"],
    metadata: {
      coreDistinction: "它能帮助我们区分敏锐和容易把变化归因到自己",
      reportValue: "你很敏感，但并不意味着你总是悲观。你只是比很多人更早捕捉变化。",
    },
  },

  // ========== E | 冲突处理节奏 (conflict_urgency) ==========
  {
    id: "CU-01",
    phase: "core",
    dimension: "conflict_urgency",
    kind: "likert",
    text: "发生明显矛盾以后，我通常希望比较快把问题说清楚。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "CU-02",
    phase: "core",
    dimension: "conflict_urgency",
    kind: "likert",
    text: "一个重要问题如果一直悬着没有解决，我会觉得很难真正放松。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    exclusionGroup: "unresolved_conflict_01",
  },
  {
    id: "CU-03",
    phase: "core",
    dimension: "conflict_urgency",
    kind: "likert",
    text: "发生争执以后，我通常更愿意双方先各自冷静一段时间，再继续讨论。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
    exclusionGroup: "alone_when_stressed_01",
  },
  {
    id: "CU-04",
    phase: "core",
    dimension: "conflict_urgency",
    kind: "scenario",
    text: "你们正在争执，TA 说：「我们两个现在情绪都不好，今晚先停一下，明天上午再谈。」你更接近：",
    options: [
      { id: "1", label: "这正是我希望的。", value: 1 },
      { id: "2", label: "我基本可以接受。", value: 2 },
      { id: "3", label: "要看问题严重程度。", value: 3 },
      { id: "4", label: "我会觉得问题还悬着，很不舒服。", value: 4 },
      { id: "5", label: "我很难接受，我希望现在至少把核心问题讲清楚。", value: 5 },
    ],
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: {
      notes: "TA 给出了明确重新沟通时间。可以区分真正的即时解决需求，和因为害怕无限期冷处理而产生的不安。",
    },
  },
  {
    id: "CU-05",
    phase: "core",
    dimension: "conflict_urgency",
    kind: "likert",
    text: "当我感觉一段重要关系出了问题时，我通常会比平时更主动地尝试联系对方。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["approach_under_stress"],
  },
  {
    id: "CU-06",
    phase: "core",
    dimension: "conflict_urgency",
    kind: "likert",
    text: "即使我知道继续谈下去可能会让情绪更激动，我有时仍然会觉得「不说清楚更难受」。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "CU-07",
    phase: "core",
    dimension: "conflict_urgency",
    kind: "forced_choice",
    text: "发生矛盾以后，哪一种情况对你更难受？",
    options: [
      { id: "1", label: "双方还没有谈清楚，但先暂停几个小时。", value: 1 },
      { id: "2", label: "比较偏左", value: 2 },
      { id: "3", label: "两边差不多", value: 3 },
      { id: "4", label: "比较偏右", value: 4 },
      { id: "5", label: "双方情绪都很激动，却继续讨论。", value: 5 },
    ],
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    metadata: { notes: "左侧越难接受分数越高。系统实现时注意该题需要反向映射答案文字。" },
  },
  {
    id: "CU-08",
    phase: "core",
    dimension: "conflict_urgency",
    kind: "likert",
    text: "如果一个问题不是必须当天解决，我通常可以睡一觉或者隔一天以后再讨论。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
  },
  {
    id: "CU-09",
    phase: "core",
    dimension: "conflict_urgency",
    kind: "likert",
    text: "矛盾以后，如果对方突然长时间不回应，我通常会比争吵本身更加不舒服。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["silence_after_conflict_trigger"],
  },
  {
    id: "CU-10",
    phase: "core",
    dimension: "conflict_urgency",
    kind: "likert",
    text: "如果对方能够清楚告诉我「我需要一点时间，但我一定会回来继续谈」，我通常比较能够接受暂停沟通。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
    signalTags: ["pause_with_reconnection"],
    metadata: { notes: "用户可能不是必须马上解决，而是不能接受不知道什么时候再谈。" },
  },

  // ========== F | 关系修复与韧性 (repair_orientation) ==========
  {
    id: "RP-01",
    phase: "core",
    dimension: "repair_orientation",
    kind: "likert",
    text: "即使刚刚发生过争执，只要对方开始释放善意，我通常愿意回应。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "RP-02",
    phase: "core",
    dimension: "repair_orientation",
    kind: "likert",
    text: "相比一定要证明谁对谁错，我更在意最后双方能不能真正理解发生了什么。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "RP-03",
    phase: "core",
    dimension: "repair_orientation",
    kind: "likert",
    text: "一旦一个重要的人让我明显失望，我通常很难恢复到之前的相处状态。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
    metadata: { coreDistinction: "能否把单次事件和整段关系分开" },
  },
  {
    id: "RP-04",
    phase: "core",
    dimension: "repair_orientation",
    kind: "likert",
    text: "即使一次沟通没有解决问题，只要双方还有诚意，我愿意以后重新谈一次。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "RP-05",
    phase: "core",
    dimension: "repair_orientation",
    kind: "scenario",
    text: "TA 因为一件事情伤害了你，后来认真说明了自己哪里做错，并且明确道歉。你的状态更接近：",
    options: [
      { id: "1", label: "即使这样，我也很难重新靠近。", value: 1 },
      { id: "2", label: "我会听，但仍然需要很长时间。", value: 2 },
      { id: "3", label: "要看事情是什么。", value: 3 },
      { id: "4", label: "我通常愿意重新观察这段关系。", value: 4 },
      { id: "5", label: "如果道歉真诚而且之后有改变，我愿意逐渐恢复连接。", value: 5 },
    ],
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "RP-06",
    phase: "core",
    dimension: "repair_orientation",
    kind: "likert",
    text: "对我来说，真正的修复不仅需要一句「对不起」，还需要之后的行为发生一些变化。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["behavior_change_required"],
    weight: 0, // 不进入主维度分数
    metadata: { notes: "作为报告信号。高修复倾向不代表别人说对不起就什么都算了。" },
  },
  {
    id: "RP-07",
    phase: "core",
    dimension: "repair_orientation",
    kind: "likert",
    text: "一次严重的不愉快，会让我很容易开始否定这段关系过去所有好的部分。",
    scoreDirection: "reverse",
    version: "1.0",
    active: true,
    metadata: { coreDistinction: "能否把单次事件和整段关系分开" },
  },
  {
    id: "RP-08",
    phase: "core",
    dimension: "repair_orientation",
    kind: "likert",
    text: "如果我知道双方其实都还在意这段关系，我通常愿意主动做一点事情打破僵局。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
  },
  {
    id: "RP-09",
    phase: "core",
    dimension: "repair_orientation",
    kind: "likert",
    text: "如果同一个问题已经发生过很多次，即使每次都有道歉，我也会逐渐降低对修复的信心。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["repeated_pattern_erosion"],
    weight: 0, // 不直接进入主分数
    metadata: { notes: "愿意修复不等于无限次接受同一个问题。" },
  },
  {
    id: "RP-10",
    phase: "core",
    dimension: "repair_orientation",
    kind: "likert",
    text: "一次矛盾结束以后，如果双方能够约定下一次具体怎么做，我会比只有情绪上的和好更安心。",
    scoreDirection: "positive",
    version: "1.0",
    active: true,
    signalTags: ["concrete_repair_preference"],
    metadata: { reportValue: "对你来说，真正有效的和好不是算了，而是知道下次遇到类似情况，两个人准备怎么处理。" },
  },
];
