import { Question } from "../types";

// ============================================================
// 默契研究所 V2.0 — 40 道统一动态追问题
// 8 组 × 5 题
// 版本: V2.0-FU-CORE-001
// ============================================================

export const FOLLOWUP_QUESTIONS: Question[] = [
  // ========== 第一组 | 高回应需求相关 (FU-RN-01 ~ 05) ==========
  {
    id: "FU-RN-01",
    phase: "followup",
    dimension: "response_need",
    kind: "forced_choice",
    text: "假设只能选择一种状态，你更愿意哪一种？",
    options: [
      { id: "1", label: "一整天都在聊天，但你始终不确定 TA 到底怎么看这段关系。", value: 1 },
      { id: "2", label: "比较偏左", value: 2 },
      { id: "3", label: "都差不多", value: 3 },
      { id: "4", label: "比较偏右", value: 4 },
      { id: "5", label: "一天只认真联系几次，但你非常确定 TA 在认真对待你。", value: 5 },
    ],
    trigger: { minScores: { response_need: 70 } },
    resolves: ["clarity_over_frequency", "contact_frequency_need"],
    reportImpact: 95,
    effectType: "classifier",
    exclusionGroup: "rn_clarity_vs_frequency",
    version: "1.0",
    active: true,
    metadata: { notes: "区分需要高频联系 vs 需要关系确定" },
  },
  {
    id: "FU-RN-02",
    phase: "followup",
    dimension: "response_need",
    kind: "scenario",
    text: "如果 TA 的联系突然减少，但能够主动、具体地解释原因，而且之后的行为也和解释一致，你的不安通常会减少多少？",
    options: [
      { id: "1", label: "几乎不会。", value: 1 },
      { id: "2", label: "会减少一点。", value: 2 },
      { id: "3", label: "一半左右。", value: 3 },
      { id: "4", label: "会减少很多。", value: 4 },
      { id: "5", label: "基本会消失。", value: 5 },
    ],
    trigger: { minScores: { response_need: 70 } },
    resolves: ["reassurance_then_calm", "persistent_contact_need"],
    reportImpact: 90,
    effectType: "signal",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-RN-03",
    phase: "followup",
    dimension: "response_need",
    kind: "classifier",
    text: "当 TA 突然变冷淡时，你最难受的更接近：",
    options: [
      { id: "1", label: "不知道发生了什么。", value: 1 },
      { id: "2", label: "担心 TA 不再喜欢我。", value: 2 },
      { id: "3", label: "感觉自己没有被重视。", value: 3 },
      { id: "4", label: "不喜欢自己失去掌控感。", value: 4 },
      { id: "5", label: "我只是单纯希望联系恢复。", value: 5 },
    ],
    weight: 0,
    trigger: { minScores: { response_need: 75 }, anySignals: ["emotional_contagion"] },
    resolves: ["response_need_source"],
    reportImpact: 80,
    effectType: "classifier",
    version: "1.0",
    active: true,
    metadata: { notes: "不进入六维主分" },
  },
  {
    id: "FU-RN-04",
    phase: "followup",
    dimension: "response_need",
    kind: "scenario",
    text: "如果 TA 回复并不快，但会提前为你安排时间、记得重要事情，并主动把你放进自己的计划里，你还会很在意回复速度吗？",
    options: [
      { id: "1", label: "仍然非常在意。", value: 1 },
      { id: "2", label: "还是比较在意。", value: 2 },
      { id: "3", label: "会减少一些。", value: 3 },
      { id: "4", label: "会减少很多。", value: 4 },
      { id: "5", label: "基本不会在意。", value: 5 },
    ],
    trigger: { minScores: { response_need: 65 } },
    resolves: ["priority_over_immediacy"],
    reportImpact: 85,
    effectType: "signal",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-RN-05",
    phase: "followup",
    dimension: "response_need",
    kind: "scenario",
    text: "如果这种联系变化只发生一次，你通常能放下吗？",
    options: [
      { id: "1", label: "很难。", value: 1 },
      { id: "2", label: "比较难。", value: 2 },
      { id: "3", label: "看具体情况。", value: 3 },
      { id: "4", label: "大部分可以。", value: 4 },
      { id: "5", label: "完全可以。", value: 5 },
    ],
    trigger: { minScores: { response_need: 70 } },
    resolves: ["single_event_sensitivity", "repeated_pattern_sensitivity"],
    reportImpact: 70,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },

  // ========== 第二组 | 高空间需求相关 (FU-SP-01 ~ 05) ==========
  {
    id: "FU-SP-01",
    phase: "followup",
    dimension: "space_need",
    kind: "scenario",
    text: "当你需要独处时，如果确定 TA 不会因此误解、追问或生气，你会不会更愿意在休息之后重新主动靠近？",
    options: [
      { id: "1", label: "基本不会。", value: 1 },
      { id: "2", label: "很少。", value: 2 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "通常会。", value: 4 },
      { id: "5", label: "是的，我只是需要恢复，不是想远离关系。", value: 5 },
    ],
    trigger: { minScores: { space_need: 70 } },
    resolves: ["restorative_space", "relational_withdrawal_possible"],
    reportImpact: 90,
    effectType: "signal",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-SP-02",
    phase: "followup",
    dimension: "space_need",
    kind: "classifier",
    text: "哪一种最接近你的理想状态？",
    options: [
      { id: "1", label: "我需要空间，而且不希望对方问任何事情。", value: 1 },
      { id: "2", label: "我需要空间，但希望先确认「我们之间没有问题」。", value: 2 },
      { id: "3", label: "我并不是真的需要空间，只是不知道怎么处理情绪。", value: 3 },
      { id: "4", label: "看具体关系。", value: 4 },
    ],
    weight: 0,
    trigger: { minScores: { space_need: 70, response_need: 65 } },
    resolves: ["space_condition_type"],
    reportImpact: 85,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-SP-03",
    phase: "followup",
    dimension: "space_need",
    kind: "scenario",
    text: "如果你拥有很多自己的朋友、兴趣和时间，但和 TA 的感情连接仍然稳定，你会觉得这是：",
    options: [
      { id: "1", label: "有点疏远。", value: 1 },
      { id: "2", label: "不够亲密。", value: 2 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "很舒服。", value: 4 },
      { id: "5", label: "这正是我理想的长期关系。", value: 5 },
    ],
    trigger: { minScores: { space_need: 65 } },
    resolves: ["autonomy_with_commitment"],
    reportImpact: 80,
    effectType: "signal",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-SP-04",
    phase: "followup",
    dimension: "space_need",
    kind: "scenario",
    text: "连续很多天高频聊天或见面以后，即使相处都很愉快，你是否仍可能产生「我想自己待一下」的需要？",
    options: [
      { id: "1", label: "几乎不会", value: 1 },
      { id: "2", label: "比较少", value: 2 },
      { id: "3", label: "看情况", value: 3 },
      { id: "4", label: "比较会", value: 4 },
      { id: "5", label: "非常会", value: 5 },
    ],
    trigger: { minScores: { space_need: 65 } },
    resolves: ["contact_saturation"],
    reportImpact: 70,
    effectType: "signal",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-SP-05",
    phase: "followup",
    dimension: "space_need",
    kind: "classifier",
    text: "当你在矛盾后需要冷静时，你更希望：",
    options: [
      { id: "1", label: "完全不确定什么时候再谈。", value: 1 },
      { id: "2", label: "大概知道晚一点会回来。", value: 2 },
      { id: "3", label: "最好有一个明确时间，例如「今晚九点继续」。", value: 3 },
    ],
    weight: 0,
    trigger: { minScores: { space_need: 70 }, maxScores: { conflict_urgency: 45 } },
    resolves: ["space_reconnection_structure"],
    reportImpact: 75,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },

  // ========== 第三组 | 高敏感 + 表达问题 (FU-ES-01 ~ 05) ==========
  {
    id: "FU-ES-01",
    phase: "followup",
    dimension: "emotional_sensitivity",
    kind: "classifier",
    text: "当你感觉 TA 状态不对时，你第一反应通常更接近：",
    options: [
      { id: "1", label: "TA 自己可能遇到了事情。", value: 1 },
      { id: "2", label: "我们之间可能出了问题。", value: 2 },
      { id: "3", label: "我是不是哪里做错了。", value: 3 },
      { id: "4", label: "我会先收集更多信息。", value: 4 },
    ],
    weight: 0,
    trigger: { minScores: { emotional_sensitivity: 70 } },
    resolves: ["change_attribution_style"],
    reportImpact: 85,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-ES-02",
    phase: "followup",
    dimension: "emotional_sensitivity",
    kind: "scenario",
    text: "当你已经明显察觉 TA 状态变化，但又不确定自己是不是想多了，你更可能：",
    options: [
      { id: "1", label: "直接问。", value: 1 },
      { id: "2", label: "轻轻试探。", value: 2 },
      { id: "3", label: "继续观察。", value: 3 },
      { id: "4", label: "心里想很多，但不说。", value: 4 },
      { id: "5", label: "越在意越难开口。", value: 5 },
    ],
    trigger: { minScores: { emotional_sensitivity: 70 }, maxScores: { expression: 45 } },
    resolves: ["silent_monitor"],
    reportImpact: 95,
    effectType: "signal",
    exclusionGroup: "high_sensitivity_low_expression",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-ES-03",
    phase: "followup",
    dimension: "emotional_sensitivity",
    kind: "scenario",
    text: "如果这种「不对劲」的感觉持续两三天，你通常会：",
    options: [
      { id: "1", label: "还是不问。", value: 1 },
      { id: "2", label: "等对方自己说。", value: 2 },
      { id: "3", label: "继续观察。", value: 3 },
      { id: "4", label: "开始主动询问。", value: 4 },
      { id: "5", label: "我会明确提出自己注意到了变化。", value: 5 },
    ],
    trigger: { requiredSignals: ["silent_monitor"] },
    resolves: ["monitoring_to_expression_threshold"],
    reportImpact: 80,
    effectType: "signal",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-ES-04",
    phase: "followup",
    dimension: "emotional_sensitivity",
    kind: "classifier",
    text: "当 TA 情绪很差时，你更容易难受，是因为：",
    options: [
      { id: "1", label: "我天然会被别人的情绪影响。", value: 1 },
      { id: "2", label: "我会觉得自己应该帮助 TA 变好。", value: 2 },
      { id: "3", label: "我担心 TA 情绪和我有关。", value: 3 },
      { id: "4", label: "三种都有一些。", value: 4 },
    ],
    weight: 0,
    trigger: { anySignals: ["emotional_contagion"] },
    resolves: ["emotional_load_source"],
    reportImpact: 75,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-ES-05",
    phase: "followup",
    dimension: "emotional_sensitivity",
    kind: "scenario",
    text: "你是否经常出现这种状态：「我确定 TA 不太对，但我不知道为什么，所以我先不下结论。」",
    options: [
      { id: "1", label: "几乎不会", value: 1 },
      { id: "2", label: "比较少", value: 2 },
      { id: "3", label: "偶尔", value: 3 },
      { id: "4", label: "比较经常", value: 4 },
      { id: "5", label: "非常经常", value: 5 },
    ],
    trigger: { minScores: { emotional_sensitivity: 70 } },
    resolves: ["perceptive_without_premature_interpretation"],
    reportImpact: 85,
    effectType: "signal",
    version: "1.0",
    active: true,
  },

  // ========== 第四组 | 表达方式相关 (FU-EX-01 ~ 05) ==========
  {
    id: "FU-EX-01",
    phase: "followup",
    dimension: "expression",
    kind: "classifier",
    text: "当你明明有需求却不说时，最常见原因是：",
    options: [
      { id: "1", label: "怕冲突。", value: 1 },
      { id: "2", label: "怕给 TA 压力。", value: 2 },
      { id: "3", label: "觉得说了也没用。", value: 3 },
      { id: "4", label: "自己也说不清。", value: 4 },
      { id: "5", label: "希望 TA 自己发现。", value: 5 },
    ],
    weight: 0,
    trigger: { maxScores: { expression: 45 } },
    resolves: ["expression_block_source"],
    reportImpact: 90,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-EX-02",
    phase: "followup",
    dimension: "expression",
    kind: "classifier",
    text: "当你表达不满时，你更接近：",
    options: [
      { id: "1", label: "「你最近根本不在乎我。」", value: 1 },
      { id: "2", label: "「我最近有点失落。」", value: 2 },
      { id: "3", label: "「我希望这周我们能留一个晚上认真相处。」", value: 3 },
    ],
    weight: 0,
    trigger: { minScores: { expression: 55 } },
    resolves: ["expression_specificity"],
    reportImpact: 80,
    effectType: "classifier",
    version: "1.0",
    active: true,
    metadata: { notes: "C 最高质量" },
  },
  {
    id: "FU-EX-03",
    phase: "followup",
    dimension: "expression",
    kind: "scenario",
    text: "当你已经清楚表达自己的需求，但 TA 最终仍然不同意，你通常能接受「表达清楚不等于对方必须答应」吗？",
    options: [
      { id: "1", label: "很难接受", value: 1 },
      { id: "2", label: "比较难", value: 2 },
      { id: "3", label: "看情况", value: 3 },
      { id: "4", label: "基本可以", value: 4 },
      { id: "5", label: "完全可以", value: 5 },
    ],
    trigger: { minScores: { expression: 70 } },
    resolves: ["expression_without_control"],
    reportImpact: 75,
    effectType: "signal",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-EX-04",
    phase: "followup",
    dimension: "expression",
    kind: "classifier",
    text: "当你告诉 TA 自己不开心时，你真正最希望 TA：",
    options: [
      { id: "1", label: "先理解我的感受。", value: 1 },
      { id: "2", label: "马上给解决方案。", value: 2 },
      { id: "3", label: "道歉。", value: 3 },
      { id: "4", label: "改变具体行为。", value: 4 },
      { id: "5", label: "陪我一会儿。", value: 5 },
    ],
    weight: 0,
    trigger: { minScores: { expression: 60 } },
    resolves: ["communication_goal"],
    reportImpact: 70,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-EX-05",
    phase: "followup",
    dimension: "expression",
    kind: "scenario",
    text: "如果 TA 连续几次没有理解你的暗示，你更可能：",
    options: [
      { id: "1", label: "觉得 TA 根本不懂我。", value: 1 },
      { id: "2", label: "更明显地暗示。", value: 2 },
      { id: "3", label: "有点失望。", value: 3 },
      { id: "4", label: "换成直接表达。", value: 4 },
      { id: "5", label: "我会意识到暗示本身可能不够清楚。", value: 5 },
    ],
    trigger: { anySignals: ["mind_reading_expectation"] },
    resolves: ["shift_from_hint_to_direct"],
    reportImpact: 70,
    effectType: "signal",
    version: "1.0",
    active: true,
  },

  // ========== 第五组 | 冲突节奏 (FU-CU-01 ~ 05) ==========
  {
    id: "FU-CU-01",
    phase: "followup",
    dimension: "conflict_urgency",
    kind: "scenario",
    text: "如果 TA 明确告诉你：「我不是逃避，我们两个小时后继续。」你的即时解决需求会下降多少？",
    options: [
      { id: "1", label: "几乎不下降。", value: 1 },
      { id: "2", label: "下降一点。", value: 2 },
      { id: "3", label: "一半左右。", value: 3 },
      { id: "4", label: "下降很多。", value: 4 },
      { id: "5", label: "基本就能接受暂停。", value: 5 },
    ],
    trigger: { minScores: { conflict_urgency: 70 } },
    resolves: ["uncertain_reconnection_trigger", "true_immediate_resolution_need"],
    reportImpact: 95,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-CU-02",
    phase: "followup",
    dimension: "conflict_urgency",
    kind: "classifier",
    text: "如果问题没有解决，你最多比较舒服地接受暂停多久？",
    options: [
      { id: "1", label: "30 分钟以内。", value: 1 },
      { id: "2", label: "几个小时。", value: 2 },
      { id: "3", label: "一晚上。", value: 3 },
      { id: "4", label: "1-2 天。", value: 4 },
      { id: "5", label: "没有固定时间，只要对方会回来。", value: 5 },
    ],
    weight: 0,
    trigger: { minScores: { conflict_urgency: 55 } },
    resolves: ["acceptable_conflict_pause_window"],
    reportImpact: 75,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-CU-03",
    phase: "followup",
    dimension: "conflict_urgency",
    kind: "classifier",
    text: "当对方需要暂停时，对你最重要的是：",
    options: [
      { id: "1", label: "告诉我为什么暂停。", value: 1 },
      { id: "2", label: "告诉我什么时候回来。", value: 2 },
      { id: "3", label: "先确认关系没有问题。", value: 3 },
      { id: "4", label: "什么都不用说，让彼此安静。", value: 4 },
    ],
    weight: 0,
    trigger: { minScores: { conflict_urgency: 55 } },
    resolves: ["pause_safety_requirement"],
    reportImpact: 75,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-CU-04",
    phase: "followup",
    dimension: "conflict_urgency",
    kind: "classifier",
    text: "当你坚持继续讨论时，你最想得到的是：",
    options: [
      { id: "1", label: "对方理解我。", value: 1 },
      { id: "2", label: "问题有解决方案。", value: 2 },
      { id: "3", label: "对方承认自己错了。", value: 3 },
      { id: "4", label: "让我知道关系没有出问题。", value: 4 },
    ],
    weight: 0,
    trigger: { minScores: { conflict_urgency: 70 }, maxScores: { repair_orientation: 50 } },
    resolves: ["conflict_persistence_goal"],
    reportImpact: 70,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-CU-05",
    phase: "followup",
    dimension: "conflict_urgency",
    kind: "scenario",
    text: "当你冷静下来以后，你通常会主动回来继续解决问题吗？",
    options: [
      { id: "1", label: "很少。", value: 1 },
      { id: "2", label: "偶尔。", value: 2 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "大多数时候会。", value: 4 },
      { id: "5", label: "会，我需要暂停但不会把暂停变成消失。", value: 5 },
    ],
    trigger: { maxScores: { conflict_urgency: 40 } },
    resolves: ["healthy_pause_return", "avoidant_pause_risk"],
    reportImpact: 85,
    effectType: "signal",
    version: "1.0",
    active: true,
  },

  // ========== 第六组 | 修复与边界 (FU-RP-01 ~ 05) ==========
  {
    id: "FU-RP-01",
    phase: "followup",
    dimension: "repair_orientation",
    kind: "classifier",
    text: "你愿意一次次修复关系，更多是因为：",
    options: [
      { id: "1", label: "我相信关系可以成长。", value: 1 },
      { id: "2", label: "我很难放弃重要的人。", value: 2 },
      { id: "3", label: "我害怕失去。", value: 3 },
      { id: "4", label: "我觉得自己有责任维持关系。", value: 4 },
      { id: "5", label: "要看具体关系。", value: 5 },
    ],
    weight: 0,
    trigger: { minScores: { repair_orientation: 70 } },
    resolves: ["repair_motivation"],
    reportImpact: 75,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-RP-02",
    phase: "followup",
    dimension: "repair_orientation",
    kind: "forced_choice",
    text: "如果只能选一个，你更容易重新建立信任的是：\n\nA. 对方非常真诚地道歉。\nB. 对方之后持续改变行为。",
    options: [
      { id: "1", label: "强烈 A", value: 1 },
      { id: "2", label: "比较 A", value: 2 },
      { id: "3", label: "都差不多", value: 3 },
      { id: "4", label: "比较 B", value: 4 },
      { id: "5", label: "强烈 B", value: 5 },
    ],
    trigger: { minScores: { repair_orientation: 60 } },
    resolves: ["behavior_change_required"],
    reportImpact: 90,
    effectType: "signal",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-RP-03",
    phase: "followup",
    dimension: "repair_orientation",
    kind: "scenario",
    text: "如果同一个问题已经发生很多次，你是否仍然认为「愿意修复」就意味着应该继续给机会？",
    options: [
      { id: "1", label: "基本是。", value: 1 },
      { id: "2", label: "大部分时候是。", value: 2 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "不一定。", value: 4 },
      { id: "5", label: "不是，修复也需要边界和实际变化。", value: 5 },
    ],
    trigger: { minScores: { repair_orientation: 70 }, anySignals: ["repeated_pattern_erosion"] },
    resolves: ["repair_with_boundaries"],
    reportImpact: 90,
    effectType: "signal",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-RP-04",
    phase: "followup",
    dimension: "repair_orientation",
    kind: "classifier",
    text: "如果总是你先主动，但对方每次都会认真参与后续解决，你最累的是：",
    options: [
      { id: "1", label: "总是我要先开口。", value: 1 },
      { id: "2", label: "后续其实也还是我在推动。", value: 2 },
      { id: "3", label: "我更在意对方有没有意识到问题。", value: 3 },
      { id: "4", label: "只要最后能解决，我不太在意谁先。", value: 4 },
    ],
    weight: 0,
    trigger: { anySignals: ["repair_labor_imbalance"] },
    resolves: ["repair_imbalance_source"],
    reportImpact: 70,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-RP-05",
    phase: "followup",
    dimension: "repair_orientation",
    kind: "scenario",
    text: "如果问题已经得到解决、对方也持续改变，你是否仍会在新的争吵里反复翻出旧问题？",
    options: [
      { id: "1", label: "经常。", value: 1 },
      { id: "2", label: "有时。", value: 2 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "很少。", value: 4 },
      { id: "5", label: "如果真的解决，我通常能够把它留在过去。", value: 5 },
    ],
    trigger: { minScores: { repair_orientation: 60 } },
    resolves: ["resolved_issue_release"],
    reportImpact: 70,
    effectType: "signal",
    version: "1.0",
    active: true,
  },

  // ========== 第七组 | 关系状态与撤离 (FU-TEN-01 ~ 05) ==========
  {
    id: "FU-TEN-01",
    phase: "followup",
    dimension: "repair_orientation",
    kind: "classifier",
    text: "你现在减少联系和分享，更接近：",
    options: [
      { id: "1", label: "我还很在乎，只是想保护自己。", value: 1 },
      { id: "2", label: "我在等对方先靠近。", value: 2 },
      { id: "3", label: "我真的越来越不需要 TA 参与我的生活。", value: 3 },
      { id: "4", label: "我自己也分不清。", value: 4 },
    ],
    weight: 0,
    trigger: { anySignals: ["sharing_withdrawal", "relief_in_disconnection"], relationshipStages: ["tense", "drifting"] },
    resolves: ["protective_withdrawal_vs_detachment"],
    reportImpact: 95,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-TEN-02",
    phase: "followup",
    dimension: "repair_orientation",
    kind: "scenario",
    text: "假设现在最困扰你们的三个问题全部明显改善，你还会想和 TA 继续走下去吗？",
    options: [
      { id: "1", label: "很确定不会。", value: 1 },
      { id: "2", label: "大概率不会。", value: 2 },
      { id: "3", label: "不确定。", value: 3 },
      { id: "4", label: "大概率会。", value: 4 },
      { id: "5", label: "很确定会。", value: 5 },
    ],
    trigger: { anySignals: ["relationship_exhaustion"], relationshipStages: ["tense", "drifting"] },
    resolves: ["desire_after_problem_resolution"],
    reportImpact: 95,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-TEN-03",
    phase: "followup",
    dimension: "emotional_sensitivity",
    kind: "classifier",
    text: "当你舍不得这段关系时，你更舍不得的是：",
    options: [
      { id: "1", label: "现在这个 TA。", value: 1 },
      { id: "2", label: "过去的 TA。", value: 2 },
      { id: "3", label: "过去的我们。", value: 3 },
      { id: "4", label: "自己投入的时间。", value: 4 },
      { id: "5", label: "对未来曾经有过的期待。", value: 5 },
    ],
    weight: 0,
    trigger: { relationshipStages: ["tense", "drifting"] },
    resolves: ["attachment_target"],
    reportImpact: 80,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-TEN-04",
    phase: "followup",
    dimension: "repair_orientation",
    kind: "classifier",
    text: "现在最难恢复的是：",
    options: [
      { id: "1", label: "相信 TA 说的话。", value: 1 },
      { id: "2", label: "相信 TA 会改变。", value: 2 },
      { id: "3", label: "相信 TA 真正理解我的感受。", value: 3 },
      { id: "4", label: "相信关系不会再次发生同样的问题。", value: 4 },
      { id: "5", label: "相信自己还能重新放松下来。", value: 5 },
    ],
    weight: 0,
    trigger: { anySignals: ["trust_stability_low"], relationshipStages: ["tense", "drifting"] },
    resolves: ["trust_damage_source"],
    reportImpact: 85,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-TEN-05",
    phase: "followup",
    dimension: "emotional_sensitivity",
    kind: "scenario",
    text: "即使现在很失望，你是否仍然想真正理解：「TA 为什么会有这些反应？」",
    options: [
      { id: "1", label: "完全不想。", value: 1 },
      { id: "2", label: "很少。", value: 2 },
      { id: "3", label: "不确定。", value: 3 },
      { id: "4", label: "仍然想。", value: 4 },
      { id: "5", label: "是的，即使失望，我仍然想理解 TA。", value: 5 },
    ],
    trigger: { relationshipStages: ["tense", "drifting"] },
    resolves: ["curiosity_about_partner_remaining"],
    reportImpact: 75,
    effectType: "signal",
    version: "1.0",
    active: true,
  },

  // ========== 第八组 | 互惠、公平、边界 (FU-BD-01 ~ 05) ==========
  {
    id: "FU-BD-01",
    phase: "followup",
    dimension: "expression",
    kind: "classifier",
    text: "对你来说，一段关系里的「公平」更接近：",
    options: [
      { id: "1", label: "双方做的事情数量差不多。", value: 1 },
      { id: "2", label: "双方付出的时间差不多。", value: 2 },
      { id: "3", label: "根据能力和现实条件弹性分配。", value: 3 },
      { id: "4", label: "不一定平均，但双方都感觉自己的付出被看见。", value: 4 },
    ],
    weight: 0,
    trigger: { anySignals: ["initiative_imbalance", "household_fairness_model", "financial_fairness_model"] },
    resolves: ["fairness_definition"],
    reportImpact: 75,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-BD-02",
    phase: "followup",
    dimension: "space_need",
    kind: "classifier",
    text: "当你坚持自己的边界时，你真正希望对方理解的是：",
    options: [
      { id: "1", label: "我不是不爱你。", value: 1 },
      { id: "2", label: "我需要保留自己的生活。", value: 2 },
      { id: "3", label: "我不喜欢被控制。", value: 3 },
      { id: "4", label: "我需要安全地说「不」。", value: 4 },
      { id: "5", label: "以上都有。", value: 5 },
    ],
    weight: 0,
    trigger: { minScores: { space_need: 65 } },
    resolves: ["boundary_meaning"],
    reportImpact: 70,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-BD-03",
    phase: "followup",
    dimension: "emotional_sensitivity",
    kind: "classifier",
    text: "当你因为 TA 和别人亲近而不舒服时，你真正最在意的更接近：",
    options: [
      { id: "1", label: "怕自己被替代。", value: 1 },
      { id: "2", label: "怕 TA 喜欢别人。", value: 2 },
      { id: "3", label: "觉得某些边界不合适。", value: 3 },
      { id: "4", label: "觉得自己没有被优先考虑。", value: 4 },
      { id: "5", label: "我只是单纯会有情绪，但仍然信任 TA。", value: 5 },
    ],
    weight: 0,
    trigger: { anySignals: ["jealousy_source"] },
    resolves: ["jealousy_source"],
    reportImpact: 75,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-BD-04",
    phase: "followup",
    dimension: "expression",
    kind: "classifier",
    text: "对你来说，真正重要的「仪式感」更接近：",
    options: [
      { id: "1", label: "礼物和惊喜。", value: 1 },
      { id: "2", label: "记得重要日期。", value: 2 },
      { id: "3", label: "主动留时间。", value: 3 },
      { id: "4", label: "提前准备，让我知道 TA 有把这件事放在心上。", value: 4 },
    ],
    weight: 0,
    trigger: { anySignals: ["ritual_need"] },
    resolves: ["ritual_meaning"],
    reportImpact: 65,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
  {
    id: "FU-BD-05",
    phase: "followup",
    dimension: "response_need",
    kind: "classifier",
    text: "如果长期都是你主动，你真正最失望的是：",
    options: [
      { id: "1", label: "很累。", value: 1 },
      { id: "2", label: "感觉自己不被想念。", value: 2 },
      { id: "3", label: "怀疑对方根本不在乎。", value: 3 },
      { id: "4", label: "不喜欢关系靠自己推动。", value: 4 },
      { id: "5", label: "希望对方也能主动证明这段关系重要。", value: 5 },
    ],
    weight: 0,
    trigger: { anySignals: ["initiative_imbalance"] },
    resolves: ["initiative_imbalance_meaning"],
    reportImpact: 75,
    effectType: "classifier",
    version: "1.0",
    active: true,
  },
];
