import { Question } from "../types";

const LIKERT_OPTIONS = [
  { id: "1", label: "非常不像我", value: 1 as const },
  { id: "2", label: "比较不像我", value: 2 as const },
  { id: "3", label: "说不清", value: 3 as const },
  { id: "4", label: "比较像我", value: 4 as const },
  { id: "5", label: "非常像我", value: 5 as const },
];

type ScenarioVariant = Pick<Question, "id" | "motherQuestionId" | "dimension" | "text"> &
  Partial<Pick<Question, "scoreDirection" | "signalTags" | "exclusionGroup" | "relationshipTypes" | "relationshipStages" | "ageBands" | "lifeStages" | "metadata">>;

const asLikert = (variants: ScenarioVariant[], phase: Question["phase"] = "relationship"): Question[] =>
  variants.map((variant) => ({
    ...variant,
    phase,
    kind: "likert",
    options: LIKERT_OPTIONS,
    scoreDirection: variant.scoreDirection ?? "positive",
    version: "2.0",
    active: true,
  }));

// ============================================================
// 默契研究所 V2.0 — 关系类型场景题库
// 7 种关系类型，每种选取代表性题目
// ============================================================

// ========== 暧昧关系 (ambiguous) ==========
export const AMBIGUOUS_QUESTIONS: Question[] = [
  {
    id: "AMB-RN-01", motherQuestionId: "RN-02", phase: "relationship", dimension: "response_need", kind: "scenario",
    text: "昨天晚上你们还聊到很晚，今天 TA 却突然变得很安静。回复明显变慢，也没有解释原因。你最自然的第一反应更接近哪一种？",
    options: [
      { id: "1", label: "TA 应该只是忙，我不会特别多想。", value: 1 },
      { id: "2", label: "我会注意到变化，但先继续做自己的事。", value: 2 },
      { id: "3", label: "会有一点疑惑，想看看之后会不会恢复正常。", value: 3 },
      { id: "4", label: "我会开始回想昨天是不是哪里说得不对。", value: 4 },
      { id: "5", label: "我会很想知道 TA 对我的感觉是不是发生了变化。", value: 5 },
    ],
    scoreDirection: "positive", exclusionGroup: "amb_reply_slow_01", signalTags: ["uncertainty_trigger"],
    relationshipTypes: ["ambiguous"], version: "1.0", active: true,
  },
  {
    id: "AMB-RN-02", motherQuestionId: "RN-05", phase: "relationship", dimension: "response_need", kind: "scenario",
    text: "你们原本约好了周末见面。临近当天，TA 突然说：「今天可能不方便了，下次吧。」但没有解释太多。你的第一感觉更接近：",
    options: [
      { id: "1", label: "有自己的事情很正常。", value: 1 },
      { id: "2", label: "会有一点失望，但不会往关系上想。", value: 2 },
      { id: "3", label: "我会想知道发生了什么。", value: 3 },
      { id: "4", label: "我会开始怀疑 TA 是不是没之前那么想见我了。", value: 4 },
      { id: "5", label: "我会非常想确认 TA 对这段关系是不是变了。", value: 5 },
    ],
    scoreDirection: "positive", exclusionGroup: "amb_cancel_plan",
    relationshipTypes: ["ambiguous"], version: "1.0", active: true,
  },
  {
    id: "AMB-EX-01", motherQuestionId: "EX-01", phase: "relationship", dimension: "expression", kind: "scenario",
    text: "你们最近每天都聊天，但没有人主动提过你们到底算什么关系。你更可能：",
    options: [
      { id: "1", label: "完全不说，顺其自然。", value: 1 },
      { id: "2", label: "心里想很多，但不主动提。", value: 2 },
      { id: "3", label: "看 TA 会不会先说。", value: 3 },
      { id: "4", label: "找个合适的时候试探一下。", value: 4 },
      { id: "5", label: "我会比较直接地问 TA 怎么看我们。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["ambiguous"], version: "1.0", active: true,
  },
  {
    id: "AMB-SP-01", motherQuestionId: "SP-01", phase: "relationship", dimension: "space_need", kind: "scenario",
    text: "你们还没有确认关系。TA 经常想每天从早聊到晚。你的感觉更接近：",
    options: [
      { id: "1", label: "很开心，暧昧期就该这样。", value: 1 },
      { id: "2", label: "基本可以，但偶尔需要一点空间。", value: 2 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "会开始觉得有点累。", value: 4 },
      { id: "5", label: "即使暧昧期，我也明显需要自己的时间和节奏。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["ambiguous"], version: "1.0", active: true,
  },
  {
    id: "AMB-ES-01", motherQuestionId: "ES-01", phase: "relationship", dimension: "emotional_sensitivity", kind: "scenario",
    text: "TA 以前回复消息很快，也经常用语气词和表情。最近两天突然变得简短，也没有解释。你更接近：",
    options: [
      { id: "1", label: "完全不会注意到。", value: 1 },
      { id: "2", label: "注意到了，但不会多想。", value: 2 },
      { id: "3", label: "会觉得有一点不同。", value: 3 },
      { id: "4", label: "会明显察觉变化，开始回想原因。", value: 4 },
      { id: "5", label: "我会很快捕捉到这种差异，并想知道是不是和我有关。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["ambiguous"], version: "1.0", active: true,
  },
  {
    id: "AMB-CU-01", motherQuestionId: "CU-04", phase: "relationship", dimension: "conflict_urgency", kind: "scenario",
    text: "你们因为一个暧昧中的误会有些不愉快。晚上 TA 说：「我们先各自睡吧，明天再说。」你更接近：",
    options: [
      { id: "1", label: "这正是我希望的。", value: 1 },
      { id: "2", label: "基本可以接受。", value: 2 },
      { id: "3", label: "看误会严重程度。", value: 3 },
      { id: "4", label: "会觉得事情没说清楚，很难受。", value: 4 },
      { id: "5", label: "暧昧期不解决问题更可怕，我希望现在就说清楚。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["ambiguous"], version: "1.0", active: true,
  },
  {
    id: "AMB-RP-01", motherQuestionId: "RP-04", phase: "relationship", dimension: "repair_orientation", kind: "scenario",
    text: "你们因为一些不确定产生了一点距离。过了几天，TA 主动找你，语气恢复如常。你更接近：",
    options: [
      { id: "1", label: "即使 TA 主动了，我还是很难重新靠近。", value: 1 },
      { id: "2", label: "会观察一阵子。", value: 2 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "如果 TA 真诚，我愿意重新靠近。", value: 4 },
      { id: "5", label: "只要 TA 回来，我通常比较快就能恢复。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["ambiguous"], version: "1.0", active: true,
  },
];

// ========== 刚确定关系 (new_relationship) ==========
export const NEW_RELATIONSHIP_QUESTIONS: Question[] = [
  {
    id: "NEW-RN-01", motherQuestionId: "RN-03", phase: "relationship", dimension: "response_need", kind: "scenario",
    text: "你们刚确认关系没多久。TA 对你很好，但平时很少主动说「想你。」「喜欢你。」「在乎你。」你会更接近：",
    options: [
      { id: "1", label: "只要行动上看得出来，我完全不需要这些表达。", value: 1 },
      { id: "2", label: "偶尔没有也没关系。", value: 2 },
      { id: "3", label: "看具体情况。", value: 3 },
      { id: "4", label: "我会希望 TA 偶尔明确表达一下。", value: 4 },
      { id: "5", label: "对我来说，明确表达会让我明显更安心。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["verbal_reassurance_need"],
    relationshipTypes: ["dating"], relationshipStages: ["new_relationship"], version: "1.0", active: true,
  },
  {
    id: "NEW-RN-02", motherQuestionId: "RN-07", phase: "relationship", dimension: "response_need", kind: "scenario",
    text: "确认关系以后，最开始 TA 经常主动找你。两个月以后主动频率明显下降，但回复依然正常。你的第一判断更接近：",
    options: [
      { id: "1", label: "很正常，关系稳定以后不可能一直像刚开始。", value: 1 },
      { id: "2", label: "会注意，但不会特别往坏处想。", value: 2 },
      { id: "3", label: "我会继续观察。", value: 3 },
      { id: "4", label: "会开始怀疑 TA 的投入是不是下降了。", value: 4 },
      { id: "5", label: "我会明显担心 TA 是不是没有以前那么喜欢我了。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["post_honeymoon_change_sensitivity"],
    relationshipTypes: ["dating"], relationshipStages: ["new_relationship"], version: "1.0", active: true,
  },
  {
    id: "NEW-EX-01", motherQuestionId: "EX-01", phase: "relationship", dimension: "expression", kind: "scenario",
    text: "你们确认关系不久，有一次 TA 做了一件让你不太舒服的事。你更可能：",
    options: [
      { id: "1", label: "刚在一起不想破坏气氛，先不说。", value: 1 },
      { id: "2", label: "忍一下，看以后会不会再发生。", value: 2 },
      { id: "3", label: "不确定要不要提。", value: 3 },
      { id: "4", label: "找机会告诉 TA。", value: 4 },
      { id: "5", label: "比较快说明发生了什么和自己的感受。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["dating"], relationshipStages: ["new_relationship"], version: "1.0", active: true,
  },
  {
    id: "NEW-SP-01", motherQuestionId: "SP-01", phase: "relationship", dimension: "space_need", kind: "scenario",
    text: "刚确认关系，TA 几乎每天都想见面或长时间聊天。你的感觉更接近：",
    options: [
      { id: "1", label: "热恋期就该这样。", value: 1 },
      { id: "2", label: "基本可以，偶尔需要一点自己的时间。", value: 2 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "会有点想退一步。", value: 4 },
      { id: "5", label: "即使刚在一起，我也明显需要保留自己的生活节奏。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["dating"], relationshipStages: ["new_relationship"], version: "1.0", active: true,
  },
  {
    id: "NEW-CU-01", motherQuestionId: "CU-04", phase: "relationship", dimension: "conflict_urgency", kind: "scenario",
    text: "你们确认关系后的第一次明显争执。晚上 TA 说：「我们先各自冷静，明天再说。」你更接近：",
    options: [
      { id: "1", label: "这正是我希望的。", value: 1 },
      { id: "2", label: "基本可以接受。", value: 2 },
      { id: "3", label: "看问题严重程度。", value: 3 },
      { id: "4", label: "会觉得事情没说清楚，很不舒服。", value: 4 },
      { id: "5", label: "第一次争执就必须马上解决，否则会越来越不安。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["dating"], relationshipStages: ["new_relationship"], version: "1.0", active: true,
  },
  {
    id: "NEW-RP-01", motherQuestionId: "RP-01", phase: "relationship", dimension: "repair_orientation", kind: "scenario",
    text: "你们第一次吵架以后，第二天 TA 发来消息：「昨天我也有不对的地方。」你更可能：",
    options: [
      { id: "1", label: "即使 TA 这样说，我还是很难马上回应。", value: 1 },
      { id: "2", label: "会观察 TA 是不是真心的。", value: 2 },
      { id: "3", label: "看事情是什么。", value: 3 },
      { id: "4", label: "如果 TA 主动了，我愿意回应。", value: 4 },
      { id: "5", label: "只要 TA 释放善意，我通常比较快就能恢复。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["dating"], relationshipStages: ["new_relationship"], version: "1.0", active: true,
  },
];

// ========== 稳定恋爱 (stable) ==========
export const STABLE_QUESTIONS: Question[] = [
  {
    id: "ST-RN-01", motherQuestionId: "RN-03", phase: "relationship", dimension: "response_need", kind: "scenario",
    text: "你们已经在一起比较久，彼此都知道对方是认真的。但 TA 现在已经很少主动说「想你。」「爱你。」「很在乎你。」你更接近：",
    options: [
      { id: "1", label: "我完全不需要这些表达。", value: 1 },
      { id: "2", label: "偶尔没有没关系。", value: 2 },
      { id: "3", label: "看平时行动。", value: 3 },
      { id: "4", label: "我还是希望偶尔听到明确表达。", value: 4 },
      { id: "5", label: "即使关系稳定，我仍然会因为这些表达明显更安心。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["ongoing_reassurance_need"],
    relationshipTypes: ["dating"], relationshipStages: ["stable"], version: "1.0", active: true,
  },
  {
    id: "ST-RN-02", motherQuestionId: "RN-07", phase: "relationship", dimension: "response_need", kind: "scenario",
    text: "刚恋爱时 TA 很主动。现在关系稳定以后，大部分联系和见面都变得比较自然，不再像以前那样频繁主动制造惊喜。你的感觉：",
    options: [
      { id: "1", label: "很正常，稳定以后本来就会变得自然。", value: 1 },
      { id: "2", label: "会注意，但不会特别在意。", value: 2 },
      { id: "3", label: "偶尔会想以前是不是更热情。", value: 3 },
      { id: "4", label: "会开始怀疑 TA 的投入是不是在下降。", value: 4 },
      { id: "5", label: "我会明显担心「习惯以后是不是就没那么在乎了」。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["novelty_decline_sensitivity"],
    relationshipTypes: ["dating"], relationshipStages: ["stable"], version: "1.0", active: true,
  },
  {
    id: "ST-EX-01", motherQuestionId: "EX-01", phase: "relationship", dimension: "expression", kind: "scenario",
    text: "你们已经在一起很久。最近 TA 有一个习惯越来越让你不舒服，但每次看起来都只是小事。你更可能：",
    options: [
      { id: "1", label: "一直不说。", value: 1 },
      { id: "2", label: "忍到真的受不了。", value: 2 },
      { id: "3", label: "看什么时候合适。", value: 3 },
      { id: "4", label: "找个机会认真告诉 TA。", value: 4 },
      { id: "5", label: "比较快说明，小事也需要沟通。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["dating"], relationshipStages: ["stable"], version: "1.0", active: true,
  },
  {
    id: "ST-SP-01", motherQuestionId: "SP-04", phase: "relationship", dimension: "space_need", kind: "scenario",
    text: "你们难得有完整周末，但你想拿半天处理自己的事情、运动或见朋友。你更接近：",
    options: [
      { id: "1", label: "恋爱以后完整周末最好一起。", value: 1 },
      { id: "2", label: "大部分应该给伴侣。", value: 2 },
      { id: "3", label: "看最近见面多少。", value: 3 },
      { id: "4", label: "留半天自己安排很正常。", value: 4 },
      { id: "5", label: "我很需要长期保留这种自主生活。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["dating"], relationshipStages: ["stable"], version: "1.0", active: true,
  },
  {
    id: "ST-CU-01", motherQuestionId: "CU-02", phase: "relationship", dimension: "conflict_urgency", kind: "scenario",
    text: "你们因为一件重复出现的小事又开始争执。TA 说：「我们以前也聊过这个，这次能不能先放一放。」你更接近：",
    options: [
      { id: "1", label: "可以，先放一放。", value: 1 },
      { id: "2", label: "基本能接受，但有点不舒服。", value: 2 },
      { id: "3", label: "看事情重要程度。", value: 3 },
      { id: "4", label: "会觉得很堵，因为以前聊过但没解决。", value: 4 },
      { id: "5", label: "正因为以前聊过没解决，这次必须说清楚。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["dating"], relationshipStages: ["stable"], version: "1.0", active: true,
  },
  {
    id: "ST-RP-01", motherQuestionId: "RP-10", phase: "relationship", dimension: "repair_orientation", kind: "scenario",
    text: "你们过去经常因为同一个问题争吵。这次双方决定以后固定一种新的处理方式。你会觉得：",
    options: [
      { id: "1", label: "没什么区别。", value: 1 },
      { id: "2", label: "要看是否执行。", value: 2 },
      { id: "3", label: "有一些帮助。", value: 3 },
      { id: "4", label: "比单纯道歉更有效。", value: 4 },
      { id: "5", label: "这种具体改变才让我感觉问题真正进入修复。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["concrete_repair_preference"],
    relationshipTypes: ["dating"], relationshipStages: ["stable"], version: "1.0", active: true,
  },
];

// ========== 异地恋 (long_distance) ==========
export const LDR_QUESTIONS: Question[] = [
  {
    id: "LDR-RN-01", motherQuestionId: "RN-02", phase: "relationship", dimension: "response_need", kind: "scenario",
    text: "你发了一条比较重要的消息。TA 明明在线，但过了很久都没有回复。你最容易：",
    options: [
      { id: "1", label: "觉得很正常，在线不代表有空。", value: 1 },
      { id: "2", label: "会注意，但不太在意。", value: 2 },
      { id: "3", label: "会有一点疑惑。", value: 3 },
      { id: "4", label: "会开始想 TA 为什么选择不回。", value: 4 },
      { id: "5", label: "会明显担心这是不是一种关系信号。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["response_choice_sensitivity"],
    relationshipTypes: ["dating"], relationshipStages: ["long_distance"], version: "1.0", active: true,
  },
  {
    id: "LDR-RN-02", motherQuestionId: "RN-08", phase: "relationship", dimension: "response_need", kind: "scenario",
    text: "TA 提前告诉你：「明天会特别忙，可能一整天都没什么时间回消息，但晚上我会找你。」这会让你：",
    options: [
      { id: "1", label: "几乎没有帮助。", value: 1 },
      { id: "2", label: "稍微安心一点。", value: 2 },
      { id: "3", label: "一半一半。", value: 3 },
      { id: "4", label: "明显安心很多。", value: 4 },
      { id: "5", label: "基本不会因为白天联系少而担心。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["predictability_reduces_anxiety"],
    relationshipTypes: ["dating"], relationshipStages: ["long_distance"], version: "1.0", active: true,
  },
  {
    id: "LDR-EX-01", motherQuestionId: "EX-05", phase: "relationship", dimension: "expression", kind: "scenario",
    text: "当你很想 TA 时，你通常会：",
    options: [
      { id: "1", label: "很少说出来。", value: 1 },
      { id: "2", label: "偶尔暗示。", value: 2 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "会主动表达。", value: 4 },
      { id: "5", label: "我会比较直接告诉 TA：「我今天很想你。」", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["dating"], relationshipStages: ["long_distance"], version: "1.0", active: true,
  },
  {
    id: "LDR-SP-01", motherQuestionId: "SP-09", phase: "relationship", dimension: "space_need", kind: "scenario",
    text: "异地恋里，TA 希望你们每天至少视频半小时。你的感觉更接近：",
    options: [
      { id: "1", label: "异地就应该这样保持联系。", value: 1 },
      { id: "2", label: "大部分时候可以。", value: 2 },
      { id: "3", label: "看当天状态。", value: 3 },
      { id: "4", label: "有时候会想自己待着。", value: 4 },
      { id: "5", label: "即使异地，我也需要明确的个人时间。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["dating"], relationshipStages: ["long_distance"], version: "1.0", active: true,
  },
  {
    id: "LDR-ES-01", motherQuestionId: "ES-04", phase: "relationship", dimension: "emotional_sensitivity", kind: "scenario",
    text: "视频通话时，TA 说「我没事」，但你觉得 TA 语气和平常不太一样。你更可能：",
    options: [
      { id: "1", label: "相信 TA 说的，不再多想。", value: 1 },
      { id: "2", label: "注意到，但先不追问。", value: 2 },
      { id: "3", label: "一边观察一边等。", value: 3 },
      { id: "4", label: "会试探一下是不是真的没事。", value: 4 },
      { id: "5", label: "异地本来就看不到表情，我通常会追到底。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["dating"], relationshipStages: ["long_distance"], version: "1.0", active: true,
  },
  {
    id: "LDR-RP-01", motherQuestionId: "RP-04", phase: "relationship", dimension: "repair_orientation", kind: "scenario",
    text: "你们异地吵了一架，之后 TA 连续两天都没有主动联系你。第三天 TA 发来「对不起，我之前态度不好」。你更可能：",
    options: [
      { id: "1", label: "两天不联系已经让我很难再回应了。", value: 1 },
      { id: "2", label: "会听，但心里还有芥蒂。", value: 2 },
      { id: "3", label: "看 TA 后续表现。", value: 3 },
      { id: "4", label: "如果 TA 道歉真诚，我愿意回应。", value: 4 },
      { id: "5", label: "只要 TA 回来，我通常比较快恢复。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["dating"], relationshipStages: ["long_distance"], version: "1.0", active: true,
  },
];

// ========== 长期伴侣/已婚 (long_term) ==========
export const MARRIED_QUESTIONS: Question[] = [
  {
    id: "MAR-RN-01", motherQuestionId: "RN-03", phase: "relationship", dimension: "response_need", kind: "scenario",
    text: "你们已经在一起很久了。TA 每天都在为家庭和工作忙碌，但很少再主动说「我爱你」或表达对你的欣赏。你更接近：",
    options: [
      { id: "1", label: "做的事本身就是爱，不需要说。", value: 1 },
      { id: "2", label: "大部分可以理解。", value: 2 },
      { id: "3", label: "偶尔会希望听到。", value: 3 },
      { id: "4", label: "会明显觉得自己的状态没有被看见。", value: 4 },
      { id: "5", label: "我很需要在家庭角色之外，仍然被当成一个有感受的伴侣。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["long_term"], version: "1.0", active: true,
  },
  {
    id: "MAR-EX-01", motherQuestionId: "EX-03", phase: "relationship", dimension: "expression", kind: "scenario",
    text: "最近你觉得家庭负担分配有点不公平，但你担心一说又变成「谁做得更多」的争吵。你更可能：",
    options: [
      { id: "1", label: "直接谈。", value: 1 },
      { id: "2", label: "尽量找机会沟通。", value: 2 },
      { id: "3", label: "会拖一段时间。", value: 3 },
      { id: "4", label: "容易压着不说。", value: 4 },
      { id: "5", label: "我经常先自己扛，直到情绪积累很多。", value: 5 },
    ],
    scoreDirection: "reverse",
    relationshipTypes: ["long_term"], version: "1.0", active: true,
  },
  {
    id: "MAR-SP-01", motherQuestionId: "SP-01", phase: "relationship", dimension: "space_need", kind: "scenario",
    text: "终于有一个晚上没有孩子、工作和家庭事情，你其实只想一个人安静待着。如果 TA 希望两个人一起活动，你会：",
    options: [
      { id: "1", label: "觉得应该优先一起。", value: 1 },
      { id: "2", label: "会勉强自己。", value: 2 },
      { id: "3", label: "看当天状态。", value: 3 },
      { id: "4", label: "会希望 TA 理解自己需要恢复。", value: 4 },
      { id: "5", label: "长期高责任生活里，我非常需要不被任何人需要的一小段时间。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["long_term"], version: "1.0", active: true,
  },
  {
    id: "MAR-ES-01", motherQuestionId: "ES-05", phase: "relationship", dimension: "emotional_sensitivity", kind: "scenario",
    text: "TA 最近因为工作、孩子或父母事情长期烦躁。即使没有直接对你发火：",
    options: [
      { id: "1", label: "基本不受影响。", value: 1 },
      { id: "2", label: "会有一点被影响。", value: 2 },
      { id: "3", label: "中等程度受影响。", value: 3 },
      { id: "4", label: "会明显被 TA 的状态带着走。", value: 4 },
      { id: "5", label: "我很容易感觉自己也在承担 TA 的压力。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["family_emotional_spillover"],
    relationshipTypes: ["long_term"], version: "1.0", active: true,
  },
  {
    id: "MAR-CU-01", motherQuestionId: "CU-04", phase: "relationship", dimension: "conflict_urgency", kind: "scenario",
    text: "晚上孩子刚睡，你们因为家庭分工争起来。已经非常晚，双方第二天都要工作。TA 提议：「我们周六上午专门坐下来谈分工。」你更接近：",
    options: [
      { id: "1", label: "这样最好。", value: 1 },
      { id: "2", label: "基本能接受。", value: 2 },
      { id: "3", label: "仍然会有点堵。", value: 3 },
      { id: "4", label: "还是希望今晚先谈。", value: 4 },
      { id: "5", label: "我很难接受这种问题继续悬几天。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["long_term"], version: "1.0", active: true,
  },
  {
    id: "MAR-RP-01", motherQuestionId: "RP-10", phase: "relationship", dimension: "repair_orientation", kind: "scenario",
    text: "你们过去经常因为家务分工争吵。这次双方决定以后固定把某几项完全交给 TA，另外几项完全由你负责。你会觉得：",
    options: [
      { id: "1", label: "没什么区别。", value: 1 },
      { id: "2", label: "要看是否执行。", value: 2 },
      { id: "3", label: "有一些帮助。", value: 3 },
      { id: "4", label: "比单纯道歉更有效。", value: 4 },
      { id: "5", label: "这种具体改变才让我感觉问题真正进入修复。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["concrete_repair_preference"],
    relationshipTypes: ["long_term"], version: "1.0", active: true,
  },
];

// ========== 关系紧张 (tense) ==========
export const TENSE_QUESTIONS: Question[] = [
  {
    id: "TEN-RN-01", motherQuestionId: "RN-07", phase: "relationship", dimension: "response_need", kind: "scenario",
    text: "最近你们之间频繁出现摩擦。你发现自己越来越频繁地检查 TA 的态度有没有变化。你更接近：",
    options: [
      { id: "1", label: "我尽量不去想。", value: 1 },
      { id: "2", label: "偶尔会注意。", value: 2 },
      { id: "3", label: "看当天情况。", value: 3 },
      { id: "4", label: "经常会留意 TA 的每一个细微变化。", value: 4 },
      { id: "5", label: "我几乎时刻都在判断 TA 是不是还在意这段关系。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["hypervigilance"],
    relationshipStages: ["tense"], version: "1.0", active: true,
  },
  {
    id: "TEN-EX-01", motherQuestionId: "EX-09", phase: "relationship", dimension: "expression", kind: "scenario",
    text: "你们最近矛盾很多。你有一些话想跟 TA 说，但每次话到嘴边又咽了回去。你更接近：",
    options: [
      { id: "1", label: "我会直接说。", value: 1 },
      { id: "2", label: "大部分时候会说。", value: 2 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "经常压着不说，怕又吵起来。", value: 4 },
      { id: "5", label: "我几乎不说真实想法了，说了也没用。", value: 5 },
    ],
    scoreDirection: "reverse", signalTags: ["communication_futility"],
    relationshipStages: ["tense"], version: "1.0", active: true,
  },
  {
    id: "TEN-SP-01", motherQuestionId: "SP-02", phase: "relationship", dimension: "space_need", kind: "scenario",
    text: "争吵后你经常想一个人待着。最近你发现自己独处的时间越来越长。你更接近：",
    options: [
      { id: "1", label: "我只是需要恢复，不是想远离关系。", value: 1 },
      { id: "2", label: "大部分是在恢复。", value: 2 },
      { id: "3", label: "一半一半。", value: 3 },
      { id: "4", label: "有时候觉得远离 TA 反而更轻松。", value: 4 },
      { id: "5", label: "我越来越觉得一个人待着比和 TA 一起更舒服。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["relief_in_disconnection", "sharing_withdrawal"],
    relationshipStages: ["tense"], version: "1.0", active: true,
  },
  {
    id: "TEN-RP-01", motherQuestionId: "RP-09", phase: "relationship", dimension: "repair_orientation", kind: "scenario",
    text: "你们已经因为同一个问题争吵了很多次，每次最后都说「以后改」，但不久又恢复原样。你更接近：",
    options: [
      { id: "1", label: "我仍然相信下次会不同。", value: 1 },
      { id: "2", label: "大部分时候还愿意试。", value: 2 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "已经开始对修复失去信心。", value: 4 },
      { id: "5", label: "我已经很难相信再谈一次会有什么不同。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["repeated_pattern_erosion", "repair_fatigue"],
    relationshipStages: ["tense"], version: "1.0", active: true,
  },
  {
    id: "TEN-CU-01", motherQuestionId: "CU-09", phase: "relationship", dimension: "conflict_urgency", kind: "scenario",
    text: "争吵后 TA 突然长时间不回应你。你更接近：",
    options: [
      { id: "1", label: "我觉得暂停一下也好。", value: 1 },
      { id: "2", label: "能接受一段时间的沉默。", value: 2 },
      { id: "3", label: "看沉默多久。", value: 3 },
      { id: "4", label: "会觉得很难受，比争吵本身更不舒服。", value: 4 },
      { id: "5", label: "长时间沉默让我感觉关系正在结束。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["silence_after_conflict_trigger"],
    relationshipStages: ["tense"], version: "1.0", active: true,
  },
  {
    id: "TEN-ES-01", motherQuestionId: "ES-05", phase: "relationship", dimension: "emotional_sensitivity", kind: "scenario",
    text: "TA 最近经常叹气或表现烦躁，即使没有直接对你。你更接近：",
    options: [
      { id: "1", label: "不太会注意到。", value: 1 },
      { id: "2", label: "注意到了但不在意。", value: 2 },
      { id: "3", label: "会有点担心。", value: 3 },
      { id: "4", label: "会明显感到紧张不安。", value: 4 },
      { id: "5", label: "我会感觉自己也越来越烦躁。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["emotional_contagion"],
    relationshipStages: ["tense"], version: "1.0", active: true,
  },
];

// ========== 朋友关系 (friend) ==========
export const FRIEND_QUESTIONS: Question[] = [
  {
    id: "FR-RN-01", motherQuestionId: "RN-07", phase: "relationship", dimension: "response_need", kind: "scenario",
    text: "你们一直是很好的朋友。最近你发现自己总是主动联系 TA，而 TA 很少先找你。你更接近：",
    options: [
      { id: "1", label: "完全不在意谁先联系。", value: 1 },
      { id: "2", label: "会注意，但不太在意。", value: 2 },
      { id: "3", label: "会观察一阵子。", value: 3 },
      { id: "4", label: "会开始觉得这段友情可能对我比对他更重要。", value: 4 },
      { id: "5", label: "我会明显怀疑 TA 是不是不那么在意这段友情了。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["initiative_imbalance"],
    relationshipTypes: ["friend"], version: "1.0", active: true,
  },
  {
    id: "FR-EX-01", motherQuestionId: "EX-01", phase: "relationship", dimension: "expression", kind: "scenario",
    text: "TA 最近几次取消了你们原定的计划。你心里不太舒服，但不确定该不该说。你更可能：",
    options: [
      { id: "1", label: "完全不说，朋友之间不用计较。", value: 1 },
      { id: "2", label: "忍一下，看以后。", value: 2 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "找机会告诉 TA。", value: 4 },
      { id: "5", label: "比较直接说清楚，朋友也需要沟通。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["friend"], version: "1.0", active: true,
  },
  {
    id: "FR-SP-01", motherQuestionId: "SP-04", phase: "relationship", dimension: "space_need", kind: "scenario",
    text: "TA 最近遇到困难，连续几天都想找你倾诉。但你自己的生活也很忙。你更接近：",
    options: [
      { id: "1", label: "朋友有困难就应该陪。", value: 1 },
      { id: "2", label: "大部分时候会抽时间。", value: 2 },
      { id: "3", label: "看当天状态。", value: 3 },
      { id: "4", label: "有时候需要跟 TA 说我也需要自己的时间。", value: 4 },
      { id: "5", label: "即使是很重要的朋友，我也需要保留自己的节奏。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["friend"], version: "1.0", active: true,
  },
  {
    id: "FR-ES-01", motherQuestionId: "ES-04", phase: "relationship", dimension: "emotional_sensitivity", kind: "scenario",
    text: "TA 说「我没事」，但你觉得 TA 的语气和平时不一样。你更可能：",
    options: [
      { id: "1", label: "相信 TA 说的。", value: 1 },
      { id: "2", label: "注意到了但不追问。", value: 2 },
      { id: "3", label: "看关系亲近程度。", value: 3 },
      { id: "4", label: "会试探一下。", value: 4 },
      { id: "5", label: "朋友之间我通常也能感觉出来，会主动问。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["friend"], version: "1.0", active: true,
  },
  {
    id: "FR-CU-01", motherQuestionId: "CU-02", phase: "relationship", dimension: "conflict_urgency", kind: "scenario",
    text: "你们因为一件事情产生了误会，TA 明显不太高兴但没直说。你更接近：",
    options: [
      { id: "1", label: "等 TA 自己消化。", value: 1 },
      { id: "2", label: "给 TA 几天空间。", value: 2 },
      { id: "3", label: "看事情重要程度。", value: 3 },
      { id: "4", label: "会觉得不舒服，想尽快说清楚。", value: 4 },
      { id: "5", label: "朋友之间也不能冷战，我会主动找 TA 谈。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["friend"], version: "1.0", active: true,
  },
  {
    id: "FR-RP-01", motherQuestionId: "RP-04", phase: "relationship", dimension: "repair_orientation", kind: "scenario",
    text: "你们因为一个误会产生距离，过了几周 TA 主动约你出来，像什么都没发生过。你更可能：",
    options: [
      { id: "1", label: "很难马上恢复如常。", value: 1 },
      { id: "2", label: "会观察一阵。", value: 2 },
      { id: "3", label: "看事情是什么。", value: 3 },
      { id: "4", label: "如果 TA 主动了，我愿意回应。", value: 4 },
      { id: "5", label: "朋友之间我通常比较快就能放下。", value: 5 },
    ],
    scoreDirection: "positive",
    relationshipTypes: ["friend"], version: "1.0", active: true,
  },
];

// ========== 年龄/生活阶段变体 ==========
export const LIFE_STAGE_QUESTIONS: Question[] = [
  // 18-24 岁
  {
    id: "Y18-RN-01", motherQuestionId: "RN-07", phase: "life_stage", dimension: "response_need", kind: "scenario",
    text: "以前 TA 下课、下班或者打完游戏经常会主动找你。最近 TA 还是会回复，但越来越少主动开启聊天。你更接近：",
    options: [
      { id: "1", label: "很正常。", value: 1 },
      { id: "2", label: "会注意，但不太在意。", value: 2 },
      { id: "3", label: "会观察。", value: 3 },
      { id: "4", label: "会开始怀疑 TA 的投入是不是下降了。", value: 4 },
      { id: "5", label: "会明显觉得自己在 TA 心里的位置可能变了。", value: 5 },
    ],
    scoreDirection: "positive", ageBands: ["18_24"], version: "1.0", active: true,
  },
  {
    id: "Y18-EX-01", motherQuestionId: "EX-04", phase: "life_stage", dimension: "expression", kind: "scenario",
    text: "你最近学习或工作压力很大，很希望 TA 多陪你一点。你更可能：",
    options: [
      { id: "1", label: "不说。", value: 1 },
      { id: "2", label: "发一些暗示。", value: 2 },
      { id: "3", label: "看 TA 能不能自己发现。", value: 3 },
      { id: "4", label: "告诉 TA：「我最近有点需要你。」", value: 4 },
      { id: "5", label: "会具体说希望什么时候陪、以什么方式陪。", value: 5 },
    ],
    scoreDirection: "positive", ageBands: ["18_24"], version: "1.0", active: true,
  },
  // 25-34 岁
  {
    id: "Y25-RN-01", motherQuestionId: "RN-07", phase: "life_stage", dimension: "response_need", kind: "scenario",
    text: "双方工作都很忙。以前 TA 会主动安排见面，现在通常都是你先问：「这周哪天有空？」你更接近：",
    options: [
      { id: "1", label: "谁约都一样。", value: 1 },
      { id: "2", label: "会注意，但没关系。", value: 2 },
      { id: "3", label: "会观察。", value: 3 },
      { id: "4", label: "时间久了会觉得投入不太平衡。", value: 4 },
      { id: "5", label: "会开始怀疑自己是不是没有被真正放进 TA 的时间安排。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["calendar_priority_sensitivity"], ageBands: ["25_34"], version: "1.0", active: true,
  },
  {
    id: "Y25-SP-01", motherQuestionId: "SP-04", phase: "life_stage", dimension: "space_need", kind: "scenario",
    text: "你们难得有完整周末，但你想拿半天处理自己的事情、运动或见朋友。你更接近：",
    options: [
      { id: "1", label: "恋爱以后完整周末最好一起。", value: 1 },
      { id: "2", label: "大部分应该给伴侣。", value: 2 },
      { id: "3", label: "看最近见面多少。", value: 3 },
      { id: "4", label: "留半天自己安排很正常。", value: 4 },
      { id: "5", label: "我很需要长期保留这种自主生活。", value: 5 },
    ],
    scoreDirection: "positive", ageBands: ["25_34"], version: "1.0", active: true,
  },
  // 35-44 岁
  {
    id: "Y35-RN-01", motherQuestionId: "RN-05", phase: "life_stage", dimension: "response_need", kind: "scenario",
    text: "工作、孩子、家务和双方父母占据了大量时间。你发现两个人已经很久没有专门留时间给彼此。你更接近：",
    options: [
      { id: "1", label: "这个阶段很正常。", value: 1 },
      { id: "2", label: "偶尔会觉得遗憾。", value: 2 },
      { id: "3", label: "会觉得需要调整。", value: 3 },
      { id: "4", label: "会明显感觉伴侣关系总被排在最后。", value: 4 },
      { id: "5", label: "我会担心我们慢慢只剩家庭合作，没有真正的关系连接。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["partner_role_eroded_by_family_system"], ageBands: ["35_44"], version: "1.0", active: true,
  },
  {
    id: "Y35-SP-01", motherQuestionId: "SP-01", phase: "life_stage", dimension: "space_need", kind: "scenario",
    text: "终于有一个晚上没有孩子、工作和家庭事情，你其实只想一个人安静待着。如果 TA 希望两个人一起活动，你会：",
    options: [
      { id: "1", label: "觉得应该优先一起。", value: 1 },
      { id: "2", label: "会勉强自己。", value: 2 },
      { id: "3", label: "看当天状态。", value: 3 },
      { id: "4", label: "会希望 TA 理解自己需要恢复。", value: 4 },
      { id: "5", label: "长期高责任生活里，我非常需要不被任何人需要的一小段时间。", value: 5 },
    ],
    scoreDirection: "positive", ageBands: ["35_44"], version: "1.0", active: true,
  },
  // 45+ 岁
  {
    id: "Y45-RN-01", motherQuestionId: "RN-03", phase: "life_stage", dimension: "response_need", kind: "scenario",
    text: "你们已经相处很多年，很多事情不需要说也能配合。但 TA 很久没有主动表达过欣赏、感谢或喜欢。你更接近：",
    options: [
      { id: "1", label: "完全不需要。", value: 1 },
      { id: "2", label: "偶尔没有没关系。", value: 2 },
      { id: "3", label: "有时候还是希望听见。", value: 3 },
      { id: "4", label: "我会觉得长期关系也需要被表达。", value: 4 },
      { id: "5", label: "我很在意自己是否仍然被 TA 当成一个值得欣赏的人，而不只是熟悉的家人。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["long_term_appreciation_need"], ageBands: ["45_plus"], version: "1.0", active: true,
  },
  {
    id: "Y45-RP-01", motherQuestionId: "RP-04", phase: "life_stage", dimension: "repair_orientation", kind: "scenario",
    text: "一个问题过去很多年一直没有解决，但最近双方生活环境发生变化，也终于有了新的解决条件。你：",
    options: [
      { id: "1", label: "觉得已经太晚。", value: 1 },
      { id: "2", label: "很难再相信。", value: 2 },
      { id: "3", label: "会观察。", value: 3 },
      { id: "4", label: "愿意重新尝试。", value: 4 },
      { id: "5", label: "我愿意根据现在新的条件，而不是只根据过去失败的次数判断修复可能性。", value: 5 },
    ],
    scoreDirection: "positive", ageBands: ["45_plus"], version: "1.0", active: true,
  },
  // 为每个年龄段补足至少 4 道生活场景题
  {
    id: "Y18-SP-01", motherQuestionId: "SP-01", phase: "life_stage", dimension: "space_need", kind: "scenario",
    text: "你们一天里已经聊了很多，但晚上你只想和朋友打游戏、追剧或者自己待着。你会觉得：",
    options: [
      { id: "1", label: "恋爱了就应该继续陪 TA。", value: 1 },
      { id: "2", label: "有点不好意思拒绝。", value: 2 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "想自己玩很正常。", value: 4 },
      { id: "5", label: "即使热恋，我也需要自己的时间。", value: 5 },
    ],
    scoreDirection: "positive", ageBands: ["18_24", "under_18"], version: "1.0", active: true,
  },
  {
    id: "Y18-ES-01", motherQuestionId: "ES-01", phase: "life_stage", dimension: "emotional_sensitivity", kind: "scenario",
    text: "TA 平时聊天会发很多表情、语气词或梗，今天却突然只回复很短的话。你：",
    options: [
      { id: "1", label: "很可能不会注意。", value: 1 },
      { id: "2", label: "注意到也不想太多。", value: 2 },
      { id: "3", label: "会觉得有点不一样。", value: 3 },
      { id: "4", label: "会明显察觉变化。", value: 4 },
      { id: "5", label: "我通常很快就会发现这种小变化。", value: 5 },
    ],
    scoreDirection: "positive", ageBands: ["18_24", "under_18"], version: "1.0", active: true,
  },
  {
    id: "Y25-EX-01", motherQuestionId: "EX-01", phase: "life_stage", dimension: "expression", kind: "scenario",
    text: "TA 最近连续加班，见面越来越少。你知道 TA 真的很忙，但自己也明显失落。你更可能：",
    options: [
      { id: "1", label: "完全不说。", value: 1 },
      { id: "2", label: "自己消化。", value: 2 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "告诉 TA 自己最近有点失落。", value: 4 },
      { id: "5", label: "会进一步一起讨论，忙碌阶段怎么保持最低限度的相处时间。", value: 5 },
    ],
    scoreDirection: "positive", ageBands: ["25_34"], version: "1.0", active: true,
  },
  {
    id: "Y25-CU-01", motherQuestionId: "CU-10", phase: "life_stage", dimension: "conflict_urgency", kind: "scenario",
    text: "你们晚上因为未来规划聊得不愉快。TA 第二天一早要参加重要会议，于是说：「我现在脑子不行，明天下班后我们专门谈。」你：",
    options: [
      { id: "1", label: "很难接受。", value: 5 },
      { id: "2", label: "还是会比较悬着。", value: 4 },
      { id: "3", label: "看情况。", value: 3 },
      { id: "4", label: "有明确时间就比较能接受。", value: 2 },
      { id: "5", label: "只要 TA 确定会回来谈，我完全可以暂停。", value: 1 },
    ],
    scoreDirection: "positive", ageBands: ["25_34"], version: "1.0", active: true,
  },
  {
    id: "Y35-ES-01", motherQuestionId: "ES-05", phase: "life_stage", dimension: "emotional_sensitivity", kind: "scenario",
    text: "TA 最近因为工作、孩子或父母事情长期烦躁。即使没有直接对你发火：",
    options: [
      { id: "1", label: "基本不影响。", value: 1 },
      { id: "2", label: "会有一点被影响。", value: 2 },
      { id: "3", label: "中等程度受影响。", value: 3 },
      { id: "4", label: "会明显被 TA 的状态带着走。", value: 4 },
      { id: "5", label: "我很容易感觉自己也在承担 TA 的压力。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["family_emotional_spillover"], ageBands: ["35_44"], version: "1.0", active: true,
  },
  {
    id: "Y35-CU-01", motherQuestionId: "CU-04", phase: "life_stage", dimension: "conflict_urgency", kind: "scenario",
    text: "晚上孩子刚睡，你们因为家庭分工争起来。TA 提议：「我们周六上午专门坐下来谈分工。」你更接近：",
    options: [
      { id: "1", label: "这样最好。", value: 1 },
      { id: "2", label: "基本能接受。", value: 2 },
      { id: "3", label: "仍然会有点堵。", value: 3 },
      { id: "4", label: "还是希望今晚先谈。", value: 4 },
      { id: "5", label: "我很难接受这种问题继续悬几天。", value: 5 },
    ],
    scoreDirection: "positive", ageBands: ["35_44"], version: "1.0", active: true,
  },
  {
    id: "Y45-SP-01", motherQuestionId: "SP-04", phase: "life_stage", dimension: "space_need", kind: "scenario",
    text: "孩子逐渐独立以后，你突然拥有比以前更多属于自己的时间。你更希望：",
    options: [
      { id: "1", label: "大部分重新变成夫妻共同时间。", value: 1 },
      { id: "2", label: "主要一起安排。", value: 2 },
      { id: "3", label: "一部分一起、一部分自己。", value: 3 },
      { id: "4", label: "很想重新发展自己的兴趣和社交。", value: 4 },
      { id: "5", label: "我希望长期关系允许双方重新成为更独立的个体。", value: 5 },
    ],
    scoreDirection: "positive", signalTags: ["post_parenting_autonomy"], ageBands: ["45_plus"], version: "1.0", active: true,
  },
  {
    id: "Y45-CU-01", motherQuestionId: "CU-03", phase: "life_stage", dimension: "conflict_urgency", kind: "scenario",
    text: "一个反复很多年的老问题再次出现。你更接近：",
    options: [
      { id: "1", label: "我不想再争，宁愿完全放下。", value: 1 },
      { id: "2", label: "会先冷静很久。", value: 2 },
      { id: "3", label: "看事情重要性。", value: 3 },
      { id: "4", label: "如果它仍然影响生活，我愿意重新谈。", value: 4 },
      { id: "5", label: "即使谈过很多次，只要还重要，我还是希望真正处理。", value: 5 },
    ],
    scoreDirection: "positive", ageBands: ["45_plus"], version: "1.0", active: true,
  },
];

// ========== V2.0 文档补全变体 ==========
// 选项文案在部分源文档中为双极、三档或仅给出量表方向；为保持稳定的可计分结构，以下完整保留原题文本并统一使用有效 Likert 选项。

AMBIGUOUS_QUESTIONS.push(
  ...asLikert([
    { id: "AMB-RN-03", motherQuestionId: "RN-08", dimension: "response_need", text: "TA 一整天明显比平时话少。晚上 TA 主动告诉你：“今天工作特别忙，所以没怎么看手机，不是因为你。”你通常会：", signalTags: ["reassurance_then_calm"], relationshipTypes: ["ambiguous"] },
    { id: "AMB-RN-04", motherQuestionId: "RN-09", dimension: "response_need", text: "你已经比较确定 TA 对你有好感。但最近几天你们都很忙，聊天明显减少。你更接近：", scoreDirection: "reverse", relationshipTypes: ["ambiguous"] },
    { id: "AMB-RN-05", motherQuestionId: "RN-03", dimension: "response_need", text: "你们已经暧昧了一段时间。TA 对你很好，也经常主动联系，但一直没有说过你们现在到底算什么。你会更接近：", signalTags: ["relationship_label_need"], relationshipTypes: ["ambiguous"] },
    { id: "AMB-RN-06", motherQuestionId: "RN-10", dimension: "response_need", text: "如果只能选择一种暧昧状态，你更能接受哪一种？每天都聊很多，但 TA 从不明确表达对你的特殊在意；或联系没有那么频繁，但 TA 会明确告诉你：“我是真的在认真了解你。”", signalTags: ["clarity_over_frequency"], relationshipTypes: ["ambiguous"] },
    { id: "AMB-RN-07", motherQuestionId: "RN-07", dimension: "response_need", text: "最近几次聊天，似乎总是你先找 TA。TA 还是会认真回复，但主动联系明显减少。你更容易：", signalTags: ["initiative_imbalance_sensitivity"], relationshipTypes: ["ambiguous"] },
    { id: "AMB-EX-02", motherQuestionId: "EX-03", dimension: "expression", text: "TA 有一天突然对你比较冷淡。其实你很在意，但又不想显得自己太在乎。你更可能：", scoreDirection: "reverse", relationshipTypes: ["ambiguous"] },
    { id: "AMB-EX-03", motherQuestionId: "EX-07", dimension: "expression", text: "当你希望 TA 知道你其实有一点吃醋时，你更接近哪一种？希望 TA 自己看出来；或我更愿意用合适的方式直接告诉 TA。", relationshipTypes: ["ambiguous"] },
    { id: "AMB-EX-04", motherQuestionId: "EX-09", dimension: "expression", text: "有时候你很想问：“我们现在到底算什么？”但你又担心这样会让 TA 有压力。你更接近：", scoreDirection: "reverse", signalTags: ["fear_of_burdening"], relationshipTypes: ["ambiguous"] },
    { id: "AMB-EX-05", motherQuestionId: "EX-06", dimension: "expression", text: "TA 开了一个玩笑，但刚好戳中了你比较在意的地方。TA 看起来并不知道你不舒服。你更可能：", relationshipTypes: ["ambiguous"] },
    { id: "AMB-EX-06", motherQuestionId: "EX-10", dimension: "expression", text: "你最近对这段关系有一点复杂，自己都还没完全想明白。如果 TA 问：“你最近怎么了？”你更可能：", relationshipTypes: ["ambiguous"] },
    { id: "AMB-SP-02", motherQuestionId: "SP-05", dimension: "space_need", text: "你正在忙自己的事情，TA 连续发来了很多消息。你第一感觉更接近：", relationshipTypes: ["ambiguous"] },
    { id: "AMB-SP-03", motherQuestionId: "SP-06", dimension: "space_need", text: "你告诉 TA：“我今天有点累，想自己待一会儿。”TA 回：“好呀，你休息就行。我们没什么问题，等你想聊再找我。”你的感觉：", signalTags: ["autonomy_with_reassurance"], relationshipTypes: ["ambiguous"] },
    { id: "AMB-SP-04", motherQuestionId: "SP-09", dimension: "space_need", text: "你们有两三天没怎么认真聊天，但见面时依然很自然，也没有感觉彼此疏远。你会更倾向认为：", relationshipTypes: ["ambiguous"] },
    { id: "AMB-SP-05", motherQuestionId: "SP-07", dimension: "space_need", text: "你们已经连续十几天每天聊很多。某一天你忽然觉得：“我今天真的不太想聊天。”这时你会：", relationshipTypes: ["ambiguous"] },
    { id: "AMB-ES-02", motherQuestionId: "ES-04", dimension: "emotional_sensitivity", text: "你问 TA：“怎么感觉你今天有点不开心？”TA 笑着说：“没有啊，我很好。”你通常：", relationshipTypes: ["ambiguous"] },
    { id: "AMB-ES-03", motherQuestionId: "ES-07", dimension: "emotional_sensitivity", text: "一次聊天结束以后，你突然感觉 TA 最后那句话有一点不对劲。接下来你更可能：", relationshipTypes: ["ambiguous"] },
    { id: "AMB-ES-04", motherQuestionId: "ES-10", dimension: "emotional_sensitivity", text: "你明显感觉 TA 今天情绪不好。你更接近：", signalTags: ["perceptive_without_personalizing"], relationshipTypes: ["ambiguous"] },
    { id: "AMB-ES-05", motherQuestionId: "ES-05", dimension: "emotional_sensitivity", text: "TA 因为自己的事情明显心情很差。虽然你知道那件事完全和你无关，但你和 TA 聊了一会以后……", signalTags: ["emotional_contagion"], relationshipTypes: ["ambiguous"] },
    { id: "AMB-CU-02", motherQuestionId: "CU-04", dimension: "conflict_urgency", text: "你们正在聊一个让双方都有点不舒服的问题。TA 说：“我们现在都有点上头，明天晚上再聊好吗？我不会消失。”你最接近：", relationshipTypes: ["ambiguous"] },
    { id: "AMB-CU-03", motherQuestionId: "CU-09", dimension: "conflict_urgency", text: "你们因为一件事情发生了明显不愉快。真正让你最难受的是：矛盾本身；还是 TA 在矛盾之后突然很久不回应。", signalTags: ["silence_after_conflict_trigger"], relationshipTypes: ["ambiguous"] },
    { id: "AMB-CU-04", motherQuestionId: "CU-10", dimension: "conflict_urgency", text: "TA 告诉你：“我现在需要两个小时冷静一下，但今晚十点我一定回来继续和你聊。”这会让你：", scoreDirection: "reverse", signalTags: ["needs_reconnection_time"], relationshipTypes: ["ambiguous"] },
    { id: "AMB-CU-05", motherQuestionId: "CU-05", dimension: "conflict_urgency", text: "当你感觉 TA 最近明显在疏远你时，你更容易：", signalTags: ["approach_under_stress"], relationshipTypes: ["ambiguous"] },
    { id: "AMB-RP-02", motherQuestionId: "RP-02", dimension: "repair_orientation", text: "你们对一件事情的看法完全不同。最后双方都不可能完全认同对方。对你来说，更重要的是：", relationshipTypes: ["ambiguous"] },
    { id: "AMB-RP-03", motherQuestionId: "RP-05", dimension: "repair_orientation", text: "TA 做了一件让你比较受伤的事。后来 TA 不只是道歉，还清楚说明自己哪里做错，并且之后真的改变了做法。你通常：", relationshipTypes: ["ambiguous"] },
    { id: "AMB-RP-05", motherQuestionId: "RP-09", dimension: "repair_orientation", text: "同一个让你不舒服的问题已经发生过很多次。每次 TA 都会认真道歉，但之后还是重复发生。你会更接近：", signalTags: ["repeated_pattern_erosion"], relationshipTypes: ["ambiguous"] },
    { id: "AMB-RP-06", motherQuestionId: "RP-10", dimension: "repair_orientation", text: "一次矛盾最后双方说：“好了，不说了，过去就过去了。”和另一种方式：“以后再遇到类似情况，我们具体这样处理。”后者会不会让你更安心？", signalTags: ["concrete_repair_preference"], relationshipTypes: ["ambiguous"] },
  ]),
);

NEW_RELATIONSHIP_QUESTIONS.push(
  ...asLikert([
    { id: "NEW-RN-03", motherQuestionId: "RN-08", dimension: "response_need", text: "TA 最近几天联系变少。后来主动告诉你：“最近工作真的很忙，我不是不想理你，只是状态很差。”如果你能确定 TA 说的是真的：", signalTags: ["reassurance_then_calm"], relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-RN-04", motherQuestionId: "RN-09", dimension: "response_need", text: "你们已经确认关系。双方最近都很忙，一周只能认真见一次。只要你能够明确感觉“我们的关系是稳定的”，你是否能够接受？", scoreDirection: "reverse", relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-RN-05", motherQuestionId: "RN-05", dimension: "response_need", text: "你原本以为周末会一起过。TA 临时告诉你：“朋友约我，我想出去见他们。”你第一感觉更接近：", signalTags: ["priority_sensitivity"], relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-RN-06", motherQuestionId: "RN-10", dimension: "response_need", text: "在恋爱刚开始的阶段，如果只能选一种状态，你更喜欢：每天联系很多，但很少讨论关系本身；或联系没有那么密集，但对方会明确表达“我很认真对待我们”。", signalTags: ["clarity_over_frequency"], relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-EX-02", motherQuestionId: "EX-04", dimension: "expression", text: "最近你感觉自己需要 TA 多陪你一点。你更可能：", relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-EX-03", motherQuestionId: "EX-07", dimension: "expression", text: "当你因为 TA 和别人相处得太亲近而吃醋时，你更接近：希望 TA 自己察觉我为什么不开心；或我会直接告诉 TA 哪件事让我不舒服。", signalTags: ["direct_boundary_expression"], relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-EX-04", motherQuestionId: "EX-09", dimension: "expression", text: "有一个要求你其实很在意，但你担心说出来以后 TA 会觉得“你怎么这么多要求？”你更容易：", scoreDirection: "reverse", signalTags: ["fear_of_burdening"], relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-EX-05", motherQuestionId: "EX-08", dimension: "expression", text: "你们第一次发生比较明显的争执。你感觉自己已经没办法继续冷静讨论。你更可能：", relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-EX-06", motherQuestionId: "EX-10", dimension: "expression", text: "你最近有一点不安，但自己还没有完全想明白原因。如果 TA 问：“是不是我哪里做得不好？”你更可能：", relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-SP-02", motherQuestionId: "SP-04", dimension: "space_need", text: "周末两天你们都有空。TA 希望两天都一起过，而你其实想留半天自己安排。你更接近：", relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-SP-03", motherQuestionId: "SP-05", dimension: "space_need", text: "你正在专心工作、学习或者玩自己的东西。TA 连续发来很多消息，并且希望你马上回。你更接近：", relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-SP-04", motherQuestionId: "SP-06", dimension: "space_need", text: "你告诉 TA：“今天我有点累，想自己待一下。”TA 回：“当然可以，你休息吧。我们之间没什么问题，等你有精神再找我。”你的第一感觉：", signalTags: ["autonomy_with_reassurance"], relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-SP-05", motherQuestionId: "SP-09", dimension: "space_need", text: "你们有一天几乎没怎么聊天。但晚上见面以后，两个人依然非常自然。你更接近：", relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-ES-01", motherQuestionId: "ES-01", dimension: "emotional_sensitivity", text: "TA 平时回你消息会比较热情。今天回复内容还是正常，但明显少了表情、语气词，也更简短。你：", relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-ES-02", motherQuestionId: "ES-04", dimension: "emotional_sensitivity", text: "你们见面时，TA 一直说“我没事。”但说话、表情和动作都和平时不太一样。你更接近：", relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-ES-03", motherQuestionId: "ES-07", dimension: "emotional_sensitivity", text: "第一次明显争吵结束以后，你躺在床上。你更接近：", relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-ES-04", motherQuestionId: "ES-10", dimension: "emotional_sensitivity", text: "你明显感觉 TA 今天情绪不好。但你知道 TA 最近工作或者学习压力很大。你的第一反应：", signalTags: ["perceptive_without_personalizing"], relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-ES-05", motherQuestionId: "ES-05", dimension: "emotional_sensitivity", text: "TA 因为工作上的事情心情特别差。虽然 TA 没有对你发脾气，但整个晚上情绪都很低。你：", signalTags: ["emotional_contagion"], relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-CU-02", motherQuestionId: "CU-04", dimension: "conflict_urgency", text: "争执过程中，TA 说：“我现在真的有点上头，我们两个小时以后继续聊，可以吗？我不会逃避。”你更接近：", relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-CU-03", motherQuestionId: "CU-05", dimension: "conflict_urgency", text: "一次争执之后，你明显感觉 TA 在减少联系。你最自然的反应：", signalTags: ["approach_under_stress"], relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-CU-04", motherQuestionId: "CU-09", dimension: "conflict_urgency", text: "你们第一次吵得比较明显。对你来说，下面哪个更难受：争吵本身；还是争吵以后 TA 突然不回应，也不知道什么时候再说。", signalTags: ["silence_after_conflict_trigger"], relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-CU-05", motherQuestionId: "CU-10", dimension: "conflict_urgency", text: "如果 TA 在争执后明确告诉你：“我需要冷静到晚上十点，十点以后我一定回来继续谈。”你会：", scoreDirection: "reverse", signalTags: ["needs_reconnection_time"], relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-RP-02", motherQuestionId: "RP-02", dimension: "repair_orientation", text: "你们第一次发现彼此对一件很重要的事情看法完全不同。最后可能谁也说服不了谁。你最希望最后达到：", relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-RP-03", motherQuestionId: "RP-05", dimension: "repair_orientation", text: "TA 做了一件让你明显受伤的事。后来 TA 不仅认真道歉，而且之后真的改变了行为。你：", relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
    { id: "NEW-RP-05", motherQuestionId: "RP-10", dimension: "repair_orientation", text: "一次矛盾结束以后，两种结果你更喜欢哪一个？“好了好了，不吵了，我们和好吧。”或“如果以后再遇到这种情况，我们提前这样处理。”", signalTags: ["concrete_repair_preference"], relationshipTypes: ["dating"], relationshipStages: ["new_relationship"] },
  ]),
);

STABLE_QUESTIONS.push(
  ...asLikert([
    { id: "ST-RN-03", motherQuestionId: "RN-08", dimension: "response_need", text: "你们最近都很忙。一周真正能认真相处的时间只有一个晚上，但那几个小时里，TA 很专注，也会认真听你说话。你是否能够因此感觉关系仍然稳定？", signalTags: ["quality_over_quantity"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-RN-04", motherQuestionId: "RN-05", dimension: "response_need", text: "你们一起吃饭、看电视、待在一个空间里很多次，但 TA 经常在看手机、工作或者做自己的事。你更容易感觉：", signalTags: ["presence_without_attention"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-RN-05", motherQuestionId: "RN-07", dimension: "response_need", text: "如果你发现自己总是在为两个人安排时间，而 TA 大多只是“有空就来”，你会：", signalTags: ["investment_imbalance_sensitivity"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-RN-06", motherQuestionId: "RN-09", dimension: "response_need", text: "如果你非常确定彼此感情稳定，即使连续几天都只是简单联系，你通常也能接受。", scoreDirection: "reverse", signalTags: ["stable_without_frequency"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-EX-02", motherQuestionId: "EX-09", dimension: "expression", text: "有一个问题你们以前谈过几次，最近它又发生了。你已经有点不舒服，但又会想：“再提是不是又要吵？”你更接近：", scoreDirection: "reverse", signalTags: ["conflict_avoidance_accumulation"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-EX-03", motherQuestionId: "EX-04", dimension: "expression", text: "你感觉最近两个人相处时间变少。你更可能说：", signalTags: ["specific_need_expression"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-EX-04", motherQuestionId: "EX-07", dimension: "expression", text: "在一起这么久以后，当你不开心时，你更接近哪一种想法？“TA 应该已经足够了解我，应该看得出来。”或“即使在一起很久，我也应该把自己的感受说出来。”", signalTags: ["mind_reading_expectation"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-EX-05", motherQuestionId: "EX-10", dimension: "expression", text: "最近你对这段关系有一点疲惫，但不是想分手，只是觉得很多事情堆在一起。如果 TA 问：“你是不是对我们有意见？”你更可能：", signalTags: ["relationship_fatigue_expression"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-EX-06", motherQuestionId: "EX-08", dimension: "expression", text: "你们在讨论一个已经重复出现很多次的问题。你感觉自己快要失去耐心。你更可能：", relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-SP-02", motherQuestionId: "SP-01", dimension: "space_need", text: "你们工作日都比较忙。到了周末，TA 希望大部分时间都一起过，而你偶尔会想完全自己安排一天。你更接近：", relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-SP-03", motherQuestionId: "SP-04", dimension: "space_need", text: "TA 希望逐渐加入你几乎所有朋友聚会和兴趣活动。你更接近：", signalTags: ["social_autonomy_need"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-SP-04", motherQuestionId: "SP-02", dimension: "space_need", text: "你遇到了一件很糟糕的事情。TA 很想马上陪你分析、安慰、问很多问题，但你其实只想安静一会。你更接近：", relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-SP-05", motherQuestionId: "SP-09", dimension: "space_need", text: "对我来说，一段成熟关系可以允许两个人某些时候各自忙很多天，只要彼此的连接仍然稳定。", relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-ES-01", motherQuestionId: "ES-01", dimension: "emotional_sensitivity", text: "因为已经很熟悉 TA，我通常很快就能感觉到：“今天 TA 跟平时不太一样。”", relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-ES-02", motherQuestionId: "ES-07", dimension: "emotional_sensitivity", text: "TA 今天说了一句很普通的话，但语气让你感觉有一点不对。之后你更可能：", relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-ES-03", motherQuestionId: "ES-10", dimension: "emotional_sensitivity", text: "TA 最近工作压力明显很大，回家以后话也变少。你更容易：", signalTags: ["perceptive_without_personalizing"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-ES-04", motherQuestionId: "ES-05", dimension: "emotional_sensitivity", text: "如果 TA 长期处于低落、焦虑或者烦躁状态，即使没有冲你发火，你自己的情绪也会越来越受影响。", signalTags: ["emotional_load_absorption"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-ES-05", motherQuestionId: "ES-08", dimension: "emotional_sensitivity", text: "如果 TA 并没有说任何不满，但开始减少拥抱、主动分享和共同活动，我通常会比较快察觉到关系氛围变化。", signalTags: ["connection_decline_detection"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-CU-02", motherQuestionId: "CU-10", dimension: "conflict_urgency", text: "TA 说：“我今晚不想继续谈，但明天上午十点我们认真说。”这和 TA 只说“不想谈了。”相比，会不会让你更容易接受？", signalTags: ["needs_reconnection_time"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-CU-03", motherQuestionId: "CU-06", dimension: "conflict_urgency", text: "你很想把问题说清楚，但你也明显感觉双方继续聊下去会说出伤人的话。你更接近：", relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-CU-04", motherQuestionId: "CU-09", dimension: "conflict_urgency", text: "对我来说，矛盾之后长时间互不回应，比争吵本身更难受。", signalTags: ["silence_after_conflict_trigger"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-CU-05", motherQuestionId: "CU-05", dimension: "conflict_urgency", text: "一次争吵以后，两个人都没有联系。即使你觉得主要问题并不在自己，你会不会因为不想关系继续僵着而先主动？", relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-RP-02", motherQuestionId: "RP-06", dimension: "repair_orientation", text: "在一段已经很稳定的关系里，对你来说，“真正修复”更接近：双方终于把情绪说开，并认真道歉；或双方之后真的改变导致问题重复发生的做法。", relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-RP-03", motherQuestionId: "RP-09", dimension: "repair_orientation", text: "一个问题已经重复出现很多次。每次争吵以后你们都能和好，但实际相处方式没有明显变化。你更接近：", signalTags: ["repair_fatigue"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-RP-04", motherQuestionId: "RP-07", dimension: "repair_orientation", text: "当 TA 做了一件让我很失望的事时，我通常仍然能同时记得这段关系里曾经真实存在的好。", relationshipTypes: ["dating"], relationshipStages: ["stable"] },
    { id: "ST-RP-05", motherQuestionId: "RP-08", dimension: "repair_orientation", text: "你回想过去几次矛盾，发现多数时候都是自己先主动缓和、联系或者解决。你的感觉更接近：", signalTags: ["repair_labor_imbalance"], relationshipTypes: ["dating"], relationshipStages: ["stable"] },
  ]),
);

LDR_QUESTIONS.push(
  ...asLikert([
    { id: "LDR-RN-07", motherQuestionId: "RN-05", dimension: "response_need", text: "你们平时每天都有联系。某一天 TA 突然从早到晚几乎没有消息，也没有提前说明。你更接近：", signalTags: ["unexpected_silence_trigger"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-RN-04", motherQuestionId: "RN-03", dimension: "response_need", text: "你们每天都会文字聊天，但连续两周都没有视频或电话。你更接近：", signalTags: ["live_contact_need"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-RN-05", motherQuestionId: "RN-09", dimension: "response_need", text: "如果你非常确定彼此关系稳定，即使某几天只能简单聊天，你通常也可以接受。", scoreDirection: "reverse", signalTags: ["stable_without_high_frequency"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-RN-06", motherQuestionId: "RN-03", dimension: "response_need", text: "TA 临时出去和朋友聚会，没有提前告诉你，晚上才提到。你更接近：", signalTags: ["transparency_need"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-EX-02", motherQuestionId: "EX-01", dimension: "expression", text: "最近总是你主动打电话，而 TA 很少主动提出视频。你更可能：", signalTags: ["contact_labor_expression"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-EX-03", motherQuestionId: "EX-08", dimension: "expression", text: "TA 想视频，但你今天状态非常差，只想一个人待着。你更可能：", relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-EX-04", motherQuestionId: "EX-10", dimension: "expression", text: "你发现 TA 误解了你的一句话，但你自己也还没完全想明白怎么解释。你更可能：", relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-EX-05", motherQuestionId: "EX-04", dimension: "expression", text: "当你明显感觉很久没见，自己已经有点撑不住时，你能否直接提出：“我真的希望我们安排一次见面。”", signalTags: ["meeting_need_expression"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-SP-02", motherQuestionId: "SP-04", dimension: "space_need", text: "即使异地，我仍然希望双方能够保留自己的朋友、兴趣和生活节奏，而不是把大部分空闲都留给视频和聊天。", relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-SP-03", motherQuestionId: "SP-09", dimension: "space_need", text: "我可以接受 TA 几个小时不回消息，而不会自动认为这意味着 TA 在疏远我。", relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-SP-04", motherQuestionId: "SP-04", dimension: "space_need", text: "你们开着视频，各自做自己的事情，几乎没怎么说话。你更接近：", signalTags: ["parallel_presence_preference"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-SP-05", motherQuestionId: "SP-06", dimension: "space_need", text: "TA 告诉你：“今晚我想自己安静一下，不视频了，但我们没什么问题。”你会：", signalTags: ["autonomy_with_reassurance"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-ES-03", motherQuestionId: "ES-07", dimension: "emotional_sensitivity", text: "因为不在同一个地方，你无法真正知道 TA 每天的很多细节。你更接近：", signalTags: ["information_gap_projection"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-ES-04", motherQuestionId: "ES-01", dimension: "emotional_sensitivity", text: "TA 发了一条状态，看起来心情很好，但那一天和你聊天时明显很冷淡。你更容易：", signalTags: ["public_private_affect_gap"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-ES-05", motherQuestionId: "ES-10", dimension: "emotional_sensitivity", text: "即使 TA 的状态变差，我通常也能先考虑工作、学习、家庭等原因，而不是马上认为“是不是我们之间有问题”。", signalTags: ["perceptive_without_personalizing"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-CU-01", motherQuestionId: "CU-01", dimension: "conflict_urgency", text: "你们正在文字聊天时发生明显矛盾。你更希望：", relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-CU-02", motherQuestionId: "CU-09", dimension: "conflict_urgency", text: "视频争吵时，TA 突然说：“我现在不想说了。”然后挂断。你更接近：", signalTags: ["abrupt_disconnect_trigger"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-CU-03", motherQuestionId: "CU-10", dimension: "conflict_urgency", text: "TA 说：“我们两个现在情绪都不好，我先休息，明天北京时间晚上九点一定给你打电话。”这会让你：", signalTags: ["needs_reconnection_time"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-CU-04", motherQuestionId: "CU-04", dimension: "conflict_urgency", text: "你们有明显时差。你现在非常想解决问题，但 TA 那边已经凌晨两点。你更接近：", signalTags: ["urgency_over_context"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-CU-05", motherQuestionId: "CU-09", dimension: "conflict_urgency", text: "异地时，矛盾以后超过一天没有任何联系，会让我明显比普通恋爱里的“冷静一晚”更难受。", signalTags: ["distance_amplified_silence"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-RP-02", motherQuestionId: "RP-04", dimension: "repair_orientation", text: "矛盾以后，如果双方能一起安排下一次见面，我通常会明显更有“我们还是在往前走”的感觉。", signalTags: ["future_meeting_repairs_security"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-RP-03", motherQuestionId: "RP-10", dimension: "repair_orientation", text: "比起只说“别生气了。”你更希望听到：“以后如果我忙到没法联系，我提前告诉你。”", signalTags: ["concrete_repair_preference"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-RP-04", motherQuestionId: "RP-09", dimension: "repair_orientation", text: "TA 已经几次因为忙突然失联，每次后来都会道歉。你更接近：", signalTags: ["repeated_absence_erosion"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
    { id: "LDR-RP-05", motherQuestionId: "RP-08", dimension: "repair_orientation", text: "回想过去几次见面，大部分都是你主动查时间、买票、安排计划。你的感觉：", signalTags: ["meeting_labor_imbalance"], relationshipTypes: ["dating"], relationshipStages: ["long_distance"] },
  ]),
);

MARRIED_QUESTIONS.push(
  ...asLikert([
    { id: "MAR-RN-02", motherQuestionId: "RN-03", dimension: "response_need", text: "即使已经在一起很多年，我仍然希望 TA 偶尔主动问：“你最近累不累？”“你心情怎么样？”“有什么我能帮你的吗？”", signalTags: ["ongoing_emotional_checkin_need"], relationshipTypes: ["long_term"] },
    { id: "MAR-RN-03", motherQuestionId: "RN-03", dimension: "response_need", text: "你们很少再说“想你”“爱你”，但 TA 会每天做饭、接送、处理家里的事情。你更接近：", signalTags: ["care_action_vs_affection_expression"], relationshipTypes: ["long_term"] },
    { id: "MAR-RN-04", motherQuestionId: "RN-05", dimension: "response_need", text: "TA 在做重要安排时，例如换工作、出差、重大支出，常常先自己决定，再告诉你。你更接近：", signalTags: ["consultation_need"], relationshipTypes: ["long_term"] },
    { id: "MAR-RN-05", motherQuestionId: "RN-05", dimension: "response_need", text: "当工作、孩子、父母和各种家庭事务都很忙时，我仍然需要感觉自己首先是 TA 的伴侣，而不只是共同解决问题的人。", signalTags: ["partner_identity_need"], relationshipTypes: ["long_term"] },
    { id: "MAR-EX-02", motherQuestionId: "EX-01", dimension: "expression", text: "有一些家务或生活习惯你已经不舒服很久，但每次都觉得“也不是什么大事”。你更可能：", signalTags: ["resentment_accumulation_risk"], relationshipTypes: ["long_term"] },
    { id: "MAR-EX-03", motherQuestionId: "EX-03", dimension: "expression", text: "你最近感觉自己承担了太多事情，但又担心说出来像是在“算账”。你更接近：", signalTags: ["burden_expression_skill"], relationshipTypes: ["long_term"] },
    { id: "MAR-EX-04", motherQuestionId: "EX-07", dimension: "expression", text: "对涉及家庭的重要决定，我能够明确表达“我不同意”，而不需要通过冷淡、讽刺或沉默让对方猜。", relationshipTypes: ["long_term"] },
    { id: "MAR-EX-05", motherQuestionId: "EX-10", dimension: "expression", text: "你感觉这段关系最近有点变远，但没有发生某件特别严重的事情。你更可能：", signalTags: ["relationship_state_expression"], relationshipTypes: ["long_term"] },
    { id: "MAR-SP-02", motherQuestionId: "SP-04", dimension: "space_need", text: "我认为长期伴侣应该允许彼此拥有一些完全不同的兴趣、朋友和活动，而不是所有生活都高度绑定。", signalTags: ["long_term_autonomy_need"], relationshipTypes: ["long_term"] },
    { id: "MAR-SP-03", motherQuestionId: "SP-02", dimension: "space_need", text: "你下班后非常累，TA 却立刻想聊很多家庭事务。你更接近：", signalTags: ["transition_space_need"], relationshipTypes: ["long_term"] },
    { id: "MAR-SP-04", motherQuestionId: "SP-04", dimension: "space_need", text: "对我来说，“夫妻 / 伴侣之间没有隐私”并不是理想状态。", signalTags: ["privacy_boundary_long_term"], relationshipTypes: ["long_term"] },
    { id: "MAR-SP-05", motherQuestionId: "SP-04", dimension: "space_need", text: "TA 想单独和朋友旅行几天，而你不参与。你更接近：", signalTags: ["independent_experience_tolerance"], relationshipTypes: ["long_term"] },
    { id: "MAR-ES-02", motherQuestionId: "ES-05", dimension: "emotional_sensitivity", text: "TA 连续几周因为工作或家庭压力情绪不好。即使 TA 没有直接冲你发火，你自己的状态也会：", signalTags: ["household_emotional_load"], relationshipTypes: ["long_term"] },
    { id: "MAR-ES-03", motherQuestionId: "ES-10", dimension: "emotional_sensitivity", text: "即使 TA 最近明显变得安静，我通常也能先区分这是 TA 自己的压力，还是我们之间的问题。", signalTags: ["long_term_contextual_attribution"], relationshipTypes: ["long_term"] },
    { id: "MAR-ES-04", motherQuestionId: "ES-04", dimension: "emotional_sensitivity", text: "TA 没有抱怨，但你发现 TA 最近总是很累、记性变差、容易烦躁。你更接近：", signalTags: ["invisible_burden_detection"], relationshipTypes: ["long_term"] },
    { id: "MAR-ES-05", motherQuestionId: "ES-05", dimension: "emotional_sensitivity", text: "如果 TA 心情不好，全家的氛围都会不自觉围着 TA 的状态变化。", signalTags: ["emotion_dominates_household"], relationshipTypes: ["long_term"] },
    { id: "MAR-CU-02", motherQuestionId: "CU-01", dimension: "conflict_urgency", text: "这个问题你们已经争论了很多次。再次发生时，你更容易：", signalTags: ["repetitive_conflict_urgency"], relationshipTypes: ["long_term"] },
    { id: "MAR-CU-04", motherQuestionId: "CU-09", dimension: "conflict_urgency", text: "对我来说，长期伴侣之间几天不说话，比直接争吵更消耗关系。", signalTags: ["long_term_silence_cost"], relationshipTypes: ["long_term"] },
    { id: "MAR-CU-05", motherQuestionId: "CU-10", dimension: "conflict_urgency", text: "TA 说：“我们现在都很累。明天晚上孩子睡了以后，我们专门留半小时谈这件事。”你会：", signalTags: ["scheduled_reconnection_works"], relationshipTypes: ["long_term"] },
    { id: "MAR-RP-06", motherQuestionId: "RP-09", dimension: "repair_orientation", text: "如果同一个问题每次都能和好，但实际做法一直没有改变，我会逐渐觉得“和好”本身已经不够。", signalTags: ["repair_without_change_fatigue"], relationshipTypes: ["long_term"] },
    { id: "MAR-RP-02", motherQuestionId: "RP-08", dimension: "repair_orientation", text: "回想过去很多次矛盾，几乎都是你先开口、先缓和、先提出解决方法。你更接近：", signalTags: ["relationship_maintenance_imbalance"], relationshipTypes: ["long_term"] },
    { id: "MAR-RP-03", motherQuestionId: "RP-10", dimension: "repair_orientation", text: "对长期关系来说，我越来越认为真正的修复应该包括：“以后具体怎么避免同样的问题再次发生。”", signalTags: ["structural_repair_need"], relationshipTypes: ["long_term"] },
    { id: "MAR-RP-04", motherQuestionId: "RP-07", dimension: "repair_orientation", text: "即使 TA 做了一件让我很失望的事，我通常仍然能同时看到这段关系里其他真实存在的好。", relationshipTypes: ["long_term"] },
    { id: "MAR-RP-05", motherQuestionId: "RP-04", dimension: "repair_orientation", text: "如果同一个问题已经持续几年，而且每次都没有明显改变，我会：", signalTags: ["chronic_pattern_exhaustion"], relationshipTypes: ["long_term"] },
  ]),
);

TENSE_QUESTIONS.push(
  ...asLikert([
    { id: "TEN-RN-02", motherQuestionId: "RN-08", dimension: "response_need", text: "当 TA 对某个让你不安的行为做出合理解释以后，你通常：", signalTags: ["reassurance_no_longer_restores_security"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-RN-03", motherQuestionId: "RN-05", dimension: "response_need", text: "最近即使 TA 仍然和我保持联系，我有时还是会觉得：“TA 好像已经没有真正把我的感受放在心上。”", signalTags: ["emotional_neglect_perception"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-RN-04", motherQuestionId: "RN-07", dimension: "response_need", text: "如果你停下主动联系、安排和沟通一段时间，你觉得这段关系会：", signalTags: ["relationship_depends_on_one_partner"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-RN-05", motherQuestionId: "RN-03", dimension: "response_need", text: "即使 TA 最近做了一些关心我的事情，我有时也很难真正感受到“被爱”。", signalTags: ["care_no_longer_lands"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-EX-02", motherQuestionId: "EX-10", dimension: "expression", text: "以前发生误会时，你还会认真解释自己。现在类似事情发生，你更接近：", signalTags: ["self_explanation_withdrawal"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-EX-03", motherQuestionId: "EX-03", dimension: "expression", text: "最近我们谈关系问题时，很容易从“我现在有什么感受”变成“你总是怎样”“你从来怎样”。", signalTags: ["complaint_to_character_attack"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-EX-04", motherQuestionId: "EX-01", dimension: "expression", text: "你明明有一个重要问题想谈，但想到“可能又要吵起来”，你更容易：", signalTags: ["topic_avoidance_due_to_conflict"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-EX-05", motherQuestionId: "EX-01", dimension: "expression", text: "最近你们还能讨论吃饭、工作、安排这些事情，但很少真正谈：“我最近在这段关系里是什么感觉。”", signalTags: ["functional_communication_only"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-SP-02", motherQuestionId: "SP-02", dimension: "space_need", text: "当你们一整天都没有联系时，我有时会觉得比聊天的时候更轻松。", signalTags: ["relief_in_disconnection"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-SP-03", motherQuestionId: "SP-04", dimension: "space_need", text: "最近我更容易想象：“如果以后没有 TA，我自己的生活会是什么样。”", signalTags: ["life_without_partner_imagining"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-SP-04", motherQuestionId: "SP-02", dimension: "space_need", text: "以前发生什么事情我很自然会告诉 TA，现在有些事情我已经不太想分享。", signalTags: ["sharing_withdrawal"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-SP-05", motherQuestionId: "SP-02", dimension: "space_need", text: "最近我会主动减少一些聊天、见面、拥抱或其他亲密互动，因为我没有以前那么想靠近。", signalTags: ["active_connection_withdrawal"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-ES-06", motherQuestionId: "ES-07", dimension: "emotional_sensitivity", text: "最近 TA 一些原本普通的行为，我越来越容易理解成“不在乎”“敷衍”或者“故意”。", signalTags: ["negative_interpretation_bias"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-ES-02", motherQuestionId: "ES-04", dimension: "emotional_sensitivity", text: "TA 突然对你特别好。你的第一反应：", signalTags: ["goodwill_suspicion"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-ES-03", motherQuestionId: "ES-05", dimension: "emotional_sensitivity", text: "这段关系已经消耗了我很多情绪，以至于有些时候我没有力气再去理解 TA 为什么那样做。", signalTags: ["empathy_exhaustion"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-ES-04", motherQuestionId: "ES-07", dimension: "emotional_sensitivity", text: "最近回想这段关系时，我更容易想起失望和争吵，而不是以前那些好的部分。", signalTags: ["negative_memory_dominance"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-ES-05", motherQuestionId: "ES-01", dimension: "emotional_sensitivity", text: "和 TA 相处时，我越来越容易提前担心：“等一下是不是又要发生什么问题。”", signalTags: ["relationship_hypervigilance"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-CU-02", motherQuestionId: "CU-01", dimension: "conflict_urgency", text: "现在一个原本很小的问题，也比以前更容易迅速升级成一次严重争吵。", signalTags: ["conflict_escalation_speed"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-CU-03", motherQuestionId: "CU-01", dimension: "conflict_urgency", text: "你们现在发生新的矛盾时，经常会把以前没有真正解决的事情一起翻出来。", signalTags: ["unresolved_history_intrusion"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-CU-04", motherQuestionId: "CU-04", dimension: "conflict_urgency", text: "TA 在争吵时说：“以后再说。”你现在更容易认为：", signalTags: ["pause_lost_credibility"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-CU-05", motherQuestionId: "CU-01", dimension: "conflict_urgency", text: "发生矛盾以后，我现在最强烈的感觉有时已经不是“我要解决”，而是“我真的不想再经历一次”。", signalTags: ["conflict_resolution_exhaustion"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-RP-02", motherQuestionId: "RP-04", dimension: "repair_orientation", text: "即使 TA 说会改变，我现在也很难相信事情真的会不同。", signalTags: ["change_credibility_loss"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-RP-03", motherQuestionId: "RP-05", dimension: "repair_orientation", text: "如果 TA 不只是道歉，而是连续几个月真的改变了导致你受伤的行为，你觉得自己的信任：", signalTags: ["trust_rebuildability"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-RP-04", motherQuestionId: "RP-08", dimension: "repair_orientation", text: "最近这段关系的修复，主要依靠我一个人在推动。", signalTags: ["one_sided_repair"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-RP-05", motherQuestionId: "RP-10", dimension: "repair_orientation", text: "你们过去很多次“和好”，其实更像是不再提问题，而不是问题真的有了新的处理方式。", signalTags: ["pseudo_repair"], relationshipStages: ["tense", "considering_future"] },
    { id: "TEN-RP-06", motherQuestionId: "RP-02", dimension: "repair_orientation", text: "即使我现在很失望，我仍然有兴趣理解：“TA 为什么会变成现在这样？”", signalTags: ["curiosity_about_partner_remaining"], relationshipStages: ["tense", "considering_future"] },
  ]),
);

FRIEND_QUESTIONS.push(
  ...asLikert([
    { id: "FR-RN-02", motherQuestionId: "RN-09", dimension: "response_need", text: "即使和一个真正重要的朋友很久不联系，我通常仍然可以相信彼此的关系没有变化。", signalTags: ["low_frequency_friendship_security"], relationshipTypes: ["friend"] },
    { id: "FR-RN-03", motherQuestionId: "RN-07", dimension: "response_need", text: "你每次约 TA，TA 大多会来，也很开心，但 TA 几乎从不主动约你。你更接近：", signalTags: ["friendship_maintenance_imbalance"], relationshipTypes: ["friend"] },
    { id: "FR-RN-04", motherQuestionId: "RN-02", dimension: "response_need", text: "一个过去经常秒回你的朋友，现在经常隔很久才回复，但内容仍然认真。你更接近：", signalTags: ["friendship_change_sensitivity"], relationshipTypes: ["friend"] },
    { id: "FR-RN-05", motherQuestionId: "RN-03", dimension: "response_need", text: "对我来说，朋友之间不需要天天联系，但我希望在重要的时候能够感觉“TA 会想到我”。", signalTags: ["important_moment_recall_need"], relationshipTypes: ["friend"] },
    { id: "FR-EX-02", motherQuestionId: "EX-01", dimension: "expression", text: "TA 连续很长一段时间几乎每次找你，都是因为自己有情绪和烦恼。你更接近：", signalTags: ["emotional_support_boundary"], relationshipTypes: ["friend"] },
    { id: "FR-EX-03", motherQuestionId: "EX-04", dimension: "expression", text: "即使 TA 很需要倾诉，如果我自己已经没有精力，我能够告诉 TA：“我现在状态不太够，晚一点再陪你聊。”", signalTags: ["support_capacity_expression"], relationshipTypes: ["friend"] },
    { id: "FR-EX-04", motherQuestionId: "EX-01", dimension: "expression", text: "TA 平时很少联系你，但一遇到问题就会来找你倾诉或求助。你更接近：", signalTags: ["utility_friendship_perception"], relationshipTypes: ["friend"] },
    { id: "FR-EX-05", motherQuestionId: "EX-05", dimension: "expression", text: "对我来说，真正亲近的朋友不应该只在难过时找彼此，也应该愿意分享普通的小事和开心的事情。", signalTags: ["positive_sharing_need"], relationshipTypes: ["friend"] },
    { id: "FR-TR-01", motherQuestionId: "RP-05", dimension: "repair_orientation", text: "你告诉朋友一件很私人的事情，并明确说“不要告诉别人”。后来你发现 TA 告诉了另一个共同朋友。你更接近：", signalTags: ["confidentiality_breach_sensitivity"], relationshipTypes: ["friend"] },
    { id: "FR-TR-02", motherQuestionId: "SP-04", dimension: "space_need", text: "即使关系很亲近，我也能接受朋友有一些完全不告诉我的事情。", signalTags: ["friend_privacy_tolerance"], relationshipTypes: ["friend"] },
    { id: "FR-TR-03", motherQuestionId: "RN-03", dimension: "response_need", text: "TA 知道一个共同朋友的隐私，但拒绝告诉你。你更接近：", signalTags: ["friend_confidentiality_vs_exclusivity"], relationshipTypes: ["friend"] },
    { id: "FR-TR-04", motherQuestionId: "ES-07", dimension: "emotional_sensitivity", text: "如果我发现一个好朋友曾在别人面前说过对我的真实不满，即使内容不是特别严重，我也会明显在意。", signalTags: ["behind_back_feedback_sensitivity"], relationshipTypes: ["friend"] },
    { id: "FR-TR-05", motherQuestionId: "EX-07", dimension: "expression", text: "朋友做了一件你明显不认同的事，你更认可：站在朋友这边最重要；或真正的朋友也应该敢于说“我觉得你这次做得不对”。", signalTags: ["loyalty_vs_honesty_model"], relationshipTypes: ["friend"] },
    { id: "FR-JE-01", motherQuestionId: "RN-07", dimension: "response_need", text: "你的好朋友最近认识了一个新朋友，两个人变得非常亲近。你更接近：", signalTags: ["friend_replacement_sensitivity"], relationshipTypes: ["friend"] },
    { id: "FR-JE-02", motherQuestionId: "RN-05", dimension: "response_need", text: "以前你们经常一起参加某类活动。最近 TA 开始经常和另一群人去，却很少再问你。你更接近：", signalTags: ["social_exclusion_sensitivity"], relationshipTypes: ["friend"] },
    { id: "FR-JE-03", motherQuestionId: "SP-04", dimension: "space_need", text: "即使一个人是我最好的朋友，我也认为 TA 可以同时拥有其他非常亲近的朋友。", signalTags: ["nonexclusive_friendship_tolerance"], relationshipTypes: ["friend"] },
    { id: "FR-JE-04", motherQuestionId: "RN-03", dimension: "response_need", text: "对我来说，“最好的朋友”这个位置应该具有一定特殊性，而不是完全可以同时有很多人。", signalTags: ["best_friend_exclusivity_need"], relationshipTypes: ["friend"] },
    { id: "FR-JE-05", motherQuestionId: "ES-01", dimension: "emotional_sensitivity", text: "TA 和别人出去玩时经常发很多照片，但和你见面时几乎不发。你更接近：", signalTags: ["friend_public_display_comparison"], relationshipTypes: ["friend"] },
    { id: "FR-LS-01", motherQuestionId: "SP-04", dimension: "space_need", text: "你们以前生活节奏很像。现在一个结婚带孩子，一个还是单身；或者一个创业很忙，一个生活比较自由。你更接近：", signalTags: ["life_stage_adaptation_need"], relationshipTypes: ["friend"] },
    { id: "FR-LS-02", motherQuestionId: "RP-04", dimension: "repair_orientation", text: "如果一个老朋友和我的生活已经越来越不同，共同话题变少，我仍然可以通过对彼此的关心维持深度友情。", signalTags: ["friendship_beyond_shared_context"], relationshipTypes: ["friend"] },
    { id: "FR-LS-03", motherQuestionId: "RN-07", dimension: "response_need", text: "一个曾经很亲近的朋友进入恋爱、婚姻或育儿阶段以后，联系明显减少。你更接近：", signalTags: ["life_transition_replacement_feeling"], relationshipTypes: ["friend"] },
    { id: "FR-LS-04", motherQuestionId: "SP-04", dimension: "space_need", text: "你们过去经济状况差不多，现在一方收入明显高很多，消费方式也完全不同。你更接近：", signalTags: ["economic_gap_friendship_effect"], relationshipTypes: ["friend"] },
    { id: "FR-LS-05", motherQuestionId: "RP-02", dimension: "repair_orientation", text: "老朋友之间，即使彼此的价值观这些年发生很大变化，也不代表一定不能继续做重要朋友。", signalTags: ["value_difference_tolerance"], relationshipTypes: ["friend"] },
    { id: "FR-BD-01", motherQuestionId: "SP-04", dimension: "space_need", text: "一个很好的朋友突然向你借一笔对你来说不算小的钱。你更接近：", signalTags: ["friend_money_boundary"], relationshipTypes: ["friend"] },
    { id: "FR-BD-02", motherQuestionId: "RP-05", dimension: "repair_orientation", text: "TA 借你的钱已经超过约定时间，但一直没有主动解释。你更接近：", signalTags: ["financial_reliability_importance"], relationshipTypes: ["friend"] },
    { id: "FR-BD-03", motherQuestionId: "SP-04", dimension: "space_need", text: "真正的朋友可以互相帮忙，但不意味着只要对方开口，我就必须答应。", signalTags: ["help_boundary_strength"], relationshipTypes: ["friend"] },
    { id: "FR-BD-04", motherQuestionId: "EX-04", dimension: "expression", text: "TA 临时请你帮一个很麻烦的忙，但你真的没有时间。你更可能：", signalTags: ["friend_refusal_capacity"], relationshipTypes: ["friend"] },
    { id: "FR-BD-05", motherQuestionId: "RP-08", dimension: "repair_orientation", text: "如果一段友情长期只有一方提供时间、资源、接送、帮忙，而另一方很少回馈，我会逐渐觉得关系失衡。", signalTags: ["practical_support_imbalance"], relationshipTypes: ["friend"] },
    { id: "FR-CU-06", motherQuestionId: "CU-05", dimension: "conflict_urgency", text: "你和一个很重要的朋友发生明显矛盾。即使你觉得自己没有做错主要部分，你会：", signalTags: ["friend_repair_initiative"], relationshipTypes: ["friend"] },
    { id: "FR-CU-02", motherQuestionId: "RN-03", dimension: "response_need", text: "越是认识很久的朋友做出让我失望的事情，我越容易觉得“你应该比别人更懂我”。", signalTags: ["history_based_expectation"], relationshipTypes: ["friend"] },
    { id: "FR-CU-03", motherQuestionId: "RP-04", dimension: "repair_orientation", text: "一段真正重要的友情可以经历严重分歧，只要双方仍然有尊重和修复意愿。", signalTags: ["friendship_conflict_resilience"], relationshipTypes: ["friend"] },
    { id: "FR-CU-04", motherQuestionId: "CU-09", dimension: "conflict_urgency", text: "吵架以后 TA 一周都不联系，也没有说明是否还想解决。你更接近：", signalTags: ["friend_silence_cost"], relationshipTypes: ["friend"] },
    { id: "FR-CU-05", motherQuestionId: "RP-10", dimension: "repair_orientation", text: "对朋友之间的严重矛盾来说，仅仅恢复正常聊天，并不等于问题真的已经修复。", signalTags: ["friend_structural_repair_need"], relationshipTypes: ["friend"] },
    { id: "FR-OLD-01", motherQuestionId: "ES-01", dimension: "emotional_sensitivity", text: "有时候我们以为自己很了解一个老朋友，其实了解的可能只是很多年前的 TA。", signalTags: ["old_friend_update_awareness"], relationshipTypes: ["friend"] },
    { id: "FR-OLD-02", motherQuestionId: "RP-04", dimension: "repair_orientation", text: "如果一个老朋友这些年兴趣、生活方式甚至很多观点都改变了，我仍然愿意重新认识现在的 TA。", signalTags: ["friend_change_acceptance"], relationshipTypes: ["friend"] },
    { id: "FR-OLD-03", motherQuestionId: "ES-07", dimension: "emotional_sensitivity", text: "你发现自己现在想到这段友情时，最怀念的往往是很多年前一起经历的事情，而不是现在的相处。你更接近：", signalTags: ["past_friendship_attachment"], relationshipTypes: ["friend"] },
    { id: "FR-OLD-04", motherQuestionId: "RN-09", dimension: "response_need", text: "如果我们很久没见，但每次真正见面仍然很自然、很真诚，我不会仅仅因为联系少就认为友情已经变淡。", signalTags: ["distance_vs_connection_separation"], relationshipTypes: ["friend"] },
    { id: "FR-OLD-05", motherQuestionId: "RN-05", dimension: "response_need", text: "你们已经很久没联系。终于见面以后，却发现两个人都在努力找话题，关系明显不像以前自然。你更接近：", signalTags: ["connection_decline_recognition"], relationshipTypes: ["friend"] },
  ]),
);

LIFE_STAGE_QUESTIONS.push(
  ...asLikert([
    { id: "Y18-RN-02", motherQuestionId: "RN-05", dimension: "response_need", text: "周末 TA 原本说可能和你见面，后来临时决定和同学、室友或朋友出去。你更接近：", ageBands: ["18_24"], lifeStages: ["student", "early_career"] },
    { id: "Y18-CU-01", motherQuestionId: "CU-04", dimension: "conflict_urgency", text: "晚上你们因为聊天里的误会吵起来，但第二天一早双方都有课或要上班。TA 说：“我们先睡，明天中午一定说清楚。”你更接近：", ageBands: ["18_24"], lifeStages: ["student", "early_career"] },
    { id: "Y18-RP-01", motherQuestionId: "RP-10", dimension: "repair_orientation", text: "你们因为“回复慢”吵了一次。TA 之后说：“以后如果我要忙几个小时，我提前告诉你。”这会让你：", signalTags: ["concrete_repair_preference"], ageBands: ["18_24"], lifeStages: ["student", "early_career"] },
    { id: "Y25-RN-02", motherQuestionId: "RN-03", dimension: "response_need", text: "TA 很少说“想你”“爱你”，但会接你下班、帮你解决事情、记得你重要安排。你更接近：", ageBands: ["25_34"], lifeStages: ["early_career", "career_intensive", "dual_career"] },
    { id: "Y25-ES-01", motherQuestionId: "ES-10", dimension: "emotional_sensitivity", text: "TA 最近工作压力很大，回消息明显变少。你更接近：", signalTags: ["perceptive_without_personalizing"], ageBands: ["25_34"], lifeStages: ["early_career", "career_intensive", "dual_career"] },
    { id: "Y25-RP-01", motherQuestionId: "RP-06", dimension: "repair_orientation", text: "TA 因为工作忙，已经连续几次临时取消约会。对你来说，更重要的是：TA 每次非常认真道歉；或 TA 以后提前安排时间，不再反复发生。", signalTags: ["behavior_change_required"], ageBands: ["25_34"], lifeStages: ["early_career", "career_intensive", "dual_career"] },
    { id: "Y35-RN-02", motherQuestionId: "RN-03", dimension: "response_need", text: "TA 每天在处理工作和家庭事情，也承担不少责任，但很少真正问你：“你最近累不累？”你：", ageBands: ["35_44"], lifeStages: ["parent_infant", "parent_school_age", "caregiver_for_parents", "dual_career"] },
    { id: "Y35-EX-01", motherQuestionId: "EX-03", dimension: "expression", text: "最近你觉得家庭负担分配有点不公平，但你担心一说又变成：“谁做得更多”的争吵。你更可能：", scoreDirection: "reverse", ageBands: ["35_44"], lifeStages: ["parent_infant", "parent_school_age", "caregiver_for_parents", "dual_career"] },
    { id: "Y35-RP-01", motherQuestionId: "RP-10", dimension: "repair_orientation", text: "你们过去经常因为家务分工争吵。这次双方决定：“以后固定把某几项完全交给 TA，另外几项完全由你负责。”你会觉得：", signalTags: ["concrete_repair_preference"], ageBands: ["35_44"], lifeStages: ["parent_infant", "parent_school_age", "caregiver_for_parents", "dual_career"] },
    { id: "Y45-RN-02", motherQuestionId: "RN-07", dimension: "response_need", text: "随着工作、孩子或家庭角色变化，TA 开始把更多时间放在自己的兴趣、朋友或活动上。你：", ageBands: ["45_plus"], lifeStages: ["empty_nest", "career_transition", "caregiver_for_parents"] },
    { id: "Y45-EX-01", motherQuestionId: "EX-01", dimension: "expression", text: "有一个生活习惯你已经忍了很多年。以前觉得不值得吵，现在却越来越难受。你更可能：", ageBands: ["45_plus"], lifeStages: ["empty_nest", "career_transition", "caregiver_for_parents"] },
    { id: "Y45-ES-01", motherQuestionId: "ES-10", dimension: "emotional_sensitivity", text: "TA 最近变得比较安静，也开始关注健康、工作变化或父母养老。你更接近：", signalTags: ["perceptive_without_personalizing"], ageBands: ["45_plus"], lifeStages: ["empty_nest", "career_transition", "caregiver_for_parents"] },
  ], "life_stage"),
);

// ========== 汇总导出 ==========
export const ALL_SCENARIO_QUESTIONS: Question[] = [
  ...AMBIGUOUS_QUESTIONS,
  ...NEW_RELATIONSHIP_QUESTIONS,
  ...STABLE_QUESTIONS,
  ...LDR_QUESTIONS,
  ...MARRIED_QUESTIONS,
  ...TENSE_QUESTIONS,
  ...FRIEND_QUESTIONS,
  ...LIFE_STAGE_QUESTIONS,
];
