// =====================================================
// 人格测试 — 30 张月相卡数据
// 来源：C_卡片元数据_30张.csv（2026-09-13）
// 类型 PersonalityCard 集中在 types.ts 定义
// 渲染：PNG 在 public/personality/cards/{id}.png
// 匹配：matchCards() 与用户向量做余弦相似度
// =====================================================

import type { PersonalityCard } from "./types";

export const PERSONALITY_CARDS: readonly PersonalityCard[] = [
  {
    id: 'P01',
    type: '主',
    no: 1,
    name: '暗礁无声',
    key: '沉底',
    line: '你低调的存在，是别人看不见的那块支点。',
    phase: '朔',
    phase_en: 'NEW MOON',
    vec: [50, 50, 50, 50, 85, 15],
    poles: 'S↑ E↓',
    between: '',
    png_path: '/personality/cards/P01.png',
  },
  {
    id: 'P02',
    type: '主',
    no: 2,
    name: '星火未燎',
    key: '初燃',
    line: '再小的一个动作，也可以点燃后来的一整片天。',
    phase: '蛾眉',
    phase_en: 'WAXING CRESCENT',
    vec: [15, 50, 50, 50, 50, 15],
    poles: 'G↓ E↓',
    between: '',
    png_path: '/personality/cards/P02.png',
  },
  {
    id: 'P03',
    type: '主',
    no: 3,
    name: '微光不争',
    key: '照暗',
    line: '你不必大声，也能照到别人没注意的那个角落。',
    phase: '蛾眉',
    phase_en: 'WAXING CRESCENT',
    vec: [50, 50, 15, 50, 50, 85],
    poles: 'I↓ E↑',
    between: '',
    png_path: '/personality/cards/P03.png',
  },
  {
    id: 'P04',
    type: '主',
    no: 4,
    name: '先行探路',
    key: '知远',
    line: '你不必站在最前面，路总是你先看见的。',
    phase: '上弦',
    phase_en: 'FIRST QUARTER',
    vec: [50, 15, 50, 85, 50, 50],
    poles: 'X↓ F↑',
    between: '',
    png_path: '/personality/cards/P04.png',
  },
  {
    id: 'P05',
    type: '主',
    no: 5,
    name: '静观一室',
    key: '见全',
    line: '你说得很少，但你把整间屋子都看完了。',
    phase: '上弦',
    phase_en: 'FIRST QUARTER',
    vec: [15, 15, 50, 50, 50, 50],
    poles: 'G↓ X↓',
    between: '',
    png_path: '/personality/cards/P05.png',
  },
  {
    id: 'P06',
    type: '主',
    no: 6,
    name: '解缆离岸',
    key: '不回',
    line: '解缆的时候你很慢，但一旦离岸，就不会回头。',
    phase: '上弦',
    phase_en: 'FIRST QUARTER',
    vec: [50, 85, 50, 85, 50, 50],
    poles: 'X↑ F↑',
    between: '',
    png_path: '/personality/cards/P06.png',
  },
  {
    id: 'P07',
    type: '主',
    no: 7,
    name: '涉川不止',
    key: '在途',
    line: '你不太提以后要去哪，但地图上的空白一直在勾你。',
    phase: '盈凸',
    phase_en: 'WAXING GIBBOUS',
    vec: [15, 50, 50, 15, 50, 50],
    poles: 'G↓ F↓',
    between: '',
    png_path: '/personality/cards/P07.png',
  },
  {
    id: 'P08',
    type: '主',
    no: 8,
    name: '守夜到明',
    key: '甘后',
    line: '只要是值得的人，你甘愿排在第二位。',
    phase: '盈凸',
    phase_en: 'WAXING GIBBOUS',
    vec: [50, 50, 85, 50, 15, 50],
    poles: 'I↑ S↓',
    between: '',
    png_path: '/personality/cards/P08.png',
  },
  {
    id: 'P09',
    type: '主',
    no: 9,
    name: '定盘在心',
    key: '自主',
    line: '你不是不需要别人，只是习惯先听自己的那句。',
    phase: '盈凸',
    phase_en: 'WAXING GIBBOUS',
    vec: [50, 85, 50, 50, 15, 50],
    poles: 'X↑ S↓',
    between: '',
    png_path: '/personality/cards/P09.png',
  },
  {
    id: 'P10',
    type: '主',
    no: 10,
    name: '破晓即行',
    key: '先动',
    line: '你不等天亮，你自己就是天亮。',
    phase: '望',
    phase_en: 'FULL MOON',
    vec: [50, 50, 50, 15, 50, 85],
    poles: 'F↓ E↑',
    between: '',
    png_path: '/personality/cards/P10.png',
  },
  {
    id: 'P11',
    type: '主',
    no: 11,
    name: '织网相连',
    key: '结缘',
    line: '你能让几个完全不同的人，在同一个屋顶下各自舒服。',
    phase: '望',
    phase_en: 'FULL MOON',
    vec: [85, 85, 50, 50, 50, 50],
    poles: 'G↑ X↑',
    between: '',
    png_path: '/personality/cards/P11.png',
  },
  {
    id: 'P12',
    type: '主',
    no: 12,
    name: '自造其光',
    key: '不群',
    line: '别人走过的路，你走上去就觉得缺氧。',
    phase: '望',
    phase_en: 'FULL MOON',
    vec: [50, 50, 15, 50, 85, 50],
    poles: 'I↓ S↑',
    between: '',
    png_path: '/personality/cards/P12.png',
  },
  {
    id: 'P13',
    type: '主',
    no: 13,
    name: '漫游界间',
    key: '跨界',
    line: '你不属于任何一片世界，你站在它们交界的地方。',
    phase: '亏凸',
    phase_en: 'WANING GIBBOUS',
    vec: [50, 50, 50, 50, 85, 85],
    poles: 'S↑ E↑',
    between: '',
    png_path: '/personality/cards/P13.png',
  },
  {
    id: 'P14',
    type: '主',
    no: 14,
    name: '执舵在手',
    key: '定调',
    line: '方向盘在你手里，别人才能安心看风景。',
    phase: '下弦',
    phase_en: 'LAST QUARTER',
    vec: [50, 50, 85, 85, 50, 50],
    poles: 'I↑ F↑',
    between: '',
    png_path: '/personality/cards/P14.png',
  },
  {
    id: 'P15',
    type: '主',
    no: 15,
    name: '观澜见来',
    key: '知来',
    line: '别人看得见一朵浪，你看见的是整片海的来路。',
    phase: '下弦',
    phase_en: 'LAST QUARTER',
    vec: [85, 50, 15, 50, 50, 50],
    poles: 'G↑ I↓',
    between: '',
    png_path: '/personality/cards/P15.png',
  },
  {
    id: 'T01',
    type: '过渡',
    no: 0.5,
    name: '暗处生温',
    key: '将燃',
    line: '别人以为你沉在原地，其实水下那一点，已经开始发热。',
    phase: '蛾眉',
    phase_en: 'WAXING CRESCENT',
    vec: [32, 50, 50, 50, 67, 15],
    poles: 'G·↓ S·↑ E↓',
    between: '暗礁无声 → 星火未燎',
    png_path: '/personality/cards/T01.png',
  },
  {
    id: 'T02',
    type: '过渡',
    no: 1.5,
    name: '微芒渐明',
    key: '初形',
    line: '那一点点火，慢慢有了自己的形状。',
    phase: '蛾眉',
    phase_en: 'WAXING CRESCENT',
    vec: [32, 50, 32, 50, 50, 50],
    poles: 'G·↓ I·↓',
    between: '星火未燎 → 微光不争',
    png_path: '/personality/cards/T02.png',
  },
  {
    id: 'T03',
    type: '过渡',
    no: 2.5,
    name: '照见前路',
    key: '成路',
    line: '你先照亮了角落，才看清角落外面还有路。',
    phase: '上弦',
    phase_en: 'FIRST QUARTER',
    vec: [50, 32, 32, 67, 50, 67],
    poles: 'X·↓ I·↓ F·↑ E·↑',
    between: '微光不争 → 先行探路',
    png_path: '/personality/cards/T03.png',
  },
  {
    id: 'T04',
    type: '过渡',
    no: 3.5,
    name: '且行且看',
    key: '且看',
    line: '你已经上了路，也开始停下来抬头看地形。',
    phase: '上弦',
    phase_en: 'FIRST QUARTER',
    vec: [32, 15, 50, 67, 50, 50],
    poles: 'G·↓ X↓ F·↑',
    between: '先行探路 → 静观一室',
    png_path: '/personality/cards/T04.png',
  },
  {
    id: 'T05',
    type: '过渡',
    no: 4.5,
    name: '观尽起锚',
    key: '起锚',
    line: '你看够了，然后才把手放上缆绳。',
    phase: '上弦',
    phase_en: 'FIRST QUARTER',
    vec: [32, 50, 50, 67, 50, 50],
    poles: 'G·↓ F·↑',
    between: '静观一室 → 解缆离岸',
    png_path: '/personality/cards/T05.png',
  },
  {
    id: 'T06',
    type: '过渡',
    no: 5.5,
    name: '出港不问',
    key: '帆张',
    line: '一离开码头，你就想去地图上空白的地方。',
    phase: '盈凸',
    phase_en: 'WAXING GIBBOUS',
    vec: [32, 67, 50, 50, 50, 50],
    poles: 'G·↓ X·↑',
    between: '解缆离岸 → 涉川不止',
    png_path: '/personality/cards/T06.png',
  },
  {
    id: 'T07',
    type: '过渡',
    no: 6.5,
    name: '远行有念',
    key: '有系',
    line: '走得再远，你心里也留着一盏回去的灯。',
    phase: '盈凸',
    phase_en: 'WAXING GIBBOUS',
    vec: [32, 50, 67, 32, 32, 50],
    poles: 'G·↓ I·↑ F·↓ S·↓',
    between: '涉川不止 → 守夜到明',
    png_path: '/personality/cards/T07.png',
  },
  {
    id: 'T08',
    type: '过渡',
    no: 7.5,
    name: '守而有度',
    key: '有底',
    line: '你会把自己放第二，但底下的那条线不会让。',
    phase: '盈凸',
    phase_en: 'WAXING GIBBOUS',
    vec: [50, 67, 67, 50, 15, 50],
    poles: 'X·↑ I·↑ S↓',
    between: '守夜到明 → 定盘在心',
    png_path: '/personality/cards/T08.png',
  },
  {
    id: 'T09',
    type: '过渡',
    no: 8.5,
    name: '谋定而动',
    key: '待晓',
    line: '你心里早有答案，只是等天亮才肯动。',
    phase: '望',
    phase_en: 'FULL MOON',
    vec: [50, 67, 50, 32, 32, 67],
    poles: 'X·↑ F·↓ S·↓ E·↑',
    between: '定盘在心 → 破晓即行',
    png_path: '/personality/cards/T09.png',
  },
  {
    id: 'T10',
    type: '过渡',
    no: 9.5,
    name: '动而聚人',
    key: '群随',
    line: '你先冲了出去，回头发现身后已经聚了一群人。',
    phase: '望',
    phase_en: 'FULL MOON',
    vec: [67, 67, 50, 32, 50, 67],
    poles: 'G·↑ X·↑ F·↓ E·↑',
    between: '破晓即行 → 织网相连',
    png_path: '/personality/cards/T10.png',
  },
  {
    id: 'T11',
    type: '过渡',
    no: 10.5,
    name: '联而新作',
    key: '新造',
    line: '把人连起来还不够，你想让他们看见从没见过的东西。',
    phase: '望',
    phase_en: 'FULL MOON',
    vec: [67, 67, 32, 50, 67, 50],
    poles: 'G·↑ X·↑ I·↓ S·↑',
    between: '织网相连 → 自造其光',
    png_path: '/personality/cards/T11.png',
  },
  {
    id: 'T12',
    type: '过渡',
    no: 11.5,
    name: '作而无界',
    key: '无界',
    line: '你造出来的东西，从来不肯只待在一个世界里。',
    phase: '亏凸',
    phase_en: 'WANING GIBBOUS',
    vec: [50, 50, 32, 50, 85, 67],
    poles: 'I·↓ S↑ E·↑',
    between: '自造其光 → 漫游界间',
    png_path: '/personality/cards/T12.png',
  },
  {
    id: 'T13',
    type: '过渡',
    no: 12.5,
    name: '跨界定舵',
    key: '掌向',
    line: '站在几个世界的交界久了，你学会了自己掌方向盘。',
    phase: '下弦',
    phase_en: 'LAST QUARTER',
    vec: [50, 50, 67, 67, 67, 67],
    poles: 'I·↑ F·↑ S·↑ E·↑',
    between: '漫游界间 → 执舵在手',
    png_path: '/personality/cards/T13.png',
  },
  {
    id: 'T14',
    type: '过渡',
    no: 13.5,
    name: '掌而览尽',
    key: '海阔',
    line: '方向握稳之后，你才抬起头看整片海的走势。',
    phase: '下弦',
    phase_en: 'LAST QUARTER',
    vec: [67, 50, 50, 67, 50, 50],
    poles: 'G·↑ F·↑',
    between: '执舵在手 → 观澜见来',
    png_path: '/personality/cards/T14.png',
  },
  {
    id: 'T15',
    type: '过渡',
    no: 14.5,
    name: '览而归沉',
    key: '归礁',
    line: '看完整片海，你又沉了回去，等着下一次涨潮。',
    phase: '朔',
    phase_en: 'NEW MOON',
    vec: [67, 50, 32, 50, 67, 32],
    poles: 'G·↑ I·↓ S·↑ E·↓',
    between: '观澜见来 → 暗礁无声',
    png_path: '/personality/cards/T15.png',
  },
] as const;

export const PERSONALITY_CARDS_BY_NO: readonly PersonalityCard[] = Object.freeze(
  [...PERSONALITY_CARDS].sort((a, b) => a.no - b.no)
);

export const PERSONALITY_CARD_BY_ID: Readonly<Record<string, PersonalityCard>> = Object.freeze(
  Object.fromEntries(PERSONALITY_CARDS.map(c => [c.id, c]))
);

export function getCardById(id: string): PersonalityCard | undefined {
  return PERSONALITY_CARD_BY_ID[id];
}