// =====================================================
// 人格测试 — 5 套卷 × 36 题 = 180 题 数据层
// 来源：B_题库_5套卷180题_修订版.csv（2026-09-13）
// 修订：I15/S14 选项打散
// 类型 PersonalityQuestion 集中在 types.ts 定义
// 选项展示顺序固定，不要随机洗牌
// =====================================================

import type { PersonalityQuestion, PersonalityPaperId, PersonalityDimension } from "./types";

export type PaperId = PersonalityPaperId;

export const PERSONALITY_PAPERS: readonly PersonalityPaperId[] = ["P1", "P2", "P3", "P4", "P5"] as const;

/** 抽卷：hash(userKey) % 5 → 同一用户复测同一卷 */
export function pickPaperId(userKey: string): PersonalityPaperId {
  let h = 0x811c9dc5 >>> 0;
  for (let i = 0; i < userKey.length; i++) {
    h ^= userKey.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return PERSONALITY_PAPERS[h % 5];
}

export const PERSONALITY_QUESTIONS_1: readonly PersonalityQuestion[] = [
  {
    id: 'G01',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '有件事让你不太舒服，你一般会',
    options: ['先把话说软一点，再把真实想法带出来', '算了，说了多半也没用，我自己消化', '找个合适的时机，直接说出是哪一点让我不舒服', '绕着弯提几次，看事情会不会自己变好', '嘴上不说，但态度和语气会先冷下来'] as const,
    scores: [4, 1, 5, 3, 2] as const,
    mother_question_id: 'G01',
    weight: 1,
  },
  {
    id: 'I09',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你觉得人和人的关系需要刻意维护吗',
    options: ['需要一些，但不用太刻意', '不需要，顺其自然就好', '看阶段，刚开始需要，久了就不用', '很需要，不维护就会变淡', '不太需要，用力反而别扭'] as const,
    scores: [4, 1, 3, 5, 2] as const,
    mother_question_id: 'I09',
    weight: 1,
  },
  {
    id: 'S13',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '你会保留一些谁都不说的心事吗',
    options: ['会，但不是什么大事', '不会，我什么都会说出来', '很少，我基本都会说', '会，有些事我只想自己留着', '偶尔会'] as const,
    scores: [4, 1, 2, 5, 3] as const,
    mother_question_id: 'S13',
    weight: 1,
  },
  {
    id: 'G04',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '「我不说，你也应该懂」这句话，你的看法是',
    options: ['希望是这样，但现实里基本做不到', '挺认同的，真正在意我的人应该能感觉到', '说不上认同，但我自己常这么做', '不太认同，我会尽量把话说清楚', '不太认同，不说出来别人怎么可能知道'] as const,
    scores: [3, 1, 2, 4, 5] as const,
    mother_question_id: 'G04',
    weight: 1,
  },
  {
    id: 'X07',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '你会把问题拆成具体能落地的解决办法吗',
    options: ['有时候会', '基本不会，事情过去了就行', '会，事情过去我一定会列个下一步', '比较少，我更在意状态有没有缓过来', '会，大部分时候能想到具体做法'] as const,
    scores: [3, 1, 5, 2, 4] as const,
    mother_question_id: 'X07',
    weight: 1,
  },
  {
    id: 'E17',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '你会把自己脆弱的一面露出来吗',
    options: ['偶尔会', '很少，我不太想让人看到', '会，我觉得这没什么', '基本不会，我会一直撑着', '会，但只在很熟的人面前'] as const,
    scores: [3, 2, 5, 1, 4] as const,
    mother_question_id: 'E17',
    weight: 1,
  },
  {
    id: 'S18',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '关于「每个人都该有自己的生活」，你',
    options: ['比较认同', '有点距离感，不太舒服', '非常认同，这是长久的前提', '认同，但也要有足够交集', '不太认同，亲近就该不分你我'] as const,
    scores: [4, 2, 5, 3, 1] as const,
    mother_question_id: 'S18',
    weight: 1,
  },
  {
    id: 'S06',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '关于独处，你的感受是',
    options: ['有也可以，没有也行', '很不习惯一个人，会空落落的', '比较享受独处', '不太喜欢一个人待着', '独处给我充电，跟人待太久我会疲惫'] as const,
    scores: [3, 1, 4, 2, 5] as const,
    mother_question_id: 'S06',
    weight: 1,
  },
  {
    id: 'E02',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '心里很难受的时候，你通常',
    options: ['说不太清自己难受什么，最后还是没说', '完全自己扛，谁也看不出来', '直接说出来，我需要有人陪着', '自己消化，不想把情绪带给别人', '会说一点，让人知道我状态不好'] as const,
    scores: [3, 1, 5, 2, 4] as const,
    mother_question_id: 'E02',
    weight: 1,
  },
  {
    id: 'X16',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '事情僵住了，你会先做什么',
    options: ['先去倒杯水、做点别的，缓一缓气氛', '先离开这个空间，各自待一会儿', '先聊最容易达成一致的那部分', '把分歧点一条条写下来，逐个谈', '不做任何事，等它自己过去'] as const,
    scores: [3, 2, 4, 5, 1] as const,
    mother_question_id: 'X16',
    weight: 1,
  },
  {
    id: 'X02',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '事情过去之后，你会主动复盘吗',
    options: ['很少，我不喜欢再回头看', '偶尔会', '每次都会，把来龙去脉捋一遍', '经常会', '从来不会，过去就过去了'] as const,
    scores: [2, 3, 5, 4, 1] as const,
    mother_question_id: 'X02',
    weight: 1,
  },
  {
    id: 'I15',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你会经常想要确认自己在别人心里重不重要吗',
    options: ['偶尔会', '经常会', '基本不会', '很少', '比较多'] as const,
    scores: [3, 5, 1, 2, 4] as const,
    mother_question_id: 'I15',
    weight: 1,
  },
  {
    id: 'G18',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '别人误会你了，你会',
    options: ['解释一遍，说不清楚就算了', '简单提一句，信不信随人', '懒得解释，时间会证明', '立刻解释，把前因后果讲完整', '不解释，心里会有点受伤'] as const,
    scores: [4, 3, 2, 5, 1] as const,
    mother_question_id: 'G18',
    weight: 1,
  },
  {
    id: 'F13',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '你更相信',
    options: ['变化太多，计划没什么用', '有方向比没方向好', '人生不需要按计划走', '规划清楚了，路才走得稳', '方向和灵活都要有'] as const,
    scores: [2, 4, 1, 5, 3] as const,
    mother_question_id: 'F13',
    weight: 1,
  },
  {
    id: 'S17',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '朋友约你出去，但你手上还有别人的事要顾，你会',
    options: ['去见朋友，我提前把手上的事交代清楚', '看哪边更重要', '肯定留下来，先顾别人那头', '去见朋友，但会先把该做的事做完', '多半留下来把手上的事做完'] as const,
    scores: [5, 3, 1, 4, 2] as const,
    mother_question_id: 'S17',
    weight: 1,
  },
  {
    id: 'I12',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你会因为没人回应而反复看手机吗',
    options: ['有时候会', '经常会，忍不住一直看', '比较多', '偶尔会', '从来不会'] as const,
    scores: [3, 5, 4, 2, 1] as const,
    mother_question_id: 'I12',
    weight: 1,
  },
  {
    id: 'S04',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '你有自己的圈子、自己的事在做，这件事对你有多重要',
    options: ['一般重要', '非常重要，这是我的根基', '比较重要', '不太重要，跟着大家一起就行', '有点重要，但不是必需'] as const,
    scores: [3, 5, 4, 1, 2] as const,
    mother_question_id: 'S04',
    weight: 1,
  },
  {
    id: 'E13',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '你要说一句很肉麻的话，你会',
    options: ['说，但会有点不好意思', '说不出来，换个方式带过', '很自然地说出口', '很勉强，能省就省', '用开玩笑的方式说'] as const,
    scores: [4, 1, 5, 2, 3] as const,
    mother_question_id: 'E13',
    weight: 1,
  },
  {
    id: 'F04',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '一段日子过得没什么方向，你会',
    options: ['很不安，这是我不接受的状态', '无所谓，本来也不需要一直有方向', '没什么感觉，现在好就行', '会比较担心，想尽快理出个方向', '有点在意，但不至于影响现在'] as const,
    scores: [5, 1, 2, 4, 3] as const,
    mother_question_id: 'F04',
    weight: 1,
  },
  {
    id: 'G14',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '发现自己刚才说错话了，你会',
    options: ['不太会承认，心里有点过意不去但说不出口', '过一会儿找机会补一句解释', '用别的话把意思圆回来', '当场就说「我刚才那句话不对」，然后重说', '当没发生过，指望别人没往心里去'] as const,
    scores: [1, 4, 3, 5, 2] as const,
    mother_question_id: 'G14',
    weight: 1,
  },
  {
    id: 'E01',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '心里被触动的时候，你会说出来吗',
    options: ['偶尔会说', '会，但不会太频繁', '很少说，有点难为情', '基本不说', '会，想到就说'] as const,
    scores: [3, 4, 2, 1, 5] as const,
    mother_question_id: 'E01',
    weight: 1,
  },
  {
    id: 'X13',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '你会主动把「以后遇到这种事怎么办」摆到明面上吗',
    options: ['偶尔会', '会，但只在比较重要的冲突之后', '从来不会', '会，这是事情过去之后必做的一步', '很少，感觉像在立规矩，有点别扭'] as const,
    scores: [3, 4, 1, 5, 2] as const,
    mother_question_id: 'X13',
    weight: 1,
  },
  {
    id: 'S03',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '连续几天被人约满，你会',
    options: ['挺好，我没问题', '正合我意，我就怕闲着', '有点喘不过气，我需要留出几天给自己', '可以，但隔几天我想空一天', '可以，但我需要提前说好哪几天是我的'] as const,
    scores: [2, 1, 5, 3, 4] as const,
    mother_question_id: 'S03',
    weight: 1,
  },
  {
    id: 'E04',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '「我在意你」这句话，你觉得',
    options: ['偶尔说说还行', '说得出口，但要看场合', '很自然，我经常会说', '说不出来，太肉麻了', '有点开不了口'] as const,
    scores: [3, 4, 5, 1, 2] as const,
    mother_question_id: 'E04',
    weight: 1,
  },
  {
    id: 'I13',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你觉得最舒服的位置是',
    options: ['一半一半', '有人惦记，偶尔有交集', '靠自己，不指望任何人', '能被人想起、被人需要的那种位置', '各自过各自的，联系不用太多'] as const,
    scores: [3, 4, 1, 5, 2] as const,
    mother_question_id: 'I13',
    weight: 1,
  },
  {
    id: 'X12',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '僵持到一半，对面突然不说话了，你会',
    options: ['也停下来，各待各的', '给几分钟，然后主动把话题接回来', '我也沉默，等那边先开口', '松一口气，正好不用继续了', '追着问清楚，不能就这么悬着'] as const,
    scores: [3, 4, 2, 1, 5] as const,
    mother_question_id: 'X12',
    weight: 1,
  },
  {
    id: 'F08',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '一年过去了，你还没想清楚下一步，你会',
    options: ['找人聊聊，看看别人怎么走', '有点在意，但会再等等', '挺好的，我也不急着定', '不太急，顺其自然', '主动空出时间理一理，我需要一个明确的说法'] as const,
    scores: [4, 3, 1, 2, 5] as const,
    mother_question_id: 'F08',
    weight: 1,
  },
  {
    id: 'G10',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '别人问你「怎么了」，你说「没事」的时候，实际是',
    options: ['真的没事，我不需要绕弯子', '有事，但我希望别人能自己看出来', '有点事，但我需要几分钟组织语言', '有事，但我不知道怎么开口', '有事，我想等人多问一句再说'] as const,
    scores: [5, 1, 4, 2, 3] as const,
    mother_question_id: 'G10',
    weight: 1,
  },
  {
    id: 'E06',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '把心里的话说出来，你会觉得难为情吗',
    options: ['完全不会，我觉得很自然', '比较难为情', '基本不会', '很难为情，基本说不出口', '有一点，但还能说'] as const,
    scores: [5, 2, 4, 1, 3] as const,
    mother_question_id: 'E06',
    weight: 1,
  },
  {
    id: 'G02',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '心里有了想法，你会直接说出口吗',
    options: ['几乎每次都会说', '偶尔忍不住了才说', '基本都憋在心里', '大部分时候会说', '一半一半，看是什么事'] as const,
    scores: [5, 2, 1, 4, 3] as const,
    mother_question_id: 'G02',
    weight: 1,
  },
  {
    id: 'F11',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '有人对你说「你这样下去不行」，你会',
    options: ['给自己设一个期限，到时必须有个结果', '认真想一次，把顾虑一条条摊开', '我也没想好，那就先这样', '听过就算，不去逼自己', '记在心里，但先按自己的节奏走'] as const,
    scores: [5, 4, 1, 2, 3] as const,
    mother_question_id: 'F11',
    weight: 1,
  },
  {
    id: 'F10',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '为了一个不确定的机会，调整自己的计划，你的态度是',
    options: ['不会为了别的事打乱我的计划', '可以调整一部分，底线不能动', '看是什么事，小调整可以', '愿意，人生本来就要不断调整', '不太愿意，我有自己的节奏'] as const,
    scores: [1, 4, 3, 5, 2] as const,
    mother_question_id: 'F10',
    weight: 1,
  },
  {
    id: 'X18',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '别人道歉了，但没说到点子上，你会',
    options: ['先收下，心里还有点没过去', '说没事，但其实没真的放下', '接受道歉，但补一句我的真实感受', '明说我要的不是这一句，是另一句', '说没事，然后把这事翻篇'] as const,
    scores: [3, 2, 4, 5, 1] as const,
    mother_question_id: 'X18',
    weight: 1,
  },
  {
    id: 'F06',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '你会把未来的事拆成阶段性目标吗',
    options: ['基本不会', '会，我有比较明确的时间表', '偶尔会想想', '很少，想了也未必实现', '会，大节点我心里有数'] as const,
    scores: [1, 5, 3, 2, 4] as const,
    mother_question_id: 'F06',
    weight: 1,
  },
  {
    id: 'I06',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '关于「被需要」，你觉得',
    options: ['不太需要，各自独立更好', '我很需要被需要，这让我知道自己有用', '被需要让我有安全感', '不太喜欢被需要的感觉，有点压力', '有最好，没有也不强求'] as const,
    scores: [2, 5, 4, 1, 3] as const,
    mother_question_id: 'I06',
    weight: 1,
  },
  {
    id: 'I14',
    paper: 'P1' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你主动递出一个善意，没什么回音，你会',
    options: ['会难受，需要弄明白是怎么回事', '无所谓，收回就好', '有点尴尬，先缓一缓', '会再试一次，或者直接问一句', '不太在意，可能没看到'] as const,
    scores: [5, 1, 3, 4, 2] as const,
    mother_question_id: 'I14',
    weight: 1,
  },
];

export const PERSONALITY_QUESTIONS_2: readonly PersonalityQuestion[] = [
  {
    id: 'X10',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '你需要先独处一会儿才能想明白，这种情况多吗',
    options: ['比较少', '有时候需要', '几乎每次都需要，当场我说不清楚', '经常需要', '基本不需要，我当场就能说清楚'] as const,
    scores: [4, 3, 1, 2, 5] as const,
    mother_question_id: 'X10',
    weight: 1,
  },
  {
    id: 'F03',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '你会主动把自己的计划往前推吗（存钱、换城市、学新东西）',
    options: ['会，我基本是那个推着自己走的人', '比较少，跟着事情走', '看情况，重要的我会推', '不会，顺其自然', '会，我推得比较多'] as const,
    scores: [5, 2, 3, 1, 4] as const,
    mother_question_id: 'F03',
    weight: 1,
  },
  {
    id: 'E09',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '你会主动给人准备点什么、制造点惊喜吗',
    options: ['经常，我喜欢这种表达', '基本不会', '很少，我不太擅长这个', '会，逢年过节和特别的日子', '偶尔会'] as const,
    scores: [5, 1, 2, 4, 3] as const,
    mother_question_id: 'E09',
    weight: 1,
  },
  {
    id: 'F17',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '你把未来想得很清楚了，身边却没人理解，你会',
    options: ['挺好，我也不需要别人理解', '会想办法把我的理由讲清楚', '先做我自己的部分，等等看', '把我的规划讲给人听，看反应', '算了，不强求'] as const,
    scores: [1, 5, 3, 4, 2] as const,
    mother_question_id: 'F17',
    weight: 1,
  },
  {
    id: 'S14',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '连着三天都跟人待在一块儿，你的状态是',
    options: ['挺好，没什么不适', '有点累，想空出一天给自己', '很满足，还想继续', '已经开始烦躁，我需要一个人待着', '还行，有点累但能撑'] as const,
    scores: [2, 4, 1, 5, 3] as const,
    mother_question_id: 'S14',
    weight: 1,
  },
  {
    id: 'I16',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '有段时间没人找你、也没人提起你，你会',
    options: ['没什么特别感觉', '会主动联系别人，哪怕只是聊几句', '挺好，我也落得清净', '会不安，需要找人说说话', '有点不习惯，但能适应'] as const,
    scores: [2, 4, 1, 5, 3] as const,
    mother_question_id: 'I16',
    weight: 1,
  },
  {
    id: 'E06',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '把心里的话说出来，你会觉得难为情吗',
    options: ['完全不会，我觉得很自然', '比较难为情', '基本不会', '很难为情，基本说不出口', '有一点，但还能说'] as const,
    scores: [5, 2, 4, 1, 3] as const,
    mother_question_id: 'E06',
    weight: 1,
  },
  {
    id: 'S13',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '你会保留一些谁都不说的心事吗',
    options: ['会，但不是什么大事', '不会，我什么都会说出来', '很少，我基本都会说', '会，有些事我只想自己留着', '偶尔会'] as const,
    scores: [4, 1, 2, 5, 3] as const,
    mother_question_id: 'S13',
    weight: 1,
  },
  {
    id: 'I18',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你会主动张罗一个局、把人聚起来吗',
    options: ['会，基本都是我在张罗', '会，我提得比较多', '很少，随缘就好', '比较少，一般别人提', '一半一半'] as const,
    scores: [5, 4, 1, 2, 3] as const,
    mother_question_id: 'I18',
    weight: 1,
  },
  {
    id: 'F01',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '关于「以后」，你更认同',
    options: ['希望能把往后的事聊清楚，越具体越好', '走一步看一步，计划赶不上变化', '大方向要一致，细节可以慢慢定', '不太想谈以后，过好现在更重要', '有个大概的方向就行，不必太细'] as const,
    scores: [5, 2, 4, 1, 3] as const,
    mother_question_id: 'F01',
    weight: 1,
  },
  {
    id: 'S17',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '朋友约你出去，但你手上还有别人的事要顾，你会',
    options: ['去见朋友，我提前把手上的事交代清楚', '看哪边更重要', '肯定留下来，先顾别人那头', '去见朋友，但会先把该做的事做完', '多半留下来把手上的事做完'] as const,
    scores: [5, 3, 1, 4, 2] as const,
    mother_question_id: 'S17',
    weight: 1,
  },
  {
    id: 'S16',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '没人陪、没人安排的时候，你能把自己的日子过好吗',
    options: ['很难，会一直等有人来找我', '还行，偶尔会有点空', '可以，我有自己的节奏', '完全没问题，我过得更自在', '有点难熬'] as const,
    scores: [1, 3, 4, 5, 2] as const,
    mother_question_id: 'S16',
    weight: 1,
  },
  {
    id: 'I11',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '有人说「这件事我自己来就行」，你的第一反应是',
    options: ['没问题，我找点别的事做', '会有点失落，想知道是不是我哪里没做好', 'OK，不用多想', '可以，但希望最后能跟我同步一下', '正好，我也能腾出手'] as const,
    scores: [3, 5, 2, 4, 1] as const,
    mother_question_id: 'I11',
    weight: 1,
  },
  {
    id: 'X01',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '和人起了正面冲突，你当下最可能',
    options: ['先不说了，我需要一个人待一会儿', '把话说到底，今天必须有个结果', '先按住情绪，把事情本身捋清楚', '直接走开，这件事我不想再提', '说几句就停，等双方都冷静了再谈'] as const,
    scores: [2, 5, 4, 1, 3] as const,
    mother_question_id: 'X01',
    weight: 1,
  },
  {
    id: 'G03',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '有人做了件让你不太舒服的事，你的第一反应是',
    options: ['当天晚点找个气氛合适的时候再说', '不说，自己慢慢消化掉', '想说但开不了口，用别的情绪表现出来', '反复掂量要不要说，最后多半还是说了', '当场就说出来，说完这件事就翻篇'] as const,
    scores: [4, 1, 2, 3, 5] as const,
    mother_question_id: 'G03',
    weight: 1,
  },
  {
    id: 'G02',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '心里有了想法，你会直接说出口吗',
    options: ['几乎每次都会说', '偶尔忍不住了才说', '基本都憋在心里', '大部分时候会说', '一半一半，看是什么事'] as const,
    scores: [5, 2, 1, 4, 3] as const,
    mother_question_id: 'G02',
    weight: 1,
  },
  {
    id: 'X04',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '你觉得自己有理，但另一方情绪很激动，你会',
    options: ['先让步，等事情冷下来再说', '继续讲道理，情绪归情绪，事情要说清', '先让人把情绪发完，等缓和了再讲事情', '干脆认下来，把这一页尽快翻过去', '不再说了，但我心里知道自己没错'] as const,
    scores: [3, 5, 4, 1, 2] as const,
    mother_question_id: 'X04',
    weight: 1,
  },
  {
    id: 'I06',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '关于「被需要」，你觉得',
    options: ['不太需要，各自独立更好', '我很需要被需要，这让我知道自己有用', '被需要让我有安全感', '不太喜欢被需要的感觉，有点压力', '有最好，没有也不强求'] as const,
    scores: [2, 5, 4, 1, 3] as const,
    mother_question_id: 'I06',
    weight: 1,
  },
  {
    id: 'F14',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '手上有两条路，方向完全不同，你会',
    options: ['想清楚每条的代价，再选一条', '不太想面对，拖一拖', '把自己的优先级排一遍，选一条走到底', '都可以，走到哪算哪', '先两边都试试，看后面有没有转机'] as const,
    scores: [4, 2, 5, 1, 3] as const,
    mother_question_id: 'F14',
    weight: 1,
  },
  {
    id: 'F12',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '你会主动想「我下一步到底要什么」吗',
    options: ['偶尔想一想', '会，我觉得该早点想清楚', '基本不想', '很少，等事情推着走', '会，但不会天天想'] as const,
    scores: [3, 5, 1, 2, 4] as const,
    mother_question_id: 'F12',
    weight: 1,
  },
  {
    id: 'E14',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '你会主动用肢体接触表达亲近吗（拥抱、拍肩、挽手）',
    options: ['基本不会，会有点不自在', '会，但只在私下', '偶尔会', '比较少，我不太习惯', '经常，我很自然'] as const,
    scores: [1, 4, 3, 2, 5] as const,
    mother_question_id: 'E14',
    weight: 1,
  },
  {
    id: 'E05',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '看电影看到动情处，你被触动了，你会',
    options: ['有点鼻酸，但忍住了', '眼眶红了，会偷偷擦一下', '心里有感触，脸上没什么反应', '眼泪直接掉，也不遮掩', '没什么特别感觉，也很少被打动'] as const,
    scores: [3, 4, 2, 5, 1] as const,
    mother_question_id: 'E05',
    weight: 1,
  },
  {
    id: 'S15',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '你觉得最健康的边界是',
    options: ['边界感太强反而生分', '清晰划线，各自的部分互不打扰', '有边界，但可以商量', '不用太明确，彼此有分寸就行', '亲近就是不分彼此'] as const,
    scores: [2, 5, 4, 3, 1] as const,
    mother_question_id: 'S15',
    weight: 1,
  },
  {
    id: 'X14',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '冲突之后你最想要的收尾是',
    options: ['当没发生过，恢复原样就好', '事情有结论，接下来该怎么走很清楚', '把话说开，情绪能过去', '放一放，自然就过去了', '面上过得去，别再提这件事'] as const,
    scores: [1, 5, 4, 2, 3] as const,
    mother_question_id: 'X14',
    weight: 1,
  },
  {
    id: 'I05',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你花了心思做的事，最后没人提起，你会',
    options: ['会找个机会让人知道这是我做的', '会失落，需要有人给句明确的话', '没关系，我做是为了自己', '没什么特别的感觉', '有点空落落的，但能想通'] as const,
    scores: [4, 5, 1, 2, 3] as const,
    mother_question_id: 'I05',
    weight: 1,
  },
  {
    id: 'F05',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '眼前出现一个和你的计划冲突的机会，你会',
    options: ['说出我的顾虑，试着找一个折中', '不太想纠结，先顺着眼前走', '直接放弃机会，按原计划来', '先听听自己更想要哪个', '把两条路摆出来，看哪条更值'] as const,
    scores: [4, 2, 1, 3, 5] as const,
    mother_question_id: 'F05',
    weight: 1,
  },
  {
    id: 'G09',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '话到嘴边又咽回去的情况，你身上多吗',
    options: ['比较少', '几乎没有，我想说的都会说', '经常这样，很多话最后都没说', '有时候会', '比较多'] as const,
    scores: [4, 5, 1, 3, 2] as const,
    mother_question_id: 'G09',
    weight: 1,
  },
  {
    id: 'E15',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '被当众夸奖或被点名表扬，你的感受是',
    options: ['可以接受，但会有点不好意思', '有点尴尬', '挺好的，我很享受', '很不舒服，我想躲开', '无所谓'] as const,
    scores: [4, 2, 5, 1, 3] as const,
    mother_question_id: 'E15',
    weight: 1,
  },
  {
    id: 'G06',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '你会主动跟人交代自己的行程和安排吗',
    options: ['很少主动说，觉得没必要件件报备', '问起来我就说', '重要的事会说，琐碎的就省了', '基本不说，各自知道各自的就行', '会，去哪儿、跟谁、大概几点回，都会说'] as const,
    scores: [2, 3, 4, 1, 5] as const,
    mother_question_id: 'G06',
    weight: 1,
  },
  {
    id: 'X06',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '有一个问题反复出现，一直没解决，你会',
    options: ['再提一次，不行就算了', '懒得再提了，习惯了', '这次一定要拿出个办法，不能再来一次', '把之前几次串起来，看它是不是有规律', '心里已经放弃解决这件事了'] as const,
    scores: [3, 2, 5, 4, 1] as const,
    mother_question_id: 'X06',
    weight: 1,
  },
  {
    id: 'S11',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '有人提出要跟你合住／合伙做事，你会',
    options: ['很开心，我早就想了', '可以，但得先约法几章', '可以，但需要过渡一下', '有点警惕，我需要先谈清楚边界', '挺好，直接来吧'] as const,
    scores: [1, 4, 3, 5, 2] as const,
    mother_question_id: 'S11',
    weight: 1,
  },
  {
    id: 'I09',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你觉得人和人的关系需要刻意维护吗',
    options: ['需要一些，但不用太刻意', '不需要，顺其自然就好', '看阶段，刚开始需要，久了就不用', '很需要，不维护就会变淡', '不太需要，用力反而别扭'] as const,
    scores: [4, 1, 3, 5, 2] as const,
    mother_question_id: 'I09',
    weight: 1,
  },
  {
    id: 'E08',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '关于「心里的话要说出口」，你觉得',
    options: ['很重要，不说别人怎么知道', '不太重要，做了就行', '完全不重要，说出来反而假', '说得少一点没关系，做到更重要', '需要说，行动也重要'] as const,
    scores: [5, 2, 1, 3, 4] as const,
    mother_question_id: 'E08',
    weight: 1,
  },
  {
    id: 'G04',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '「我不说，你也应该懂」这句话，你的看法是',
    options: ['希望是这样，但现实里基本做不到', '挺认同的，真正在意我的人应该能感觉到', '说不上认同，但我自己常这么做', '不太认同，我会尽量把话说清楚', '不太认同，不说出来别人怎么可能知道'] as const,
    scores: [3, 1, 2, 4, 5] as const,
    mother_question_id: 'G04',
    weight: 1,
  },
  {
    id: 'G08',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '有分歧的时候，你更倾向',
    options: ['把分歧点摆到桌面上，逐个解决', '先不提，避免把气氛弄僵', '说一半留一半，让人自己去体会', '把我的理由一条条讲出来', '先听别人怎么说，再决定我要不要讲'] as const,
    scores: [5, 1, 2, 4, 3] as const,
    mother_question_id: 'G08',
    weight: 1,
  },
  {
    id: 'X05',
    paper: 'P2' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '起了争执之后，通常是',
    options: ['我冷着，可以很久不说话', '一般是别人先开口，我在等', '我主动开口，把问题聊开', '我等一会儿，还是会先开口', '看谁先忍不住，不一定是我'] as const,
    scores: [1, 2, 5, 4, 3] as const,
    mother_question_id: 'X05',
    weight: 1,
  },
];

export const PERSONALITY_QUESTIONS_3: readonly PersonalityQuestion[] = [
  {
    id: 'X02',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '事情过去之后，你会主动复盘吗',
    options: ['很少，我不喜欢再回头看', '偶尔会', '每次都会，把来龙去脉捋一遍', '经常会', '从来不会，过去就过去了'] as const,
    scores: [2, 3, 5, 4, 1] as const,
    mother_question_id: 'X02',
    weight: 1,
  },
  {
    id: 'F18',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '你愿意把自己的未来早早定下来吗',
    options: ['完全不愿意', '不太愿意', '非常愿意', '比较愿意', '看情况'] as const,
    scores: [1, 2, 5, 4, 3] as const,
    mother_question_id: 'F18',
    weight: 1,
  },
  {
    id: 'X15',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '你发现有人在冷处理你，你会',
    options: ['主动递个台阶，试探还能不能聊', '也冷着，看谁先撑不住', '直接问到底是哪句话没对，把话说开', '有点慌，但不知道该怎么办，就耗着', '不打扰，等这事自己冷下来'] as const,
    scores: [4, 3, 5, 1, 2] as const,
    mother_question_id: 'X15',
    weight: 1,
  },
  {
    id: 'E09',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '你会主动给人准备点什么、制造点惊喜吗',
    options: ['经常，我喜欢这种表达', '基本不会', '很少，我不太擅长这个', '会，逢年过节和特别的日子', '偶尔会'] as const,
    scores: [5, 1, 2, 4, 3] as const,
    mother_question_id: 'E09',
    weight: 1,
  },
  {
    id: 'X17',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '你会因为怕伤和气而咽下自己的意见吗',
    options: ['有时候会', '比较少', '经常这样，我几乎不坚持', '基本不会，我一定会说', '比较多'] as const,
    scores: [3, 4, 1, 5, 2] as const,
    mother_question_id: 'X17',
    weight: 1,
  },
  {
    id: 'X05',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '起了争执之后，通常是',
    options: ['我冷着，可以很久不说话', '一般是别人先开口，我在等', '我主动开口，把问题聊开', '我等一会儿，还是会先开口', '看谁先忍不住，不一定是我'] as const,
    scores: [1, 2, 5, 4, 3] as const,
    mother_question_id: 'X05',
    weight: 1,
  },
  {
    id: 'I17',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '什么最能让你有底气',
    options: ['有人记得我说过的小事', '把手上的事做好就够了', '有人明确说过我很重要', '自己心里有底，不用别人证明', '靠自己，不需要任何人给的底'] as const,
    scores: [4, 2, 5, 3, 1] as const,
    mother_question_id: 'I17',
    weight: 1,
  },
  {
    id: 'S12',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '关于「钱要不要共用」，你更倾向',
    options: ['看是什么事，部分共用', '基本共用，需要就说一声', '大部分分开，只在具体事上分摊', '完全共用，不分你我', '完全分开，各自管各自的'] as const,
    scores: [3, 2, 4, 1, 5] as const,
    mother_question_id: 'S12',
    weight: 1,
  },
  {
    id: 'F06',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '你会把未来的事拆成阶段性目标吗',
    options: ['基本不会', '会，我有比较明确的时间表', '偶尔会想想', '很少，想了也未必实现', '会，大节点我心里有数'] as const,
    scores: [1, 5, 3, 2, 4] as const,
    mother_question_id: 'F06',
    weight: 1,
  },
  {
    id: 'G11',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '你心里最理想的沟通状态是',
    options: ['不用每件事都说透，差不多就行', '大部分事能聊开，少数事各自消化', '很多事心照不宣，说透了反而尴尬', '少说少错，安静待着最舒服', '有什么说什么，说完就过去，不留隔夜账'] as const,
    scores: [3, 4, 2, 1, 5] as const,
    mother_question_id: 'G11',
    weight: 1,
  },
  {
    id: 'E07',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '有人为你做了一件很用心的事，你会',
    options: ['心里很感动，但什么都没表示', '说谢谢，但不会说太多', '认真说谢谢，让人知道我很喜欢', '当场就说我很感动，反应藏不住', '记在心里，用行动回报'] as const,
    scores: [1, 3, 4, 5, 2] as const,
    mother_question_id: 'E07',
    weight: 1,
  },
  {
    id: 'X12',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '僵持到一半，对面突然不说话了，你会',
    options: ['也停下来，各待各的', '给几分钟，然后主动把话题接回来', '我也沉默，等那边先开口', '松一口气，正好不用继续了', '追着问清楚，不能就这么悬着'] as const,
    scores: [3, 4, 2, 1, 5] as const,
    mother_question_id: 'X12',
    weight: 1,
  },
  {
    id: 'F01',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '关于「以后」，你更认同',
    options: ['希望能把往后的事聊清楚，越具体越好', '走一步看一步，计划赶不上变化', '大方向要一致，细节可以慢慢定', '不太想谈以后，过好现在更重要', '有个大概的方向就行，不必太细'] as const,
    scores: [5, 2, 4, 1, 3] as const,
    mother_question_id: 'F01',
    weight: 1,
  },
  {
    id: 'I02',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '一整天都没有人找你，你会',
    options: ['没什么感觉，我也没想着联系谁', '会主动发个消息，但不提这件事', '稍微有点在意，但忍着不问', '有点纳闷，但不会主动开口', '会不踏实，忍不住先发条消息'] as const,
    scores: [1, 4, 2, 3, 5] as const,
    mother_question_id: 'I02',
    weight: 1,
  },
  {
    id: 'S19',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '你需要提前知道别人全天的安排吗',
    options: ['不需要，我不想知道那么细', '基本不需要', '需要，我会比较安心', '知道个大概就行', '希望知道多一些'] as const,
    scores: [5, 4, 1, 3, 2] as const,
    mother_question_id: 'S19',
    weight: 1,
  },
  {
    id: 'E14',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '你会主动用肢体接触表达亲近吗（拥抱、拍肩、挽手）',
    options: ['基本不会，会有点不自在', '会，但只在私下', '偶尔会', '比较少，我不太习惯', '经常，我很自然'] as const,
    scores: [1, 4, 3, 2, 5] as const,
    mother_question_id: 'E14',
    weight: 1,
  },
  {
    id: 'G07',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '你想拒绝一个不太合理的要求，你会',
    options: ['先说为难，再慢慢把真实想法说出来', '不太会拒绝，硬着头皮也做了', '直接说不行，然后把原因讲清楚', '嘴上答应，做的时候再打折扣', '找个借口绕过去，不正面拒绝'] as const,
    scores: [4, 1, 5, 2, 3] as const,
    mother_question_id: 'G07',
    weight: 1,
  },
  {
    id: 'G16',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '你把自己真实想法原原本本讲出来的比例大概是',
    options: ['九成以上', '七成左右', '不到两成', '五成左右', '三成左右'] as const,
    scores: [5, 4, 1, 3, 2] as const,
    mother_question_id: 'G16',
    weight: 1,
  },
  {
    id: 'I13',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你觉得最舒服的位置是',
    options: ['一半一半', '有人惦记，偶尔有交集', '靠自己，不指望任何人', '能被人想起、被人需要的那种位置', '各自过各自的，联系不用太多'] as const,
    scores: [3, 4, 1, 5, 2] as const,
    mother_question_id: 'I13',
    weight: 1,
  },
  {
    id: 'E10',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '你真的很生气，你会',
    options: ['表现出来，但不会明说原因', '压下去，装作没事', '直接说出来，我气什么得让人知道', '闷着，等自己消气', '会说，但会先压一压语气'] as const,
    scores: [3, 1, 5, 2, 4] as const,
    mother_question_id: 'E10',
    weight: 1,
  },
  {
    id: 'E12',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '看到有人掉眼泪，你会跟着红了眼眶吗',
    options: ['会有点鼻酸', '不太会，我会比较镇定', '会，我很容易被带动', '看情况', '不会，我习惯先想怎么解决'] as const,
    scores: [4, 2, 5, 3, 1] as const,
    mother_question_id: 'E12',
    weight: 1,
  },
  {
    id: 'I01',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '做成一件事之后，你希望被人知道吗',
    options: ['有没有人知道都行', '比较希望，有人知道就行', '希望，被看见我会更有底', '不需要，我更愿意自己收着', '不太在意，自己知道就够了'] as const,
    scores: [3, 4, 5, 1, 2] as const,
    mother_question_id: 'I01',
    weight: 1,
  },
  {
    id: 'S01',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '你需要有完全属于自己的时间吗',
    options: ['比较需要，每周都得有', '基本不需要', '偶尔需要', '非常需要，这是我不可少的', '不太需要，有人陪着反而更自在'] as const,
    scores: [4, 1, 3, 5, 2] as const,
    mother_question_id: 'S01',
    weight: 1,
  },
  {
    id: 'G18',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '别人误会你了，你会',
    options: ['解释一遍，说不清楚就算了', '简单提一句，信不信随人', '懒得解释，时间会证明', '立刻解释，把前因后果讲完整', '不解释，心里会有点受伤'] as const,
    scores: [4, 3, 2, 5, 1] as const,
    mother_question_id: 'G18',
    weight: 1,
  },
  {
    id: 'G17',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '比起把话说清楚，你更看重',
    options: ['看情况，有些事说太清楚反而伤人', '更看重彼此体面，有些话不必挑明', '没什么比说清楚更重要', '说清楚优先，但会注意方式', '更看重气氛，宁可含糊一点'] as const,
    scores: [3, 1, 5, 4, 2] as const,
    mother_question_id: 'G17',
    weight: 1,
  },
  {
    id: 'S05',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '有人聚了个局没叫上你，你会',
    options: ['没什么，我正好有自己的安排', '挺好，我巴不得空出这个晚上', '稍微有点在意', '有点失落，希望他们能叫上我', '完全没问题，各自玩得开心'] as const,
    scores: [3, 5, 2, 1, 4] as const,
    mother_question_id: 'S05',
    weight: 1,
  },
  {
    id: 'E11',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '你更习惯用哪种方式表达在乎',
    options: ['说出来，语言最直接', '只做不说', '主要是做，不太会说', '一半说一半做', '语言和靠近的动作都会'] as const,
    scores: [5, 1, 2, 3, 4] as const,
    mother_question_id: 'E11',
    weight: 1,
  },
  {
    id: 'F02',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '谈到「五年后我在哪」，你会',
    options: ['主动想，希望现在就有个数', '想想可以，但不急着定下来', '不太想谈，到时再说', '回避这个话题，想了会有压力', '认真想，给出我能接受的范围'] as const,
    scores: [5, 3, 2, 1, 4] as const,
    mother_question_id: 'F02',
    weight: 1,
  },
  {
    id: 'X08',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '冲突里你最受不了的是',
    options: ['事情悬着不解决', '话说得太重伤到人', '场面失控，声音越来越大', '被追着要一个态度', '各自说各自的，谁也没听进去'] as const,
    scores: [5, 3, 1, 2, 4] as const,
    mother_question_id: 'X08',
    weight: 1,
  },
  {
    id: 'I03',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '和人同处一个空间、各做各的，你的感受是',
    options: ['可以，但最好时不时说两句话', '这是我最舒服的状态', '挺好的，安静地待着也舒服', '不够，我更想要有一些互动', '挺舒服的，不用刻意找话题'] as const,
    scores: [4, 1, 3, 5, 2] as const,
    mother_question_id: 'I03',
    weight: 1,
  },
  {
    id: 'S06',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '关于独处，你的感受是',
    options: ['有也可以，没有也行', '很不习惯一个人，会空落落的', '比较享受独处', '不太喜欢一个人待着', '独处给我充电，跟人待太久我会疲惫'] as const,
    scores: [3, 1, 4, 2, 5] as const,
    mother_question_id: 'S06',
    weight: 1,
  },
  {
    id: 'F04',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '一段日子过得没什么方向，你会',
    options: ['很不安，这是我不接受的状态', '无所谓，本来也不需要一直有方向', '没什么感觉，现在好就行', '会比较担心，想尽快理出个方向', '有点在意，但不至于影响现在'] as const,
    scores: [5, 1, 2, 4, 3] as const,
    mother_question_id: 'F04',
    weight: 1,
  },
  {
    id: 'S18',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '关于「每个人都该有自己的生活」，你',
    options: ['比较认同', '有点距离感，不太舒服', '非常认同，这是长久的前提', '认同，但也要有足够交集', '不太认同，亲近就该不分你我'] as const,
    scores: [4, 2, 5, 3, 1] as const,
    mother_question_id: 'S18',
    weight: 1,
  },
  {
    id: 'G14',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '发现自己刚才说错话了，你会',
    options: ['不太会承认，心里有点过意不去但说不出口', '过一会儿找机会补一句解释', '用别的话把意思圆回来', '当场就说「我刚才那句话不对」，然后重说', '当没发生过，指望别人没往心里去'] as const,
    scores: [1, 4, 3, 5, 2] as const,
    mother_question_id: 'G14',
    weight: 1,
  },
  {
    id: 'F07',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '关于金钱和储蓄，你的态度是',
    options: ['有个大概的数就行，不必太细', '钱够花就行，不用规划', '大项支出要想清楚，日常不用太紧', '希望能做长期规划，包括为几年后存钱', '不太想算钱，算了有压力'] as const,
    scores: [3, 1, 4, 5, 2] as const,
    mother_question_id: 'F07',
    weight: 1,
  },
  {
    id: 'I08',
    paper: 'P3' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你很看重的一件事，别人完全忘了，你会',
    options: ['不太在意，忘了就忘了', '有点失落，但不会说出来', '会提一句，让人知道我还记着', '会直接说我很在意这件事', '我自己也记不太清，无所谓'] as const,
    scores: [2, 3, 4, 5, 1] as const,
    mother_question_id: 'I08',
    weight: 1,
  },
];

export const PERSONALITY_QUESTIONS_4: readonly PersonalityQuestion[] = [
  {
    id: 'F07',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '关于金钱和储蓄，你的态度是',
    options: ['有个大概的数就行，不必太细', '钱够花就行，不用规划', '大项支出要想清楚，日常不用太紧', '希望能做长期规划，包括为几年后存钱', '不太想算钱，算了有压力'] as const,
    scores: [3, 1, 4, 5, 2] as const,
    mother_question_id: 'F07',
    weight: 1,
  },
  {
    id: 'X15',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '你发现有人在冷处理你，你会',
    options: ['主动递个台阶，试探还能不能聊', '也冷着，看谁先撑不住', '直接问到底是哪句话没对，把话说开', '有点慌，但不知道该怎么办，就耗着', '不打扰，等这事自己冷下来'] as const,
    scores: [4, 3, 5, 1, 2] as const,
    mother_question_id: 'X15',
    weight: 1,
  },
  {
    id: 'X04',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '你觉得自己有理，但另一方情绪很激动，你会',
    options: ['先让步，等事情冷下来再说', '继续讲道理，情绪归情绪，事情要说清', '先让人把情绪发完，等缓和了再讲事情', '干脆认下来，把这一页尽快翻过去', '不再说了，但我心里知道自己没错'] as const,
    scores: [3, 5, 4, 1, 2] as const,
    mother_question_id: 'X04',
    weight: 1,
  },
  {
    id: 'G08',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '有分歧的时候，你更倾向',
    options: ['把分歧点摆到桌面上，逐个解决', '先不提，避免把气氛弄僵', '说一半留一半，让人自己去体会', '把我的理由一条条讲出来', '先听别人怎么说，再决定我要不要讲'] as const,
    scores: [5, 1, 2, 4, 3] as const,
    mother_question_id: 'G08',
    weight: 1,
  },
  {
    id: 'E17',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '你会把自己脆弱的一面露出来吗',
    options: ['偶尔会', '很少，我不太想让人看到', '会，我觉得这没什么', '基本不会，我会一直撑着', '会，但只在很熟的人面前'] as const,
    scores: [3, 2, 5, 1, 4] as const,
    mother_question_id: 'E17',
    weight: 1,
  },
  {
    id: 'G16',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '你把自己真实想法原原本本讲出来的比例大概是',
    options: ['九成以上', '七成左右', '不到两成', '五成左右', '三成左右'] as const,
    scores: [5, 4, 1, 3, 2] as const,
    mother_question_id: 'G16',
    weight: 1,
  },
  {
    id: 'S08',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '有人想翻看你的东西（手机、笔记、账单），你会',
    options: ['可以看，但希望先说一声', '无所谓，没什么不能看的', '会给看，但心里有点别扭', '不太舒服，会先问清楚想看什么', '直接给，我没觉得有什么'] as const,
    scores: [4, 3, 2, 5, 1] as const,
    mother_question_id: 'S08',
    weight: 1,
  },
  {
    id: 'E07',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '有人为你做了一件很用心的事，你会',
    options: ['心里很感动，但什么都没表示', '说谢谢，但不会说太多', '认真说谢谢，让人知道我很喜欢', '当场就说我很感动，反应藏不住', '记在心里，用行动回报'] as const,
    scores: [1, 3, 4, 5, 2] as const,
    mother_question_id: 'E07',
    weight: 1,
  },
  {
    id: 'F10',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '为了一个不确定的机会，调整自己的计划，你的态度是',
    options: ['不会为了别的事打乱我的计划', '可以调整一部分，底线不能动', '看是什么事，小调整可以', '愿意，人生本来就要不断调整', '不太愿意，我有自己的节奏'] as const,
    scores: [1, 4, 3, 5, 2] as const,
    mother_question_id: 'F10',
    weight: 1,
  },
  {
    id: 'E18',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '关于情绪，你更倾向于',
    options: ['完全自己消化，不麻烦别人', '大部分说出来，少部分自己消化', '大部分自己消化', '流动出来，说出来就舒服了', '一半一半'] as const,
    scores: [1, 4, 2, 5, 3] as const,
    mother_question_id: 'E18',
    weight: 1,
  },
  {
    id: 'S02',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '关于「什么事都跟人一起做」，你觉得',
    options: ['不太想要，有些事我更想自己来', '挺好，我比较享受', '这正是我想要的', '偶尔就好，太多会累', '有些事一起做挺好，有些不必'] as const,
    scores: [5, 2, 1, 4, 3] as const,
    mother_question_id: 'S02',
    weight: 1,
  },
  {
    id: 'F02',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '谈到「五年后我在哪」，你会',
    options: ['主动想，希望现在就有个数', '想想可以，但不急着定下来', '不太想谈，到时再说', '回避这个话题，想了会有压力', '认真想，给出我能接受的范围'] as const,
    scores: [5, 3, 2, 1, 4] as const,
    mother_question_id: 'F02',
    weight: 1,
  },
  {
    id: 'X03',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '关于「正面冲突」，你更认同',
    options: ['可以起冲突，但要有个结果', '冲突基本没有意义，只会把事情推远', '能避免就避免，但真撞上了也不怕', '冲突太耗人，我尽量躲开', '冲突是解决问题的一种方式，比憋着强'] as const,
    scores: [4, 1, 3, 2, 5] as const,
    mother_question_id: 'X03',
    weight: 1,
  },
  {
    id: 'S15',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '你觉得最健康的边界是',
    options: ['边界感太强反而生分', '清晰划线，各自的部分互不打扰', '有边界，但可以商量', '不用太明确，彼此有分寸就行', '亲近就是不分彼此'] as const,
    scores: [2, 5, 4, 3, 1] as const,
    mother_question_id: 'S15',
    weight: 1,
  },
  {
    id: 'S01',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '你需要有完全属于自己的时间吗',
    options: ['比较需要，每周都得有', '基本不需要', '偶尔需要', '非常需要，这是我不可少的', '不太需要，有人陪着反而更自在'] as const,
    scores: [4, 1, 3, 5, 2] as const,
    mother_question_id: 'S01',
    weight: 1,
  },
  {
    id: 'F11',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '有人对你说「你这样下去不行」，你会',
    options: ['给自己设一个期限，到时必须有个结果', '认真想一次，把顾虑一条条摊开', '我也没想好，那就先这样', '听过就算，不去逼自己', '记在心里，但先按自己的节奏走'] as const,
    scores: [5, 4, 1, 2, 3] as const,
    mother_question_id: 'F11',
    weight: 1,
  },
  {
    id: 'E05',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '看电影看到动情处，你被触动了，你会',
    options: ['有点鼻酸，但忍住了', '眼眶红了，会偷偷擦一下', '心里有感触，脸上没什么反应', '眼泪直接掉，也不遮掩', '没什么特别感觉，也很少被打动'] as const,
    scores: [3, 4, 2, 5, 1] as const,
    mother_question_id: 'E05',
    weight: 1,
  },
  {
    id: 'X17',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '你会因为怕伤和气而咽下自己的意见吗',
    options: ['有时候会', '比较少', '经常这样，我几乎不坚持', '基本不会，我一定会说', '比较多'] as const,
    scores: [3, 4, 1, 5, 2] as const,
    mother_question_id: 'X17',
    weight: 1,
  },
  {
    id: 'I04',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你会在意自己的付出有没有被看见吗',
    options: ['有时候会在意', '比较在意', '偶尔会有点介意', '不太在意，我自己知道做了什么', '很在意，没人提我会有点不甘'] as const,
    scores: [3, 4, 2, 1, 5] as const,
    mother_question_id: 'I04',
    weight: 1,
  },
  {
    id: 'S07',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '你会因为想自己待着，而推掉别人的邀约吗',
    options: ['会，这对我来说很正常', '基本不会', '从来不会', '偶尔会', '很少，除非真的很累'] as const,
    scores: [5, 2, 1, 4, 3] as const,
    mother_question_id: 'S07',
    weight: 1,
  },
  {
    id: 'I07',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你会主动把自己在意什么说出来吗',
    options: ['偶尔说', '基本不说', '经常说，想到就说', '很少说，有点开不了口', '会说，但不会太频繁'] as const,
    scores: [3, 1, 5, 2, 4] as const,
    mother_question_id: 'I07',
    weight: 1,
  },
  {
    id: 'I16',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '有段时间没人找你、也没人提起你，你会',
    options: ['没什么特别感觉', '会主动联系别人，哪怕只是聊几句', '挺好，我也落得清净', '会不安，需要找人说说话', '有点不习惯，但能适应'] as const,
    scores: [2, 4, 1, 5, 3] as const,
    mother_question_id: 'I16',
    weight: 1,
  },
  {
    id: 'G03',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '有人做了件让你不太舒服的事，你的第一反应是',
    options: ['当天晚点找个气氛合适的时候再说', '不说，自己慢慢消化掉', '想说但开不了口，用别的情绪表现出来', '反复掂量要不要说，最后多半还是说了', '当场就说出来，说完这件事就翻篇'] as const,
    scores: [4, 1, 2, 3, 5] as const,
    mother_question_id: 'G03',
    weight: 1,
  },
  {
    id: 'E04',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '「我在意你」这句话，你觉得',
    options: ['偶尔说说还行', '说得出口，但要看场合', '很自然，我经常会说', '说不出来，太肉麻了', '有点开不了口'] as const,
    scores: [3, 4, 5, 1, 2] as const,
    mother_question_id: 'E04',
    weight: 1,
  },
  {
    id: 'S09',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '你觉得再近的人之间，也应该',
    options: ['完全共享，没什么要藏的', '大部分是各自的，需要时能坦诚', '各有各的边界，互不越界', '彼此透明，但不刻意查', '基本没有秘密，都可以看'] as const,
    scores: [1, 4, 5, 3, 2] as const,
    mother_question_id: 'S09',
    weight: 1,
  },
  {
    id: 'X14',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '冲突之后你最想要的收尾是',
    options: ['当没发生过，恢复原样就好', '事情有结论，接下来该怎么走很清楚', '把话说开，情绪能过去', '放一放，自然就过去了', '面上过得去，别再提这件事'] as const,
    scores: [1, 5, 4, 2, 3] as const,
    mother_question_id: 'X14',
    weight: 1,
  },
  {
    id: 'I05',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你花了心思做的事，最后没人提起，你会',
    options: ['会找个机会让人知道这是我做的', '会失落，需要有人给句明确的话', '没关系，我做是为了自己', '没什么特别的感觉', '有点空落落的，但能想通'] as const,
    scores: [4, 5, 1, 2, 3] as const,
    mother_question_id: 'I05',
    weight: 1,
  },
  {
    id: 'G15',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '发出去的消息很久没有回音，你会',
    options: ['不追问，但心里会记着这个时间差', '换个不相关的话题，把对话重新接上', '直接问是不是在忙，或者打个电话', '等一等，看事情会不会自己有下文', '什么都不做，等这事自己过去'] as const,
    scores: [2, 4, 5, 3, 1] as const,
    mother_question_id: 'G15',
    weight: 1,
  },
  {
    id: 'I10',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你需要别人明确表达对你的认可吗',
    options: ['很需要，我希望有人经常说出来', '不需要，我心里有数就行', '基本不需要', '偶尔需要', '比较需要'] as const,
    scores: [5, 1, 2, 3, 4] as const,
    mother_question_id: 'I10',
    weight: 1,
  },
  {
    id: 'F05',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '眼前出现一个和你的计划冲突的机会，你会',
    options: ['说出我的顾虑，试着找一个折中', '不太想纠结，先顺着眼前走', '直接放弃机会，按原计划来', '先听听自己更想要哪个', '把两条路摆出来，看哪条更值'] as const,
    scores: [4, 2, 1, 3, 5] as const,
    mother_question_id: 'F05',
    weight: 1,
  },
  {
    id: 'G10',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '别人问你「怎么了」，你说「没事」的时候，实际是',
    options: ['真的没事，我不需要绕弯子', '有事，但我希望别人能自己看出来', '有点事，但我需要几分钟组织语言', '有事，但我不知道怎么开口', '有事，我想等人多问一句再说'] as const,
    scores: [5, 1, 4, 2, 3] as const,
    mother_question_id: 'G10',
    weight: 1,
  },
  {
    id: 'F09',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '谈到「以后」你会觉得有压力吗',
    options: ['比较有压力', '很有压力，我尽量不谈', '基本没有', '完全没有，我很愿意谈', '有一点，但不是大问题'] as const,
    scores: [2, 1, 4, 5, 3] as const,
    mother_question_id: 'F09',
    weight: 1,
  },
  {
    id: 'I02',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '一整天都没有人找你，你会',
    options: ['没什么感觉，我也没想着联系谁', '会主动发个消息，但不提这件事', '稍微有点在意，但忍着不问', '有点纳闷，但不会主动开口', '会不踏实，忍不住先发条消息'] as const,
    scores: [1, 4, 2, 3, 5] as const,
    mother_question_id: 'I02',
    weight: 1,
  },
  {
    id: 'G13',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '你会用「我猜你是这么想的」来跟人确认吗',
    options: ['偶尔会', '会，猜完一定追一句「是这样吗」', '会，但只在比较重要的事上', '不会，我一般按自己的猜测往下走', '很少，我猜完就当是真的了'] as const,
    scores: [3, 5, 4, 1, 2] as const,
    mother_question_id: 'G13',
    weight: 1,
  },
  {
    id: 'X11',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '发现自己确实有错，你会',
    options: ['不太愿意认错，会觉得很难堪', '用行动去补，不太会说出口', '直接认，然后说我打算怎么改', '心里知道，但嘴上不会认', '会认，但说不出太具体的话'] as const,
    scores: [1, 3, 5, 2, 4] as const,
    mother_question_id: 'X11',
    weight: 1,
  },
  {
    id: 'E12',
    paper: 'P4' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '看到有人掉眼泪，你会跟着红了眼眶吗',
    options: ['会有点鼻酸', '不太会，我会比较镇定', '会，我很容易被带动', '看情况', '不会，我习惯先想怎么解决'] as const,
    scores: [4, 2, 5, 3, 1] as const,
    mother_question_id: 'E12',
    weight: 1,
  },
];

export const PERSONALITY_QUESTIONS_5: readonly PersonalityQuestion[] = [
  {
    id: 'E15',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '被当众夸奖或被点名表扬，你的感受是',
    options: ['可以接受，但会有点不好意思', '有点尴尬', '挺好的，我很享受', '很不舒服，我想躲开', '无所谓'] as const,
    scores: [4, 2, 5, 1, 3] as const,
    mother_question_id: 'E15',
    weight: 1,
  },
  {
    id: 'S16',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '没人陪、没人安排的时候，你能把自己的日子过好吗',
    options: ['很难，会一直等有人来找我', '还行，偶尔会有点空', '可以，我有自己的节奏', '完全没问题，我过得更自在', '有点难熬'] as const,
    scores: [1, 3, 4, 5, 2] as const,
    mother_question_id: 'S16',
    weight: 1,
  },
  {
    id: 'S10',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '做什么事你都想拉个人一起吗',
    options: ['比较少', '大部分想找人一起', '是的，一个人反而没劲', '有些事想一起，有些无所谓', '不是，很多事我更想一个人做'] as const,
    scores: [4, 2, 1, 3, 5] as const,
    mother_question_id: 'S10',
    weight: 1,
  },
  {
    id: 'G17',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '比起把话说清楚，你更看重',
    options: ['看情况，有些事说太清楚反而伤人', '更看重彼此体面，有些话不必挑明', '没什么比说清楚更重要', '说清楚优先，但会注意方式', '更看重气氛，宁可含糊一点'] as const,
    scores: [3, 1, 5, 4, 2] as const,
    mother_question_id: 'G17',
    weight: 1,
  },
  {
    id: 'F12',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '你会主动想「我下一步到底要什么」吗',
    options: ['偶尔想一想', '会，我觉得该早点想清楚', '基本不想', '很少，等事情推着走', '会，但不会天天想'] as const,
    scores: [3, 5, 1, 2, 4] as const,
    mother_question_id: 'F12',
    weight: 1,
  },
  {
    id: 'X09',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '有人提出一个你完全不同意的要求，你会',
    options: ['说出顾虑，试着谈一个折中方案', '不太敢反驳，先顺着再说', '明确说不同意，并给出我的理由', '先答应下来，之后再慢慢磨', '不正面回应，拖着看会不会就这么过去'] as const,
    scores: [4, 1, 5, 3, 2] as const,
    mother_question_id: 'X09',
    weight: 1,
  },
  {
    id: 'X18',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '别人道歉了，但没说到点子上，你会',
    options: ['先收下，心里还有点没过去', '说没事，但其实没真的放下', '接受道歉，但补一句我的真实感受', '明说我要的不是这一句，是另一句', '说没事，然后把这事翻篇'] as const,
    scores: [3, 2, 4, 5, 1] as const,
    mother_question_id: 'X18',
    weight: 1,
  },
  {
    id: 'E02',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '心里很难受的时候，你通常',
    options: ['说不太清自己难受什么，最后还是没说', '完全自己扛，谁也看不出来', '直接说出来，我需要有人陪着', '自己消化，不想把情绪带给别人', '会说一点，让人知道我状态不好'] as const,
    scores: [3, 1, 5, 2, 4] as const,
    mother_question_id: 'E02',
    weight: 1,
  },
  {
    id: 'E16',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '你做了件让别人不高兴的事，想道歉，你会',
    options: ['不说，等这件事过去', '说对不起，并说明我错在哪', '说对不起，但说不出更多', '用行动弥补，不太会说出口', '直接说对不起，也说出我当时的想法'] as const,
    scores: [1, 4, 3, 2, 5] as const,
    mother_question_id: 'E16',
    weight: 1,
  },
  {
    id: 'F15',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '你会定期回头看看自己这段时间走得怎么样吗',
    options: ['偶尔会想一想', '会，一年里总会有几次', '从来没有过', '很少，感觉像在给自己开会', '会，我会专门留出时间做这件事'] as const,
    scores: [3, 4, 1, 2, 5] as const,
    mother_question_id: 'F15',
    weight: 1,
  },
  {
    id: 'X06',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '有一个问题反复出现，一直没解决，你会',
    options: ['再提一次，不行就算了', '懒得再提了，习惯了', '这次一定要拿出个办法，不能再来一次', '把之前几次串起来，看它是不是有规律', '心里已经放弃解决这件事了'] as const,
    scores: [3, 2, 5, 4, 1] as const,
    mother_question_id: 'X06',
    weight: 1,
  },
  {
    id: 'S12',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '关于「钱要不要共用」，你更倾向',
    options: ['看是什么事，部分共用', '基本共用，需要就说一声', '大部分分开，只在具体事上分摊', '完全共用，不分你我', '完全分开，各自管各自的'] as const,
    scores: [3, 2, 4, 1, 5] as const,
    mother_question_id: 'S12',
    weight: 1,
  },
  {
    id: 'G12',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '要提一个别人可能不爱听的要求，你会',
    options: ['先铺垫，再把要求说出来', '拐弯抹角地说，让人自己去悟', '开门见山，要求和不接受的后果一起说', '不提了，我自己想办法解决', '试探几次，看反应再决定提不提'] as const,
    scores: [4, 2, 5, 1, 3] as const,
    mother_question_id: 'G12',
    weight: 1,
  },
  {
    id: 'F08',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '一年过去了，你还没想清楚下一步，你会',
    options: ['找人聊聊，看看别人怎么走', '有点在意，但会再等等', '挺好的，我也不急着定', '不太急，顺其自然', '主动空出时间理一理，我需要一个明确的说法'] as const,
    scores: [4, 3, 1, 2, 5] as const,
    mother_question_id: 'F08',
    weight: 1,
  },
  {
    id: 'F09',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '谈到「以后」你会觉得有压力吗',
    options: ['比较有压力', '很有压力，我尽量不谈', '基本没有', '完全没有，我很愿意谈', '有一点，但不是大问题'] as const,
    scores: [2, 1, 4, 5, 3] as const,
    mother_question_id: 'F09',
    weight: 1,
  },
  {
    id: 'G13',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '你会用「我猜你是这么想的」来跟人确认吗',
    options: ['偶尔会', '会，猜完一定追一句「是这样吗」', '会，但只在比较重要的事上', '不会，我一般按自己的猜测往下走', '很少，我猜完就当是真的了'] as const,
    scores: [3, 5, 4, 1, 2] as const,
    mother_question_id: 'G13',
    weight: 1,
  },
  {
    id: 'I18',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你会主动张罗一个局、把人聚起来吗',
    options: ['会，基本都是我在张罗', '会，我提得比较多', '很少，随缘就好', '比较少，一般别人提', '一半一半'] as const,
    scores: [5, 4, 1, 2, 3] as const,
    mother_question_id: 'I18',
    weight: 1,
  },
  {
    id: 'X08',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '冲突里你最受不了的是',
    options: ['事情悬着不解决', '话说得太重伤到人', '场面失控，声音越来越大', '被追着要一个态度', '各自说各自的，谁也没听进去'] as const,
    scores: [5, 3, 1, 2, 4] as const,
    mother_question_id: 'X08',
    weight: 1,
  },
  {
    id: 'X19',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '你觉得冲突的价值在于',
    options: ['把藏着的问题翻出来，解决掉', '有代价，但不可避免', '纯粹是消耗，越少越好', '让人看清自己的底线在哪', '基本是消耗，能避则避'] as const,
    scores: [5, 3, 1, 4, 2] as const,
    mother_question_id: 'X19',
    weight: 1,
  },
  {
    id: 'E10',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '你真的很生气，你会',
    options: ['表现出来，但不会明说原因', '压下去，装作没事', '直接说出来，我气什么得让人知道', '闷着，等自己消气', '会说，但会先压一压语气'] as const,
    scores: [3, 1, 5, 2, 4] as const,
    mother_question_id: 'E10',
    weight: 1,
  },
  {
    id: 'S04',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '你有自己的圈子、自己的事在做，这件事对你有多重要',
    options: ['一般重要', '非常重要，这是我的根基', '比较重要', '不太重要，跟着大家一起就行', '有点重要，但不是必需'] as const,
    scores: [3, 5, 4, 1, 2] as const,
    mother_question_id: 'S04',
    weight: 1,
  },
  {
    id: 'G07',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '你想拒绝一个不太合理的要求，你会',
    options: ['先说为难，再慢慢把真实想法说出来', '不太会拒绝，硬着头皮也做了', '直接说不行，然后把原因讲清楚', '嘴上答应，做的时候再打折扣', '找个借口绕过去，不正面拒绝'] as const,
    scores: [4, 1, 5, 2, 3] as const,
    mother_question_id: 'G07',
    weight: 1,
  },
  {
    id: 'I12',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你会因为没人回应而反复看手机吗',
    options: ['有时候会', '经常会，忍不住一直看', '比较多', '偶尔会', '从来不会'] as const,
    scores: [3, 5, 4, 2, 1] as const,
    mother_question_id: 'I12',
    weight: 1,
  },
  {
    id: 'F13',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '你更相信',
    options: ['变化太多，计划没什么用', '有方向比没方向好', '人生不需要按计划走', '规划清楚了，路才走得稳', '方向和灵活都要有'] as const,
    scores: [2, 4, 1, 5, 3] as const,
    mother_question_id: 'F13',
    weight: 1,
  },
  {
    id: 'I11',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '有人说「这件事我自己来就行」，你的第一反应是',
    options: ['没问题，我找点别的事做', '会有点失落，想知道是不是我哪里没做好', 'OK，不用多想', '可以，但希望最后能跟我同步一下', '正好，我也能腾出手'] as const,
    scores: [3, 5, 2, 4, 1] as const,
    mother_question_id: 'I11',
    weight: 1,
  },
  {
    id: 'G09',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '话到嘴边又咽回去的情况，你身上多吗',
    options: ['比较少', '几乎没有，我想说的都会说', '经常这样，很多话最后都没说', '有时候会', '比较多'] as const,
    scores: [4, 5, 1, 3, 2] as const,
    mother_question_id: 'G09',
    weight: 1,
  },
  {
    id: 'S03',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '连续几天被人约满，你会',
    options: ['挺好，我没问题', '正合我意，我就怕闲着', '有点喘不过气，我需要留出几天给自己', '可以，但隔几天我想空一天', '可以，但我需要提前说好哪几天是我的'] as const,
    scores: [2, 1, 5, 3, 4] as const,
    mother_question_id: 'S03',
    weight: 1,
  },
  {
    id: 'I14',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你主动递出一个善意，没什么回音，你会',
    options: ['会难受，需要弄明白是怎么回事', '无所谓，收回就好', '有点尴尬，先缓一缓', '会再试一次，或者直接问一句', '不太在意，可能没看到'] as const,
    scores: [5, 1, 3, 4, 2] as const,
    mother_question_id: 'I14',
    weight: 1,
  },
  {
    id: 'E18',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '关于情绪，你更倾向于',
    options: ['完全自己消化，不麻烦别人', '大部分说出来，少部分自己消化', '大部分自己消化', '流动出来，说出来就舒服了', '一半一半'] as const,
    scores: [1, 4, 2, 5, 3] as const,
    mother_question_id: 'E18',
    weight: 1,
  },
  {
    id: 'E03',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'E' as PersonalityDimension,
    text: '你的高兴和不高兴，脸上藏得住吗',
    options: ['完全藏不住，一眼就能看出来', '基本藏不住', '很能藏，别人基本看不出来', '比较能藏', '看情况'] as const,
    scores: [5, 4, 1, 2, 3] as const,
    mother_question_id: 'E03',
    weight: 1,
  },
  {
    id: 'F16',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'F' as PersonalityDimension,
    text: '关于「把计划定死」，你觉得',
    options: ['有点压力，能晚就晚', '定不定都行，不是必需品', '这是迟早的事，我希望早点定下来', '看状态，不急', '想清楚了就该写下来'] as const,
    scores: [2, 1, 5, 3, 4] as const,
    mother_question_id: 'F16',
    weight: 1,
  },
  {
    id: 'I08',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你很看重的一件事，别人完全忘了，你会',
    options: ['不太在意，忘了就忘了', '有点失落，但不会说出来', '会提一句，让人知道我还记着', '会直接说我很在意这件事', '我自己也记不太清，无所谓'] as const,
    scores: [2, 3, 4, 5, 1] as const,
    mother_question_id: 'I08',
    weight: 1,
  },
  {
    id: 'I04',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'I' as PersonalityDimension,
    text: '你会在意自己的付出有没有被看见吗',
    options: ['有时候会在意', '比较在意', '偶尔会有点介意', '不太在意，我自己知道做了什么', '很在意，没人提我会有点不甘'] as const,
    scores: [3, 4, 2, 1, 5] as const,
    mother_question_id: 'I04',
    weight: 1,
  },
  {
    id: 'S11',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'S' as PersonalityDimension,
    text: '有人提出要跟你合住／合伙做事，你会',
    options: ['很开心，我早就想了', '可以，但得先约法几章', '可以，但需要过渡一下', '有点警惕，我需要先谈清楚边界', '挺好，直接来吧'] as const,
    scores: [1, 4, 3, 5, 2] as const,
    mother_question_id: 'S11',
    weight: 1,
  },
  {
    id: 'X16',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'X' as PersonalityDimension,
    text: '事情僵住了，你会先做什么',
    options: ['先去倒杯水、做点别的，缓一缓气氛', '先离开这个空间，各自待一会儿', '先聊最容易达成一致的那部分', '把分歧点一条条写下来，逐个谈', '不做任何事，等它自己过去'] as const,
    scores: [3, 2, 4, 5, 1] as const,
    mother_question_id: 'X16',
    weight: 1,
  },
  {
    id: 'G05',
    paper: 'P5' as PersonalityPaperId,
    dimension: 'G' as PersonalityDimension,
    text: '要跟人商量一件挺重要的事，你会',
    options: ['先探探别人的口风，顺着往下接', '我先说我的，再听别人的意见', '不太想谈，能拖就拖一拖', '让别人先拿主意，我配合就行', '先把各自的想法摊开，再一项项对'] as const,
    scores: [3, 4, 1, 2, 5] as const,
    mother_question_id: 'G05',
    weight: 1,
  },
];

/** 全部题目（5 套卷） */
export const PERSONALITY_ALL_QUESTIONS: readonly PersonalityQuestion[] = [
  ...PERSONALITY_QUESTIONS_1,
  ...PERSONALITY_QUESTIONS_2,
  ...PERSONALITY_QUESTIONS_3,
  ...PERSONALITY_QUESTIONS_4,
  ...PERSONALITY_QUESTIONS_5,
];

/** 按 paper + dimension 取题 */
export function getQuestionsByPaperAndDim(paper: PersonalityPaperId, dim: PersonalityDimension): readonly PersonalityQuestion[] {
  const list = paper === "P1" ? PERSONALITY_QUESTIONS_1 : paper === "P2" ? PERSONALITY_QUESTIONS_2
    : paper === "P3" ? PERSONALITY_QUESTIONS_3 : paper === "P4" ? PERSONALITY_QUESTIONS_4 : PERSONALITY_QUESTIONS_5;
  return list.filter(q => q.dimension === dim);
}

/** 按 mother_question_id 找所有出现（用于锚题一致性校验） */
export function findByMotherId(mid: string): readonly PersonalityQuestion[] {
  return PERSONALITY_ALL_QUESTIONS.filter(q => q.mother_question_id === mid);
}