// =====================================================
// 人格测试 v5 — 30 张月相卡（P01-P15 主卡 + T01-T15 过渡卡）
// 来源：交付/卡片数据.json（2026-09-13）
// 匹配：6 维中心向量 vec[]，余弦相似度排序取 Top3
// 渲染：每张卡对应 ./动画卡/v5_{id}_{name}.html（Top1 真嵌，Top2/3 嵌但暂停动画）
// =====================================================

import { V2_DIMENSIONS } from './dimensions';

export interface V2Card {
  /** 卡 ID：P01-P15 主卡 / T01-T15 过渡卡 */
  id: string;
  /** 月相序号 1-30 */
  no: number;
  /** 主 / 过渡 */
  type: "主" | "过渡";
  /** 卡名（4 字） */
  name: string;
  /** 密钥（2 字） */
  key: string;
  /** 判词 */
  line: string;
  /** 月相：朔 / 蛾眉 / 上弦 / 盈凸 / 望 / 亏凸 / 下弦 */
  phase: string;
  phase_en: string;
  /** 6 维中心向量 [G,X,I,F,S,E] —— 50 = 中性，85 = 显著高，15 = 显著低 */
  vec: readonly number[];
  /** 极性描述（人话） */
  poles: string;
  /** 极性维度（按这个聚类） */
  pole_dims: readonly (typeof V2_DIMENSIONS[number])[];
  /** 过渡卡才有：介于哪两张主卡 */
  between?: string;
  /** 动画卡静态路径（运行时拼） */
  html_path: string;
}

export const V2_CARDS: readonly V2Card[] = [
  {
    id: "P01",
    no: 1,
    type: "主",
    name: "暗礁无声",
    key: "沉底",
    line: "你低调的存在，是别人看不见的那块支点。",
    phase: "朔",
    phase_en: "NEW MOON",
    vec: [50, 50, 50, 50, 85, 15] as const,
    poles: "S↑ E↓",
    pole_dims: ['E', 'S'] as const,
    html_path: `/personality-v2/cards/v5_P01_暗礁无声.html`,
  },
  {
    id: "P02",
    no: 2,
    type: "主",
    name: "星火未燎",
    key: "初燃",
    line: "再小的一个动作，也可以点燃后来的一整片天。",
    phase: "蛾眉",
    phase_en: "WAXING CRESCENT",
    vec: [15, 50, 50, 50, 50, 15] as const,
    poles: "G↓ E↓",
    pole_dims: ['E', 'G'] as const,
    html_path: `/personality-v2/cards/v5_P02_星火未燎.html`,
  },
  {
    id: "P03",
    no: 3,
    type: "主",
    name: "微光不争",
    key: "照暗",
    line: "你不必大声，也能照到别人没注意的那个角落。",
    phase: "蛾眉",
    phase_en: "WAXING CRESCENT",
    vec: [50, 50, 15, 50, 50, 85] as const,
    poles: "I↓ E↑",
    pole_dims: ['E', 'I'] as const,
    html_path: `/personality-v2/cards/v5_P03_微光不争.html`,
  },
  {
    id: "P04",
    no: 4,
    type: "主",
    name: "先行探路",
    key: "知远",
    line: "你不必站在最前面，路总是你先看见的。",
    phase: "上弦",
    phase_en: "FIRST QUARTER",
    vec: [50, 15, 50, 85, 50, 50] as const,
    poles: "X↓ F↑",
    pole_dims: ['F', 'X'] as const,
    html_path: `/personality-v2/cards/v5_P04_先行探路.html`,
  },
  {
    id: "P05",
    no: 5,
    type: "主",
    name: "静观一室",
    key: "见全",
    line: "你说得很少，但你把整间屋子都看完了。",
    phase: "上弦",
    phase_en: "FIRST QUARTER",
    vec: [15, 15, 50, 50, 50, 50] as const,
    poles: "G↓ X↓",
    pole_dims: ['G', 'X'] as const,
    html_path: `/personality-v2/cards/v5_P05_静观一室.html`,
  },
  {
    id: "P06",
    no: 6,
    type: "主",
    name: "解缆离岸",
    key: "不回",
    line: "解缆的时候你很慢，但一旦离岸，就不会回头。",
    phase: "上弦",
    phase_en: "FIRST QUARTER",
    vec: [50, 85, 50, 85, 50, 50] as const,
    poles: "X↑ F↑",
    pole_dims: ['F', 'X'] as const,
    html_path: `/personality-v2/cards/v5_P06_解缆离岸.html`,
  },
  {
    id: "P07",
    no: 7,
    type: "主",
    name: "涉川不止",
    key: "在途",
    line: "你不太提以后要去哪，但地图上的空白一直在勾你。",
    phase: "盈凸",
    phase_en: "WAXING GIBBOUS",
    vec: [15, 50, 50, 15, 50, 50] as const,
    poles: "G↓ F↓",
    pole_dims: ['F', 'G'] as const,
    html_path: `/personality-v2/cards/v5_P07_涉川不止.html`,
  },
  {
    id: "P08",
    no: 8,
    type: "主",
    name: "守夜到明",
    key: "甘后",
    line: "只要是值得的人，你甘愿排在第二位。",
    phase: "盈凸",
    phase_en: "WAXING GIBBOUS",
    vec: [50, 50, 85, 50, 15, 50] as const,
    poles: "I↑ S↓",
    pole_dims: ['I', 'S'] as const,
    html_path: `/personality-v2/cards/v5_P08_守夜到明.html`,
  },
  {
    id: "P09",
    no: 9,
    type: "主",
    name: "定盘在心",
    key: "自主",
    line: "你不是不需要别人，只是习惯先听自己的那句。",
    phase: "盈凸",
    phase_en: "WAXING GIBBOUS",
    vec: [50, 85, 50, 50, 15, 50] as const,
    poles: "X↑ S↓",
    pole_dims: ['S', 'X'] as const,
    html_path: `/personality-v2/cards/v5_P09_定盘在心.html`,
  },
  {
    id: "P10",
    no: 10,
    type: "主",
    name: "破晓即行",
    key: "先动",
    line: "你不等天亮，你自己就是天亮。",
    phase: "望",
    phase_en: "FULL MOON",
    vec: [50, 50, 50, 15, 50, 85] as const,
    poles: "F↓ E↑",
    pole_dims: ['E', 'F'] as const,
    html_path: `/personality-v2/cards/v5_P10_破晓即行.html`,
  },
  {
    id: "P11",
    no: 11,
    type: "主",
    name: "织网相连",
    key: "结缘",
    line: "你能让几个完全不同的人，在同一个屋顶下各自舒服。",
    phase: "望",
    phase_en: "FULL MOON",
    vec: [85, 85, 50, 50, 50, 50] as const,
    poles: "G↑ X↑",
    pole_dims: ['G', 'X'] as const,
    html_path: `/personality-v2/cards/v5_P11_织网相连.html`,
  },
  {
    id: "P12",
    no: 12,
    type: "主",
    name: "自造其光",
    key: "不群",
    line: "别人走过的路，你走上去就觉得缺氧。",
    phase: "望",
    phase_en: "FULL MOON",
    vec: [50, 50, 15, 50, 85, 50] as const,
    poles: "I↓ S↑",
    pole_dims: ['I', 'S'] as const,
    html_path: `/personality-v2/cards/v5_P12_自造其光.html`,
  },
  {
    id: "P13",
    no: 13,
    type: "主",
    name: "漫游界间",
    key: "跨界",
    line: "你不属于任何一片世界，你站在它们交界的地方。",
    phase: "亏凸",
    phase_en: "WANING GIBBOUS",
    vec: [50, 50, 50, 50, 85, 85] as const,
    poles: "S↑ E↑",
    pole_dims: ['E', 'S'] as const,
    html_path: `/personality-v2/cards/v5_P13_漫游界间.html`,
  },
  {
    id: "P14",
    no: 14,
    type: "主",
    name: "执舵在手",
    key: "定调",
    line: "方向盘在你手里，别人才能安心看风景。",
    phase: "下弦",
    phase_en: "LAST QUARTER",
    vec: [50, 50, 85, 85, 50, 50] as const,
    poles: "I↑ F↑",
    pole_dims: ['F', 'I'] as const,
    html_path: `/personality-v2/cards/v5_P14_执舵在手.html`,
  },
  {
    id: "P15",
    no: 15,
    type: "主",
    name: "观澜见来",
    key: "知来",
    line: "别人看得见一朵浪，你看见的是整片海的来路。",
    phase: "下弦",
    phase_en: "LAST QUARTER",
    vec: [85, 50, 15, 50, 50, 50] as const,
    poles: "G↑ I↓",
    pole_dims: ['G', 'I'] as const,
    html_path: `/personality-v2/cards/v5_P15_观澜见来.html`,
  },
  {
    id: "T01",
    no: 1,
    type: "过渡",
    name: "暗处生温",
    key: "将燃",
    line: "别人以为你沉在原地，其实水下那一点，已经开始发热。",
    phase: "蛾眉",
    phase_en: "WAXING CRESCENT",
    vec: [32.5, 50, 50, 50, 67.5, 15] as const,
    poles: "G·↓ S·↑ E↓",
    pole_dims: ['E', 'G', 'S'] as const,
    between: "暗礁无声 → 星火未燎",
    html_path: `/personality-v2/cards/v5_T01_暗处生温.html`,
  },
  {
    id: "T02",
    no: 2,
    type: "过渡",
    name: "微芒渐明",
    key: "初形",
    line: "那一点点火，慢慢有了自己的形状。",
    phase: "蛾眉",
    phase_en: "WAXING CRESCENT",
    vec: [32.5, 50, 32.5, 50, 50, 50] as const,
    poles: "G·↓ I·↓",
    pole_dims: ['G', 'I'] as const,
    between: "星火未燎 → 微光不争",
    html_path: `/personality-v2/cards/v5_T02_微芒渐明.html`,
  },
  {
    id: "T03",
    no: 3,
    type: "过渡",
    name: "照见前路",
    key: "成路",
    line: "你先照亮了角落，才看清角落外面还有路。",
    phase: "上弦",
    phase_en: "FIRST QUARTER",
    vec: [50, 32.5, 32.5, 67.5, 50, 67.5] as const,
    poles: "X·↓ I·↓ F·↑ E·↑",
    pole_dims: ['E', 'F', 'I', 'X'] as const,
    between: "微光不争 → 先行探路",
    html_path: `/personality-v2/cards/v5_T03_照见前路.html`,
  },
  {
    id: "T04",
    no: 4,
    type: "过渡",
    name: "且行且看",
    key: "且看",
    line: "你已经上了路，也开始停下来抬头看地形。",
    phase: "上弦",
    phase_en: "FIRST QUARTER",
    vec: [32.5, 15, 50, 67.5, 50, 50] as const,
    poles: "G·↓ X↓ F·↑",
    pole_dims: ['F', 'G', 'X'] as const,
    between: "先行探路 → 静观一室",
    html_path: `/personality-v2/cards/v5_T04_且行且看.html`,
  },
  {
    id: "T05",
    no: 5,
    type: "过渡",
    name: "观尽起锚",
    key: "起锚",
    line: "你看够了，然后才把手放上缆绳。",
    phase: "上弦",
    phase_en: "FIRST QUARTER",
    vec: [32.5, 50, 50, 67.5, 50, 50] as const,
    poles: "G·↓ F·↑",
    pole_dims: ['F', 'G'] as const,
    between: "静观一室 → 解缆离岸",
    html_path: `/personality-v2/cards/v5_T05_观尽起锚.html`,
  },
  {
    id: "T06",
    no: 6,
    type: "过渡",
    name: "出港不问",
    key: "帆张",
    line: "一离开码头，你就想去地图上空白的地方。",
    phase: "盈凸",
    phase_en: "WAXING GIBBOUS",
    vec: [32.5, 67.5, 50, 50, 50, 50] as const,
    poles: "G·↓ X·↑",
    pole_dims: ['G', 'X'] as const,
    between: "解缆离岸 → 涉川不止",
    html_path: `/personality-v2/cards/v5_T06_出港不问.html`,
  },
  {
    id: "T07",
    no: 7,
    type: "过渡",
    name: "远行有念",
    key: "有系",
    line: "走得再远，你心里也留着一盏回去的灯。",
    phase: "盈凸",
    phase_en: "WAXING GIBBOUS",
    vec: [32.5, 50, 67.5, 32.5, 32.5, 50] as const,
    poles: "G·↓ I·↑ F·↓ S·↓",
    pole_dims: ['F', 'G', 'I', 'S'] as const,
    between: "涉川不止 → 守夜到明",
    html_path: `/personality-v2/cards/v5_T07_远行有念.html`,
  },
  {
    id: "T08",
    no: 8,
    type: "过渡",
    name: "守而有度",
    key: "有底",
    line: "你会把自己放第二，但底下的那条线不会让。",
    phase: "盈凸",
    phase_en: "WAXING GIBBOUS",
    vec: [50, 67.5, 67.5, 50, 15, 50] as const,
    poles: "X·↑ I·↑ S↓",
    pole_dims: ['I', 'S', 'X'] as const,
    between: "守夜到明 → 定盘在心",
    html_path: `/personality-v2/cards/v5_T08_守而有度.html`,
  },
  {
    id: "T09",
    no: 9,
    type: "过渡",
    name: "谋定而动",
    key: "待晓",
    line: "你心里早有答案，只是等天亮才肯动。",
    phase: "望",
    phase_en: "FULL MOON",
    vec: [50, 67.5, 50, 32.5, 32.5, 67.5] as const,
    poles: "X·↑ F·↓ S·↓ E·↑",
    pole_dims: ['E', 'F', 'S', 'X'] as const,
    between: "定盘在心 → 破晓即行",
    html_path: `/personality-v2/cards/v5_T09_谋定而动.html`,
  },
  {
    id: "T10",
    no: 10,
    type: "过渡",
    name: "动而聚人",
    key: "群随",
    line: "你先冲了出去，回头发现身后已经聚了一群人。",
    phase: "望",
    phase_en: "FULL MOON",
    vec: [67.5, 67.5, 50, 32.5, 50, 67.5] as const,
    poles: "G·↑ X·↑ F·↓ E·↑",
    pole_dims: ['E', 'F', 'G', 'X'] as const,
    between: "破晓即行 → 织网相连",
    html_path: `/personality-v2/cards/v5_T10_动而聚人.html`,
  },
  {
    id: "T11",
    no: 11,
    type: "过渡",
    name: "联而新作",
    key: "新造",
    line: "把人连起来还不够，你想让他们看见从没见过的东西。",
    phase: "望",
    phase_en: "FULL MOON",
    vec: [67.5, 67.5, 32.5, 50, 67.5, 50] as const,
    poles: "G·↑ X·↑ I·↓ S·↑",
    pole_dims: ['G', 'I', 'S', 'X'] as const,
    between: "织网相连 → 自造其光",
    html_path: `/personality-v2/cards/v5_T11_联而新作.html`,
  },
  {
    id: "T12",
    no: 12,
    type: "过渡",
    name: "作而无界",
    key: "无界",
    line: "你造出来的东西，从来不肯只待在一个世界里。",
    phase: "亏凸",
    phase_en: "WANING GIBBOUS",
    vec: [50, 50, 32.5, 50, 85, 67.5] as const,
    poles: "I·↓ S↑ E·↑",
    pole_dims: ['E', 'I', 'S'] as const,
    between: "自造其光 → 漫游界间",
    html_path: `/personality-v2/cards/v5_T12_作而无界.html`,
  },
  {
    id: "T13",
    no: 13,
    type: "过渡",
    name: "跨界定舵",
    key: "掌向",
    line: "站在几个世界的交界久了，你学会了自己掌方向盘。",
    phase: "下弦",
    phase_en: "LAST QUARTER",
    vec: [50, 50, 67.5, 67.5, 67.5, 67.5] as const,
    poles: "I·↑ F·↑ S·↑ E·↑",
    pole_dims: ['E', 'F', 'I', 'S'] as const,
    between: "漫游界间 → 执舵在手",
    html_path: `/personality-v2/cards/v5_T13_跨界定舵.html`,
  },
  {
    id: "T14",
    no: 14,
    type: "过渡",
    name: "掌而览尽",
    key: "海阔",
    line: "方向握稳之后，你才抬起头看整片海的走势。",
    phase: "下弦",
    phase_en: "LAST QUARTER",
    vec: [67.5, 50, 50, 67.5, 50, 50] as const,
    poles: "G·↑ F·↑",
    pole_dims: ['F', 'G'] as const,
    between: "执舵在手 → 观澜见来",
    html_path: `/personality-v2/cards/v5_T14_掌而览尽.html`,
  },
  {
    id: "T15",
    no: 15,
    type: "过渡",
    name: "览而归沉",
    key: "归礁",
    line: "看完整片海，你又沉了回去，等着下一次涨潮。",
    phase: "朔",
    phase_en: "NEW MOON",
    vec: [67.5, 50, 32.5, 50, 67.5, 32.5] as const,
    poles: "G·↑ I·↓ S·↑ E·↓",
    pole_dims: ['E', 'G', 'I', 'S'] as const,
    between: "观澜见来 → 暗礁无声",
    html_path: `/personality-v2/cards/v5_T15_览而归沉.html`,
  },
] as const;

/** Map by id（O(1) 查找） */
export const V2_CARD_BY_ID: Readonly<Record<string, V2Card>> = Object.freeze(
  Object.fromEntries(V2_CARDS.map(c => [c.id, c]))
);

export function getCardById(id: string): V2Card | undefined {
  return V2_CARD_BY_ID[id];
}